// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: sologenic/com-fs-utils-lib/models/metadata/metadata.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { Timestamp } from "../../../../google/protobuf/timestamp";

export const protobufPackage = "metadata";

export enum Network {
  /** NETWORK_DO_NOT_USE - Avoid a default value since a default and a bug are not distinguishable */
  NETWORK_DO_NOT_USE = 0,
  MAINNET = 1,
  TESTNET = 2,
  DEVNET = 3,
  UNRECOGNIZED = -1,
}

export function networkFromJSON(object: any): Network {
  switch (object) {
    case 0:
    case "NETWORK_DO_NOT_USE":
      return Network.NETWORK_DO_NOT_USE;
    case 1:
    case "MAINNET":
      return Network.MAINNET;
    case 2:
    case "TESTNET":
      return Network.TESTNET;
    case 3:
    case "DEVNET":
      return Network.DEVNET;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Network.UNRECOGNIZED;
  }
}

export function networkToJSON(object: Network): string {
  switch (object) {
    case Network.NETWORK_DO_NOT_USE:
      return "NETWORK_DO_NOT_USE";
    case Network.MAINNET:
      return "MAINNET";
    case Network.TESTNET:
      return "TESTNET";
    case Network.DEVNET:
      return "DEVNET";
    case Network.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface MetaData {
  /** mainnet, testnet, devnet, can also be some virtually defined network (extra devnet for testing, extra mainnnet node for scanning historical blocks, etc) */
  Network: Network;
  UpdatedAt:
    | Date
    | undefined;
  /** Internal to listener */
  CreatedAt: Date | undefined;
  UpdatedByAccount?: string | undefined;
  MetaDataDetails?: MetaDataDetails | undefined;
}

export interface MetaDataDetails {
  /** required */
  name: string;
  /** required */
  description: string;
  /** required */
  image: string;
  /** required */
  externalUrl: string;
  /** required */
  addressLine1: string;
  /** optional */
  addressLine2?:
    | string
    | undefined;
  /** required */
  city: string;
  /** optional */
  region?:
    | string
    | undefined;
  /** optional */
  postalCode?:
    | string
    | undefined;
  /** required */
  country: string;
  /** required */
  yearFounded: number;
  /** required */
  licensed: boolean;
  /** optional */
  licenseCountry?:
    | string
    | undefined;
  /** optional */
  licenseNumber?:
    | string
    | undefined;
  /** optional */
  phone?:
    | string
    | undefined;
  /** optional */
  email?:
    | string
    | undefined;
  /** optional (list of links) */
  socialMediaLinks: string[];
  /** JSON array string */
  keyClients?:
    | string
    | undefined;
  /** JSON array string */
  press?: string | undefined;
}

function createBaseMetaData(): MetaData {
  return {
    Network: 0,
    UpdatedAt: undefined,
    CreatedAt: undefined,
    UpdatedByAccount: undefined,
    MetaDataDetails: undefined,
  };
}

export const MetaData = {
  encode(message: MetaData, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Network !== 0) {
      writer.uint32(8).int32(message.Network);
    }
    if (message.UpdatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.UpdatedAt), writer.uint32(18).fork()).ldelim();
    }
    if (message.CreatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.CreatedAt), writer.uint32(26).fork()).ldelim();
    }
    if (message.UpdatedByAccount !== undefined) {
      writer.uint32(34).string(message.UpdatedByAccount);
    }
    if (message.MetaDataDetails !== undefined) {
      MetaDataDetails.encode(message.MetaDataDetails, writer.uint32(42).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MetaData {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMetaData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.Network = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.UpdatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.CreatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.UpdatedByAccount = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.MetaDataDetails = MetaDataDetails.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MetaData {
    return {
      Network: isSet(object.Network) ? networkFromJSON(object.Network) : 0,
      UpdatedAt: isSet(object.UpdatedAt) ? fromJsonTimestamp(object.UpdatedAt) : undefined,
      CreatedAt: isSet(object.CreatedAt) ? fromJsonTimestamp(object.CreatedAt) : undefined,
      UpdatedByAccount: isSet(object.UpdatedByAccount) ? globalThis.String(object.UpdatedByAccount) : undefined,
      MetaDataDetails: isSet(object.MetaDataDetails) ? MetaDataDetails.fromJSON(object.MetaDataDetails) : undefined,
    };
  },

  toJSON(message: MetaData): unknown {
    const obj: any = {};
    if (message.Network !== 0) {
      obj.Network = networkToJSON(message.Network);
    }
    if (message.UpdatedAt !== undefined) {
      obj.UpdatedAt = message.UpdatedAt.toISOString();
    }
    if (message.CreatedAt !== undefined) {
      obj.CreatedAt = message.CreatedAt.toISOString();
    }
    if (message.UpdatedByAccount !== undefined) {
      obj.UpdatedByAccount = message.UpdatedByAccount;
    }
    if (message.MetaDataDetails !== undefined) {
      obj.MetaDataDetails = MetaDataDetails.toJSON(message.MetaDataDetails);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MetaData>, I>>(base?: I): MetaData {
    return MetaData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MetaData>, I>>(object: I): MetaData {
    const message = createBaseMetaData();
    message.Network = object.Network ?? 0;
    message.UpdatedAt = object.UpdatedAt ?? undefined;
    message.CreatedAt = object.CreatedAt ?? undefined;
    message.UpdatedByAccount = object.UpdatedByAccount ?? undefined;
    message.MetaDataDetails = (object.MetaDataDetails !== undefined && object.MetaDataDetails !== null)
      ? MetaDataDetails.fromPartial(object.MetaDataDetails)
      : undefined;
    return message;
  },
};

function createBaseMetaDataDetails(): MetaDataDetails {
  return {
    name: "",
    description: "",
    image: "",
    externalUrl: "",
    addressLine1: "",
    addressLine2: undefined,
    city: "",
    region: undefined,
    postalCode: undefined,
    country: "",
    yearFounded: 0,
    licensed: false,
    licenseCountry: undefined,
    licenseNumber: undefined,
    phone: undefined,
    email: undefined,
    socialMediaLinks: [],
    keyClients: undefined,
    press: undefined,
  };
}

export const MetaDataDetails = {
  encode(message: MetaDataDetails, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(18).string(message.description);
    }
    if (message.image !== "") {
      writer.uint32(26).string(message.image);
    }
    if (message.externalUrl !== "") {
      writer.uint32(34).string(message.externalUrl);
    }
    if (message.addressLine1 !== "") {
      writer.uint32(42).string(message.addressLine1);
    }
    if (message.addressLine2 !== undefined) {
      writer.uint32(50).string(message.addressLine2);
    }
    if (message.city !== "") {
      writer.uint32(58).string(message.city);
    }
    if (message.region !== undefined) {
      writer.uint32(66).string(message.region);
    }
    if (message.postalCode !== undefined) {
      writer.uint32(74).string(message.postalCode);
    }
    if (message.country !== "") {
      writer.uint32(82).string(message.country);
    }
    if (message.yearFounded !== 0) {
      writer.uint32(88).int32(message.yearFounded);
    }
    if (message.licensed !== false) {
      writer.uint32(96).bool(message.licensed);
    }
    if (message.licenseCountry !== undefined) {
      writer.uint32(106).string(message.licenseCountry);
    }
    if (message.licenseNumber !== undefined) {
      writer.uint32(114).string(message.licenseNumber);
    }
    if (message.phone !== undefined) {
      writer.uint32(122).string(message.phone);
    }
    if (message.email !== undefined) {
      writer.uint32(130).string(message.email);
    }
    for (const v of message.socialMediaLinks) {
      writer.uint32(138).string(v!);
    }
    if (message.keyClients !== undefined) {
      writer.uint32(146).string(message.keyClients);
    }
    if (message.press !== undefined) {
      writer.uint32(154).string(message.press);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MetaDataDetails {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMetaDataDetails();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.description = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.image = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.externalUrl = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.addressLine1 = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.addressLine2 = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.city = reader.string();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.region = reader.string();
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.postalCode = reader.string();
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.country = reader.string();
          continue;
        case 11:
          if (tag !== 88) {
            break;
          }

          message.yearFounded = reader.int32();
          continue;
        case 12:
          if (tag !== 96) {
            break;
          }

          message.licensed = reader.bool();
          continue;
        case 13:
          if (tag !== 106) {
            break;
          }

          message.licenseCountry = reader.string();
          continue;
        case 14:
          if (tag !== 114) {
            break;
          }

          message.licenseNumber = reader.string();
          continue;
        case 15:
          if (tag !== 122) {
            break;
          }

          message.phone = reader.string();
          continue;
        case 16:
          if (tag !== 130) {
            break;
          }

          message.email = reader.string();
          continue;
        case 17:
          if (tag !== 138) {
            break;
          }

          message.socialMediaLinks.push(reader.string());
          continue;
        case 18:
          if (tag !== 146) {
            break;
          }

          message.keyClients = reader.string();
          continue;
        case 19:
          if (tag !== 154) {
            break;
          }

          message.press = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MetaDataDetails {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      image: isSet(object.image) ? globalThis.String(object.image) : "",
      externalUrl: isSet(object.externalUrl) ? globalThis.String(object.externalUrl) : "",
      addressLine1: isSet(object.addressLine1) ? globalThis.String(object.addressLine1) : "",
      addressLine2: isSet(object.addressLine2) ? globalThis.String(object.addressLine2) : undefined,
      city: isSet(object.city) ? globalThis.String(object.city) : "",
      region: isSet(object.region) ? globalThis.String(object.region) : undefined,
      postalCode: isSet(object.postalCode) ? globalThis.String(object.postalCode) : undefined,
      country: isSet(object.country) ? globalThis.String(object.country) : "",
      yearFounded: isSet(object.yearFounded) ? globalThis.Number(object.yearFounded) : 0,
      licensed: isSet(object.licensed) ? globalThis.Boolean(object.licensed) : false,
      licenseCountry: isSet(object.licenseCountry) ? globalThis.String(object.licenseCountry) : undefined,
      licenseNumber: isSet(object.licenseNumber) ? globalThis.String(object.licenseNumber) : undefined,
      phone: isSet(object.phone) ? globalThis.String(object.phone) : undefined,
      email: isSet(object.email) ? globalThis.String(object.email) : undefined,
      socialMediaLinks: globalThis.Array.isArray(object?.socialMediaLinks)
        ? object.socialMediaLinks.map((e: any) => globalThis.String(e))
        : [],
      keyClients: isSet(object.keyClients) ? globalThis.String(object.keyClients) : undefined,
      press: isSet(object.press) ? globalThis.String(object.press) : undefined,
    };
  },

  toJSON(message: MetaDataDetails): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.image !== "") {
      obj.image = message.image;
    }
    if (message.externalUrl !== "") {
      obj.externalUrl = message.externalUrl;
    }
    if (message.addressLine1 !== "") {
      obj.addressLine1 = message.addressLine1;
    }
    if (message.addressLine2 !== undefined) {
      obj.addressLine2 = message.addressLine2;
    }
    if (message.city !== "") {
      obj.city = message.city;
    }
    if (message.region !== undefined) {
      obj.region = message.region;
    }
    if (message.postalCode !== undefined) {
      obj.postalCode = message.postalCode;
    }
    if (message.country !== "") {
      obj.country = message.country;
    }
    if (message.yearFounded !== 0) {
      obj.yearFounded = Math.round(message.yearFounded);
    }
    if (message.licensed !== false) {
      obj.licensed = message.licensed;
    }
    if (message.licenseCountry !== undefined) {
      obj.licenseCountry = message.licenseCountry;
    }
    if (message.licenseNumber !== undefined) {
      obj.licenseNumber = message.licenseNumber;
    }
    if (message.phone !== undefined) {
      obj.phone = message.phone;
    }
    if (message.email !== undefined) {
      obj.email = message.email;
    }
    if (message.socialMediaLinks?.length) {
      obj.socialMediaLinks = message.socialMediaLinks;
    }
    if (message.keyClients !== undefined) {
      obj.keyClients = message.keyClients;
    }
    if (message.press !== undefined) {
      obj.press = message.press;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MetaDataDetails>, I>>(base?: I): MetaDataDetails {
    return MetaDataDetails.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MetaDataDetails>, I>>(object: I): MetaDataDetails {
    const message = createBaseMetaDataDetails();
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    message.image = object.image ?? "";
    message.externalUrl = object.externalUrl ?? "";
    message.addressLine1 = object.addressLine1 ?? "";
    message.addressLine2 = object.addressLine2 ?? undefined;
    message.city = object.city ?? "";
    message.region = object.region ?? undefined;
    message.postalCode = object.postalCode ?? undefined;
    message.country = object.country ?? "";
    message.yearFounded = object.yearFounded ?? 0;
    message.licensed = object.licensed ?? false;
    message.licenseCountry = object.licenseCountry ?? undefined;
    message.licenseNumber = object.licenseNumber ?? undefined;
    message.phone = object.phone ?? undefined;
    message.email = object.email ?? undefined;
    message.socialMediaLinks = object.socialMediaLinks?.map((e) => e) || [];
    message.keyClients = object.keyClients ?? undefined;
    message.press = object.press ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
