// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: asset.proto

package asset

import (
	denom "github.com/sologenic/com-fs-asset-model/domain/denom"
	audit "github.com/sologenic/com-fs-utils-lib/models/audit"
	metadata "github.com/sologenic/com-fs-utils-lib/models/metadata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetStatus int32

const (
	AssetStatus_ASSET_STATUS_DO_NOT_USE        AssetStatus = 0
	AssetStatus_DO_NOT_LIST                    AssetStatus = 1 // BROKER_ASSET_ADMINISTRATOR only
	AssetStatus_REQUEST_LISTING                AssetStatus = 2 // BROKER_ASSET_ADMINISTRATOR only
	AssetStatus_LISTED                         AssetStatus = 3 // ORGANIZATION_ASSET_ADMINISTRATOR only
	AssetStatus_ORGANIZATION_ADMIN_DO_NOT_LIST AssetStatus = 4 // ORGANIZATION_ASSET_ADMINISTRATOR only
	AssetStatus_OUTDATED_ASSET_VERSION         AssetStatus = 5
)

// Enum value maps for AssetStatus.
var (
	AssetStatus_name = map[int32]string{
		0: "ASSET_STATUS_DO_NOT_USE",
		1: "DO_NOT_LIST",
		2: "REQUEST_LISTING",
		3: "LISTED",
		4: "ORGANIZATION_ADMIN_DO_NOT_LIST",
		5: "OUTDATED_ASSET_VERSION",
	}
	AssetStatus_value = map[string]int32{
		"ASSET_STATUS_DO_NOT_USE":        0,
		"DO_NOT_LIST":                    1,
		"REQUEST_LISTING":                2,
		"LISTED":                         3,
		"ORGANIZATION_ADMIN_DO_NOT_LIST": 4,
		"OUTDATED_ASSET_VERSION":         5,
	}
)

func (x AssetStatus) Enum() *AssetStatus {
	p := new(AssetStatus)
	*p = x
	return p
}

func (x AssetStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_asset_proto_enumTypes[0].Descriptor()
}

func (AssetStatus) Type() protoreflect.EnumType {
	return &file_asset_proto_enumTypes[0]
}

func (x AssetStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetStatus.Descriptor instead.
func (AssetStatus) EnumDescriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{0}
}

type Reason int32

const (
	Reason_REASON_DO_NOT_USE Reason = 0
	Reason_DUPLICATE         Reason = 1
	Reason_UNWANTED_ASSET    Reason = 2
	Reason_UNSTABLE_ASSET    Reason = 3
)

// Enum value maps for Reason.
var (
	Reason_name = map[int32]string{
		0: "REASON_DO_NOT_USE",
		1: "DUPLICATE",
		2: "UNWANTED_ASSET",
		3: "UNSTABLE_ASSET",
	}
	Reason_value = map[string]int32{
		"REASON_DO_NOT_USE": 0,
		"DUPLICATE":         1,
		"UNWANTED_ASSET":    2,
		"UNSTABLE_ASSET":    3,
	}
)

func (x Reason) Enum() *Reason {
	p := new(Reason)
	*p = x
	return p
}

func (x Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_asset_proto_enumTypes[1].Descriptor()
}

func (Reason) Type() protoreflect.EnumType {
	return &file_asset_proto_enumTypes[1]
}

func (x Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Reason.Descriptor instead.
func (Reason) EnumDescriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{1}
}

// TODO: to have shared between order
type AssetType int32

const (
	AssetType_ASSET_TYPE_DO_NOT_USE AssetType = 0
	AssetType_STOCKS                AssetType = 1
	AssetType_BONDS                 AssetType = 2
	AssetType_WRAPPED_STABLECOIN    AssetType = 3 // Represents a stablecoin that is wrapped for internal use within the system, such as WUSDC.
	AssetType_CRYPTO                AssetType = 4
	AssetType_FOREX                 AssetType = 5
	AssetType_FUTURES               AssetType = 6
	AssetType_OPTIONS               AssetType = 7
)

// Enum value maps for AssetType.
var (
	AssetType_name = map[int32]string{
		0: "ASSET_TYPE_DO_NOT_USE",
		1: "STOCKS",
		2: "BONDS",
		3: "WRAPPED_STABLECOIN",
		4: "CRYPTO",
		5: "FOREX",
		6: "FUTURES",
		7: "OPTIONS",
	}
	AssetType_value = map[string]int32{
		"ASSET_TYPE_DO_NOT_USE": 0,
		"STOCKS":                1,
		"BONDS":                 2,
		"WRAPPED_STABLECOIN":    3,
		"CRYPTO":                4,
		"FOREX":                 5,
		"FUTURES":               6,
		"OPTIONS":               7,
	}
)

func (x AssetType) Enum() *AssetType {
	p := new(AssetType)
	*p = x
	return p
}

func (x AssetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetType) Descriptor() protoreflect.EnumDescriptor {
	return file_asset_proto_enumTypes[2].Descriptor()
}

func (AssetType) Type() protoreflect.EnumType {
	return &file_asset_proto_enumTypes[2]
}

func (x AssetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetType.Descriptor instead.
func (AssetType) EnumDescriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{2}
}

type UserAssetStatus int32

const (
	UserAssetStatus_USER_ASSET_STATUS_DO_NOT_USE UserAssetStatus = 0
	UserAssetStatus_NOT_WHITELISTED              UserAssetStatus = 1
	UserAssetStatus_WHITELISTING_REQUESTED       UserAssetStatus = 2
	UserAssetStatus_WHITELISTED                  UserAssetStatus = 3
	UserAssetStatus_OUTDATED_VERSION             UserAssetStatus = 4
	UserAssetStatus_BLACKLISTED                  UserAssetStatus = 5
	UserAssetStatus_SELL_ONLY                    UserAssetStatus = 6
)

// Enum value maps for UserAssetStatus.
var (
	UserAssetStatus_name = map[int32]string{
		0: "USER_ASSET_STATUS_DO_NOT_USE",
		1: "NOT_WHITELISTED",
		2: "WHITELISTING_REQUESTED",
		3: "WHITELISTED",
		4: "OUTDATED_VERSION",
		5: "BLACKLISTED",
		6: "SELL_ONLY",
	}
	UserAssetStatus_value = map[string]int32{
		"USER_ASSET_STATUS_DO_NOT_USE": 0,
		"NOT_WHITELISTED":              1,
		"WHITELISTING_REQUESTED":       2,
		"WHITELISTED":                  3,
		"OUTDATED_VERSION":             4,
		"BLACKLISTED":                  5,
		"SELL_ONLY":                    6,
	}
)

func (x UserAssetStatus) Enum() *UserAssetStatus {
	p := new(UserAssetStatus)
	*p = x
	return p
}

func (x UserAssetStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserAssetStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_asset_proto_enumTypes[3].Descriptor()
}

func (UserAssetStatus) Type() protoreflect.EnumType {
	return &file_asset_proto_enumTypes[3]
}

func (x UserAssetStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserAssetStatus.Descriptor instead.
func (UserAssetStatus) EnumDescriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{3}
}

type Exchange int32

const (
	Exchange_EXCHANGE_DO_NOT_USE Exchange = 0
	Exchange_NASDAQ              Exchange = 1
	Exchange_NYSE                Exchange = 2
	Exchange_ONCHAIN             Exchange = 3 // On‑chain token/cryptocurrency markets, e.g. wrapped USDC
)

// Enum value maps for Exchange.
var (
	Exchange_name = map[int32]string{
		0: "EXCHANGE_DO_NOT_USE",
		1: "NASDAQ",
		2: "NYSE",
		3: "ONCHAIN",
	}
	Exchange_value = map[string]int32{
		"EXCHANGE_DO_NOT_USE": 0,
		"NASDAQ":              1,
		"NYSE":                2,
		"ONCHAIN":             3,
	}
)

func (x Exchange) Enum() *Exchange {
	p := new(Exchange)
	*p = x
	return p
}

func (x Exchange) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Exchange) Descriptor() protoreflect.EnumDescriptor {
	return file_asset_proto_enumTypes[4].Descriptor()
}

func (Exchange) Type() protoreflect.EnumType {
	return &file_asset_proto_enumTypes[4]
}

func (x Exchange) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Exchange.Descriptor instead.
func (Exchange) EnumDescriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{4}
}

// Global Industry Classification Standard (GICS®) 11 sectors
// Source: https://www.msci.com/our-solutions/indexes/gics
type Industry int32

const (
	Industry_INDUSTRY_DO_NOT_USE    Industry = 0
	Industry_ENERGY                 Industry = 1
	Industry_MATERIALS              Industry = 2
	Industry_INDUSTRIALS            Industry = 3
	Industry_CONSUMER_DISCRETIONARY Industry = 4
	Industry_CONSUMER_STAPLES       Industry = 5
	Industry_HEALTH_CARE            Industry = 6
	Industry_FINANCIALS             Industry = 7
	Industry_INFORMATION_TECHNOLOGY Industry = 8
	Industry_COMMUNICATION_SERVICES Industry = 9
	Industry_UTILITIES              Industry = 10
	Industry_REAL_ESTATE            Industry = 11
)

// Enum value maps for Industry.
var (
	Industry_name = map[int32]string{
		0:  "INDUSTRY_DO_NOT_USE",
		1:  "ENERGY",
		2:  "MATERIALS",
		3:  "INDUSTRIALS",
		4:  "CONSUMER_DISCRETIONARY",
		5:  "CONSUMER_STAPLES",
		6:  "HEALTH_CARE",
		7:  "FINANCIALS",
		8:  "INFORMATION_TECHNOLOGY",
		9:  "COMMUNICATION_SERVICES",
		10: "UTILITIES",
		11: "REAL_ESTATE",
	}
	Industry_value = map[string]int32{
		"INDUSTRY_DO_NOT_USE":    0,
		"ENERGY":                 1,
		"MATERIALS":              2,
		"INDUSTRIALS":            3,
		"CONSUMER_DISCRETIONARY": 4,
		"CONSUMER_STAPLES":       5,
		"HEALTH_CARE":            6,
		"FINANCIALS":             7,
		"INFORMATION_TECHNOLOGY": 8,
		"COMMUNICATION_SERVICES": 9,
		"UTILITIES":              10,
		"REAL_ESTATE":            11,
	}
)

func (x Industry) Enum() *Industry {
	p := new(Industry)
	*p = x
	return p
}

func (x Industry) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Industry) Descriptor() protoreflect.EnumDescriptor {
	return file_asset_proto_enumTypes[5].Descriptor()
}

func (Industry) Type() protoreflect.EnumType {
	return &file_asset_proto_enumTypes[5]
}

func (x Industry) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Industry.Descriptor instead.
func (Industry) EnumDescriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{5}
}

type AssetDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key combination: Currency_OrganizationID_SmartContractIssuerAddr e.g "appl_1_72c4c072-2fe4-4f72-ae9d-d9d52a05fd71_testcore1et29c..."
	ID              string      `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`                         // Key string to prevent composing the key all the time and reduce errors
	OrganizationID  string      `protobuf:"bytes,2,opt,name=OrganizationID,proto3" json:"OrganizationID,omitempty"` // External entity (broker) that owns this asset
	Status          AssetStatus `protobuf:"varint,3,opt,name=Status,proto3,enum=asset.AssetStatus" json:"Status,omitempty"`
	Reason          *Reason     `protobuf:"varint,4,opt,name=Reason,proto3,enum=asset.Reason,oneof" json:"Reason,omitempty"`
	JurisdictionIDs []string    `protobuf:"bytes,5,rep,name=JurisdictionIDs,proto3" json:"JurisdictionIDs,omitempty"` // list of jurisdictionIDs where this asset is allowed to be traded
	Type            AssetType   `protobuf:"varint,6,opt,name=Type,proto3,enum=asset.AssetType" json:"Type,omitempty"`
	// Asset specific properties
	Name                 string   `protobuf:"bytes,7,opt,name=Name,proto3" json:"Name,omitempty"`
	ExchangeTickerSymbol string   `protobuf:"bytes,8,opt,name=ExchangeTickerSymbol,proto3" json:"ExchangeTickerSymbol,omitempty"`
	Exchange             Exchange `protobuf:"varint,9,opt,name=Exchange,proto3,enum=asset.Exchange" json:"Exchange,omitempty"`
	InternalDescription  string   `protobuf:"bytes,10,opt,name=InternalDescription,proto3" json:"InternalDescription,omitempty"` // Description for internal use, not for on-chain
	MinTransactionAmount float64  `protobuf:"fixed64,11,opt,name=MinTransactionAmount,proto3" json:"MinTransactionAmount,omitempty"`
	// TradingMarginPercentage is required additional margin as a percentage of the order value that buyers must provide.
	// Value should be between 0.0 and 1.0 (0% to 100%)
	// Example: If TradingMarginPercentage = 0.1 (10%) and order value is $100:
	//   - Buyer must provide $110 total ($100 asset cost + $10 margin)
	//   - $5 (5%, cost) is kept for transaction costs
	//   - $5 (5%, refundable) is returned to the buyer after execution
	TradingMarginPercentage float64   `protobuf:"fixed64,12,opt,name=TradingMarginPercentage,proto3" json:"TradingMarginPercentage,omitempty"`
	LogoFile                *LogoFile `protobuf:"bytes,13,opt,name=LogoFile,proto3" json:"LogoFile,omitempty"`
	Industry                Industry  `protobuf:"varint,14,opt,name=Industry,proto3,enum=asset.Industry" json:"Industry,omitempty"` // Global Industry Classification Standard (GICS®) sector
	// Margin percentage specific to the asset. This is the asset's individual margin percentage used to calculate buying power.
	// Buying Power = AvailableFunds(On-chain) + (Σ Assets(non-stablecoin)  × AssetMarginPercentage)
	// Asset Margin Percentage: represents the collateral value of the asset (e.g., 50% → 10,000BTC → 10,000BTC → 5,000 buying power contribution)
	AssetMarginPercentage float64 `protobuf:"fixed64,15,opt,name=AssetMarginPercentage,proto3" json:"AssetMarginPercentage,omitempty"`
	// On-chain properties
	Denom                   *denom.Denom `protobuf:"bytes,17,opt,name=Denom,proto3" json:"Denom,omitempty"`                                      // {subunit}-{issuer} where Subunit is su{Currency}. e.g., suappl_1-testcore1et29c...
	IsIssuedInSmartContract bool         `protobuf:"varint,18,opt,name=IsIssuedInSmartContract,proto3" json:"IsIssuedInSmartContract,omitempty"` // Flag to indicate if the asset is issued in the smart contract
	SmartContractIssuerAddr string       `protobuf:"bytes,19,opt,name=SmartContractIssuerAddr,proto3" json:"SmartContractIssuerAddr,omitempty"`  // Issuer address of the smart contract (distinct from Denom.Issuer which is the smart contract address that minted the token)
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AssetDetails) Reset() {
	*x = AssetDetails{}
	mi := &file_asset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetDetails) ProtoMessage() {}

func (x *AssetDetails) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetDetails.ProtoReflect.Descriptor instead.
func (*AssetDetails) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{0}
}

func (x *AssetDetails) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *AssetDetails) GetOrganizationID() string {
	if x != nil {
		return x.OrganizationID
	}
	return ""
}

func (x *AssetDetails) GetStatus() AssetStatus {
	if x != nil {
		return x.Status
	}
	return AssetStatus_ASSET_STATUS_DO_NOT_USE
}

func (x *AssetDetails) GetReason() Reason {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return Reason_REASON_DO_NOT_USE
}

func (x *AssetDetails) GetJurisdictionIDs() []string {
	if x != nil {
		return x.JurisdictionIDs
	}
	return nil
}

func (x *AssetDetails) GetType() AssetType {
	if x != nil {
		return x.Type
	}
	return AssetType_ASSET_TYPE_DO_NOT_USE
}

func (x *AssetDetails) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AssetDetails) GetExchangeTickerSymbol() string {
	if x != nil {
		return x.ExchangeTickerSymbol
	}
	return ""
}

func (x *AssetDetails) GetExchange() Exchange {
	if x != nil {
		return x.Exchange
	}
	return Exchange_EXCHANGE_DO_NOT_USE
}

func (x *AssetDetails) GetInternalDescription() string {
	if x != nil {
		return x.InternalDescription
	}
	return ""
}

func (x *AssetDetails) GetMinTransactionAmount() float64 {
	if x != nil {
		return x.MinTransactionAmount
	}
	return 0
}

func (x *AssetDetails) GetTradingMarginPercentage() float64 {
	if x != nil {
		return x.TradingMarginPercentage
	}
	return 0
}

func (x *AssetDetails) GetLogoFile() *LogoFile {
	if x != nil {
		return x.LogoFile
	}
	return nil
}

func (x *AssetDetails) GetIndustry() Industry {
	if x != nil {
		return x.Industry
	}
	return Industry_INDUSTRY_DO_NOT_USE
}

func (x *AssetDetails) GetAssetMarginPercentage() float64 {
	if x != nil {
		return x.AssetMarginPercentage
	}
	return 0
}

func (x *AssetDetails) GetDenom() *denom.Denom {
	if x != nil {
		return x.Denom
	}
	return nil
}

func (x *AssetDetails) GetIsIssuedInSmartContract() bool {
	if x != nil {
		return x.IsIssuedInSmartContract
	}
	return false
}

func (x *AssetDetails) GetSmartContractIssuerAddr() string {
	if x != nil {
		return x.SmartContractIssuerAddr
	}
	return ""
}

type Asset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetDetails  *AssetDetails          `protobuf:"bytes,1,opt,name=AssetDetails,proto3" json:"AssetDetails,omitempty"`
	MetaData      *metadata.MetaData     `protobuf:"bytes,2,opt,name=MetaData,proto3" json:"MetaData,omitempty"`
	Audit         *audit.Audit           `protobuf:"bytes,3,opt,name=Audit,proto3" json:"Audit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_asset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{1}
}

func (x *Asset) GetAssetDetails() *AssetDetails {
	if x != nil {
		return x.AssetDetails
	}
	return nil
}

func (x *Asset) GetMetaData() *metadata.MetaData {
	if x != nil {
		return x.MetaData
	}
	return nil
}

func (x *Asset) GetAudit() *audit.Audit {
	if x != nil {
		return x.Audit
	}
	return nil
}

type Assets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assets        []*Asset               `protobuf:"bytes,1,rep,name=Assets,proto3" json:"Assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assets) Reset() {
	*x = Assets{}
	mi := &file_asset_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assets) ProtoMessage() {}

func (x *Assets) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assets.ProtoReflect.Descriptor instead.
func (*Assets) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{2}
}

func (x *Assets) GetAssets() []*Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

type LogoFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reference     string                 `protobuf:"bytes,1,opt,name=Reference,proto3" json:"Reference,omitempty"` // The reference to the file
	Extension     string                 `protobuf:"bytes,2,opt,name=Extension,proto3" json:"Extension,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=Name,proto3,oneof" json:"Name,omitempty"` // User defined name of the file, used as a "description" and not to reference the file
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoFile) Reset() {
	*x = LogoFile{}
	mi := &file_asset_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoFile) ProtoMessage() {}

func (x *LogoFile) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoFile.ProtoReflect.Descriptor instead.
func (*LogoFile) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{3}
}

func (x *LogoFile) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *LogoFile) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

func (x *LogoFile) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type UserAssetList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key combination: Currency-OrganizationID-AccountID-Wallet (AssetKey-AccountID-Wallet)
	AccountID      string             `protobuf:"bytes,1,opt,name=AccountID,proto3" json:"AccountID,omitempty"`
	Wallet         string             `protobuf:"bytes,2,opt,name=Wallet,proto3" json:"Wallet,omitempty"`
	AssetKey       string             `protobuf:"bytes,3,opt,name=AssetKey,proto3" json:"AssetKey,omitempty"` // Currency-OrganizationID
	Status         UserAssetStatus    `protobuf:"varint,4,opt,name=Status,proto3,enum=asset.UserAssetStatus" json:"Status,omitempty"`
	MetaData       *metadata.MetaData `protobuf:"bytes,5,opt,name=MetaData,proto3" json:"MetaData,omitempty"`
	Visible        bool               `protobuf:"varint,6,opt,name=Visible,proto3" json:"Visible,omitempty"`
	OrganizationID string             `protobuf:"bytes,7,opt,name=OrganizationID,proto3" json:"OrganizationID,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserAssetList) Reset() {
	*x = UserAssetList{}
	mi := &file_asset_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAssetList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAssetList) ProtoMessage() {}

func (x *UserAssetList) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAssetList.ProtoReflect.Descriptor instead.
func (*UserAssetList) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{4}
}

func (x *UserAssetList) GetAccountID() string {
	if x != nil {
		return x.AccountID
	}
	return ""
}

func (x *UserAssetList) GetWallet() string {
	if x != nil {
		return x.Wallet
	}
	return ""
}

func (x *UserAssetList) GetAssetKey() string {
	if x != nil {
		return x.AssetKey
	}
	return ""
}

func (x *UserAssetList) GetStatus() UserAssetStatus {
	if x != nil {
		return x.Status
	}
	return UserAssetStatus_USER_ASSET_STATUS_DO_NOT_USE
}

func (x *UserAssetList) GetMetaData() *metadata.MetaData {
	if x != nil {
		return x.MetaData
	}
	return nil
}

func (x *UserAssetList) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

func (x *UserAssetList) GetOrganizationID() string {
	if x != nil {
		return x.OrganizationID
	}
	return ""
}

type UserAssetLists struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserAssetLists []*UserAssetList       `protobuf:"bytes,1,rep,name=UserAssetLists,proto3" json:"UserAssetLists,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserAssetLists) Reset() {
	*x = UserAssetLists{}
	mi := &file_asset_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAssetLists) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAssetLists) ProtoMessage() {}

func (x *UserAssetLists) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAssetLists.ProtoReflect.Descriptor instead.
func (*UserAssetLists) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{5}
}

func (x *UserAssetLists) GetUserAssetLists() []*UserAssetList {
	if x != nil {
		return x.UserAssetLists
	}
	return nil
}

var File_asset_proto protoreflect.FileDescriptor

const file_asset_proto_rawDesc = "" +
	"\n" +
	"\vasset.proto\x12\x05asset\x1a5sologenic/com-fs-asset-model/domain/denom/denom.proto\x1a9sologenic/com-fs-utils-lib/models/metadata/metadata.proto\x1a3sologenic/com-fs-utils-lib/models/audit/audit.proto\"\xb6\x06\n" +
	"\fAssetDetails\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12&\n" +
	"\x0eOrganizationID\x18\x02 \x01(\tR\x0eOrganizationID\x12*\n" +
	"\x06Status\x18\x03 \x01(\x0e2\x12.asset.AssetStatusR\x06Status\x12*\n" +
	"\x06Reason\x18\x04 \x01(\x0e2\r.asset.ReasonH\x00R\x06Reason\x88\x01\x01\x12(\n" +
	"\x0fJurisdictionIDs\x18\x05 \x03(\tR\x0fJurisdictionIDs\x12$\n" +
	"\x04Type\x18\x06 \x01(\x0e2\x10.asset.AssetTypeR\x04Type\x12\x12\n" +
	"\x04Name\x18\a \x01(\tR\x04Name\x122\n" +
	"\x14ExchangeTickerSymbol\x18\b \x01(\tR\x14ExchangeTickerSymbol\x12+\n" +
	"\bExchange\x18\t \x01(\x0e2\x0f.asset.ExchangeR\bExchange\x120\n" +
	"\x13InternalDescription\x18\n" +
	" \x01(\tR\x13InternalDescription\x122\n" +
	"\x14MinTransactionAmount\x18\v \x01(\x01R\x14MinTransactionAmount\x128\n" +
	"\x17TradingMarginPercentage\x18\f \x01(\x01R\x17TradingMarginPercentage\x12+\n" +
	"\bLogoFile\x18\r \x01(\v2\x0f.asset.LogoFileR\bLogoFile\x12+\n" +
	"\bIndustry\x18\x0e \x01(\x0e2\x0f.asset.IndustryR\bIndustry\x124\n" +
	"\x15AssetMarginPercentage\x18\x0f \x01(\x01R\x15AssetMarginPercentage\x12\"\n" +
	"\x05Denom\x18\x11 \x01(\v2\f.denom.DenomR\x05Denom\x128\n" +
	"\x17IsIssuedInSmartContract\x18\x12 \x01(\bR\x17IsIssuedInSmartContract\x128\n" +
	"\x17SmartContractIssuerAddr\x18\x13 \x01(\tR\x17SmartContractIssuerAddrB\t\n" +
	"\a_Reason\"\x94\x01\n" +
	"\x05Asset\x127\n" +
	"\fAssetDetails\x18\x01 \x01(\v2\x13.asset.AssetDetailsR\fAssetDetails\x12.\n" +
	"\bMetaData\x18\x02 \x01(\v2\x12.metadata.MetaDataR\bMetaData\x12\"\n" +
	"\x05Audit\x18\x03 \x01(\v2\f.audit.AuditR\x05Audit\".\n" +
	"\x06Assets\x12$\n" +
	"\x06Assets\x18\x01 \x03(\v2\f.asset.AssetR\x06Assets\"h\n" +
	"\bLogoFile\x12\x1c\n" +
	"\tReference\x18\x01 \x01(\tR\tReference\x12\x1c\n" +
	"\tExtension\x18\x02 \x01(\tR\tExtension\x12\x17\n" +
	"\x04Name\x18\x03 \x01(\tH\x00R\x04Name\x88\x01\x01B\a\n" +
	"\x05_Name\"\x83\x02\n" +
	"\rUserAssetList\x12\x1c\n" +
	"\tAccountID\x18\x01 \x01(\tR\tAccountID\x12\x16\n" +
	"\x06Wallet\x18\x02 \x01(\tR\x06Wallet\x12\x1a\n" +
	"\bAssetKey\x18\x03 \x01(\tR\bAssetKey\x12.\n" +
	"\x06Status\x18\x04 \x01(\x0e2\x16.asset.UserAssetStatusR\x06Status\x12.\n" +
	"\bMetaData\x18\x05 \x01(\v2\x12.metadata.MetaDataR\bMetaData\x12\x18\n" +
	"\aVisible\x18\x06 \x01(\bR\aVisible\x12&\n" +
	"\x0eOrganizationID\x18\a \x01(\tR\x0eOrganizationID\"N\n" +
	"\x0eUserAssetLists\x12<\n" +
	"\x0eUserAssetLists\x18\x01 \x03(\v2\x14.asset.UserAssetListR\x0eUserAssetLists*\x9c\x01\n" +
	"\vAssetStatus\x12\x1b\n" +
	"\x17ASSET_STATUS_DO_NOT_USE\x10\x00\x12\x0f\n" +
	"\vDO_NOT_LIST\x10\x01\x12\x13\n" +
	"\x0fREQUEST_LISTING\x10\x02\x12\n" +
	"\n" +
	"\x06LISTED\x10\x03\x12\"\n" +
	"\x1eORGANIZATION_ADMIN_DO_NOT_LIST\x10\x04\x12\x1a\n" +
	"\x16OUTDATED_ASSET_VERSION\x10\x05*V\n" +
	"\x06Reason\x12\x15\n" +
	"\x11REASON_DO_NOT_USE\x10\x00\x12\r\n" +
	"\tDUPLICATE\x10\x01\x12\x12\n" +
	"\x0eUNWANTED_ASSET\x10\x02\x12\x12\n" +
	"\x0eUNSTABLE_ASSET\x10\x03*\x86\x01\n" +
	"\tAssetType\x12\x19\n" +
	"\x15ASSET_TYPE_DO_NOT_USE\x10\x00\x12\n" +
	"\n" +
	"\x06STOCKS\x10\x01\x12\t\n" +
	"\x05BONDS\x10\x02\x12\x16\n" +
	"\x12WRAPPED_STABLECOIN\x10\x03\x12\n" +
	"\n" +
	"\x06CRYPTO\x10\x04\x12\t\n" +
	"\x05FOREX\x10\x05\x12\v\n" +
	"\aFUTURES\x10\x06\x12\v\n" +
	"\aOPTIONS\x10\a*\xab\x01\n" +
	"\x0fUserAssetStatus\x12 \n" +
	"\x1cUSER_ASSET_STATUS_DO_NOT_USE\x10\x00\x12\x13\n" +
	"\x0fNOT_WHITELISTED\x10\x01\x12\x1a\n" +
	"\x16WHITELISTING_REQUESTED\x10\x02\x12\x0f\n" +
	"\vWHITELISTED\x10\x03\x12\x14\n" +
	"\x10OUTDATED_VERSION\x10\x04\x12\x0f\n" +
	"\vBLACKLISTED\x10\x05\x12\r\n" +
	"\tSELL_ONLY\x10\x06*F\n" +
	"\bExchange\x12\x17\n" +
	"\x13EXCHANGE_DO_NOT_USE\x10\x00\x12\n" +
	"\n" +
	"\x06NASDAQ\x10\x01\x12\b\n" +
	"\x04NYSE\x10\x02\x12\v\n" +
	"\aONCHAIN\x10\x03*\xfa\x01\n" +
	"\bIndustry\x12\x17\n" +
	"\x13INDUSTRY_DO_NOT_USE\x10\x00\x12\n" +
	"\n" +
	"\x06ENERGY\x10\x01\x12\r\n" +
	"\tMATERIALS\x10\x02\x12\x0f\n" +
	"\vINDUSTRIALS\x10\x03\x12\x1a\n" +
	"\x16CONSUMER_DISCRETIONARY\x10\x04\x12\x14\n" +
	"\x10CONSUMER_STAPLES\x10\x05\x12\x0f\n" +
	"\vHEALTH_CARE\x10\x06\x12\x0e\n" +
	"\n" +
	"FINANCIALS\x10\a\x12\x1a\n" +
	"\x16INFORMATION_TECHNOLOGY\x10\b\x12\x1a\n" +
	"\x16COMMUNICATION_SERVICES\x10\t\x12\r\n" +
	"\tUTILITIES\x10\n" +
	"\x12\x0f\n" +
	"\vREAL_ESTATE\x10\vB/Z-github.com/sologenic/com-fs-asset-model;assetb\x06proto3"

var (
	file_asset_proto_rawDescOnce sync.Once
	file_asset_proto_rawDescData []byte
)

func file_asset_proto_rawDescGZIP() []byte {
	file_asset_proto_rawDescOnce.Do(func() {
		file_asset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_asset_proto_rawDesc), len(file_asset_proto_rawDesc)))
	})
	return file_asset_proto_rawDescData
}

var file_asset_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_asset_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_asset_proto_goTypes = []any{
	(AssetStatus)(0),          // 0: asset.AssetStatus
	(Reason)(0),               // 1: asset.Reason
	(AssetType)(0),            // 2: asset.AssetType
	(UserAssetStatus)(0),      // 3: asset.UserAssetStatus
	(Exchange)(0),             // 4: asset.Exchange
	(Industry)(0),             // 5: asset.Industry
	(*AssetDetails)(nil),      // 6: asset.AssetDetails
	(*Asset)(nil),             // 7: asset.Asset
	(*Assets)(nil),            // 8: asset.Assets
	(*LogoFile)(nil),          // 9: asset.LogoFile
	(*UserAssetList)(nil),     // 10: asset.UserAssetList
	(*UserAssetLists)(nil),    // 11: asset.UserAssetLists
	(*denom.Denom)(nil),       // 12: denom.Denom
	(*metadata.MetaData)(nil), // 13: metadata.MetaData
	(*audit.Audit)(nil),       // 14: audit.Audit
}
var file_asset_proto_depIdxs = []int32{
	0,  // 0: asset.AssetDetails.Status:type_name -> asset.AssetStatus
	1,  // 1: asset.AssetDetails.Reason:type_name -> asset.Reason
	2,  // 2: asset.AssetDetails.Type:type_name -> asset.AssetType
	4,  // 3: asset.AssetDetails.Exchange:type_name -> asset.Exchange
	9,  // 4: asset.AssetDetails.LogoFile:type_name -> asset.LogoFile
	5,  // 5: asset.AssetDetails.Industry:type_name -> asset.Industry
	12, // 6: asset.AssetDetails.Denom:type_name -> denom.Denom
	6,  // 7: asset.Asset.AssetDetails:type_name -> asset.AssetDetails
	13, // 8: asset.Asset.MetaData:type_name -> metadata.MetaData
	14, // 9: asset.Asset.Audit:type_name -> audit.Audit
	7,  // 10: asset.Assets.Assets:type_name -> asset.Asset
	3,  // 11: asset.UserAssetList.Status:type_name -> asset.UserAssetStatus
	13, // 12: asset.UserAssetList.MetaData:type_name -> metadata.MetaData
	10, // 13: asset.UserAssetLists.UserAssetLists:type_name -> asset.UserAssetList
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_asset_proto_init() }
func file_asset_proto_init() {
	if File_asset_proto != nil {
		return
	}
	file_asset_proto_msgTypes[0].OneofWrappers = []any{}
	file_asset_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_asset_proto_rawDesc), len(file_asset_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_asset_proto_goTypes,
		DependencyIndexes: file_asset_proto_depIdxs,
		EnumInfos:         file_asset_proto_enumTypes,
		MessageInfos:      file_asset_proto_msgTypes,
	}.Build()
	File_asset_proto = out.File
	file_asset_proto_goTypes = nil
	file_asset_proto_depIdxs = nil
}
