// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: asset-grpc.proto

package asset

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetKey) Reset() {
	*x = AssetKey{}
	mi := &file_asset_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetKey) ProtoMessage() {}

func (x *AssetKey) ProtoReflect() protoreflect.Message {
	mi := &file_asset_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetKey.ProtoReflect.Descriptor instead.
func (*AssetKey) Descriptor() ([]byte, []int) {
	return file_asset_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *AssetKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type AssetQuery struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Offset         *int32                 `protobuf:"varint,1,opt,name=Offset,proto3,oneof" json:"Offset,omitempty"`
	OrganizationID *string                `protobuf:"bytes,2,opt,name=OrganizationID,proto3,oneof" json:"OrganizationID,omitempty"`
	ID             *string                `protobuf:"bytes,3,opt,name=ID,proto3,oneof" json:"ID,omitempty"`
	Type           *AssetType             `protobuf:"varint,4,opt,name=Type,proto3,enum=asset.AssetType,oneof" json:"Type,omitempty"`
	Limit          *int32                 `protobuf:"varint,5,opt,name=Limit,proto3,oneof" json:"Limit,omitempty"`
	IsIssued       *bool                  `protobuf:"varint,6,opt,name=IsIssued,proto3,oneof" json:"IsIssued,omitempty"` // IssuedAt != nil
	IsEnabled      *bool                  `protobuf:"varint,7,opt,name=IsEnabled,proto3,oneof" json:"IsEnabled,omitempty"`
	IsVisible      *bool                  `protobuf:"varint,8,opt,name=IsVisible,proto3,oneof" json:"IsVisible,omitempty"`
	IsPromoted     *bool                  `protobuf:"varint,9,opt,name=IsPromoted,proto3,oneof" json:"IsPromoted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AssetQuery) Reset() {
	*x = AssetQuery{}
	mi := &file_asset_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetQuery) ProtoMessage() {}

func (x *AssetQuery) ProtoReflect() protoreflect.Message {
	mi := &file_asset_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetQuery.ProtoReflect.Descriptor instead.
func (*AssetQuery) Descriptor() ([]byte, []int) {
	return file_asset_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *AssetQuery) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *AssetQuery) GetOrganizationID() string {
	if x != nil && x.OrganizationID != nil {
		return *x.OrganizationID
	}
	return ""
}

func (x *AssetQuery) GetID() string {
	if x != nil && x.ID != nil {
		return *x.ID
	}
	return ""
}

func (x *AssetQuery) GetType() AssetType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return AssetType_ASSET_TYPE_NONE
}

func (x *AssetQuery) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *AssetQuery) GetIsIssued() bool {
	if x != nil && x.IsIssued != nil {
		return *x.IsIssued
	}
	return false
}

func (x *AssetQuery) GetIsEnabled() bool {
	if x != nil && x.IsEnabled != nil {
		return *x.IsEnabled
	}
	return false
}

func (x *AssetQuery) GetIsVisible() bool {
	if x != nil && x.IsVisible != nil {
		return *x.IsVisible
	}
	return false
}

func (x *AssetQuery) GetIsPromoted() bool {
	if x != nil && x.IsPromoted != nil {
		return *x.IsPromoted
	}
	return false
}

type CountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountResponse) Reset() {
	*x = CountResponse{}
	mi := &file_asset_grpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountResponse) ProtoMessage() {}

func (x *CountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asset_grpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountResponse.ProtoReflect.Descriptor instead.
func (*CountResponse) Descriptor() ([]byte, []int) {
	return file_asset_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *CountResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_asset_grpc_proto protoreflect.FileDescriptor

const file_asset_grpc_proto_rawDesc = "" +
	"\n" +
	"\x10asset-grpc.proto\x12\x05asset\x1a\vasset.proto\"\x1c\n" +
	"\bAssetKey\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\"\xad\x03\n" +
	"\n" +
	"AssetQuery\x12\x1b\n" +
	"\x06Offset\x18\x01 \x01(\x05H\x00R\x06Offset\x88\x01\x01\x12+\n" +
	"\x0eOrganizationID\x18\x02 \x01(\tH\x01R\x0eOrganizationID\x88\x01\x01\x12\x13\n" +
	"\x02ID\x18\x03 \x01(\tH\x02R\x02ID\x88\x01\x01\x12)\n" +
	"\x04Type\x18\x04 \x01(\x0e2\x10.asset.AssetTypeH\x03R\x04Type\x88\x01\x01\x12\x19\n" +
	"\x05Limit\x18\x05 \x01(\x05H\x04R\x05Limit\x88\x01\x01\x12\x1f\n" +
	"\bIsIssued\x18\x06 \x01(\bH\x05R\bIsIssued\x88\x01\x01\x12!\n" +
	"\tIsEnabled\x18\a \x01(\bH\x06R\tIsEnabled\x88\x01\x01\x12!\n" +
	"\tIsVisible\x18\b \x01(\bH\aR\tIsVisible\x88\x01\x01\x12#\n" +
	"\n" +
	"IsPromoted\x18\t \x01(\bH\bR\n" +
	"IsPromoted\x88\x01\x01B\t\n" +
	"\a_OffsetB\x11\n" +
	"\x0f_OrganizationIDB\x05\n" +
	"\x03_IDB\a\n" +
	"\x05_TypeB\b\n" +
	"\x06_LimitB\v\n" +
	"\t_IsIssuedB\f\n" +
	"\n" +
	"_IsEnabledB\f\n" +
	"\n" +
	"_IsVisibleB\r\n" +
	"\v_IsPromoted\"%\n" +
	"\rCountResponse\x12\x14\n" +
	"\x05Count\x18\x01 \x01(\x05R\x05Count2\xd2\x01\n" +
	"\x10AssetListService\x12,\n" +
	"\vUpsertAsset\x12\f.asset.Asset\x1a\x0f.asset.AssetKey\x12)\n" +
	"\bGetAsset\x12\x0f.asset.AssetKey\x1a\f.asset.Asset\x12-\n" +
	"\tGetAssets\x12\x11.asset.AssetQuery\x1a\r.asset.Assets\x126\n" +
	"\vCountAssets\x12\x11.asset.AssetQuery\x1a\x14.asset.CountResponseB/Z-github.com/sologenic/com-fs-asset-model;assetb\x06proto3"

var (
	file_asset_grpc_proto_rawDescOnce sync.Once
	file_asset_grpc_proto_rawDescData []byte
)

func file_asset_grpc_proto_rawDescGZIP() []byte {
	file_asset_grpc_proto_rawDescOnce.Do(func() {
		file_asset_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_asset_grpc_proto_rawDesc), len(file_asset_grpc_proto_rawDesc)))
	})
	return file_asset_grpc_proto_rawDescData
}

var file_asset_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_asset_grpc_proto_goTypes = []any{
	(*AssetKey)(nil),      // 0: asset.AssetKey
	(*AssetQuery)(nil),    // 1: asset.AssetQuery
	(*CountResponse)(nil), // 2: asset.CountResponse
	(AssetType)(0),        // 3: asset.AssetType
	(*Asset)(nil),         // 4: asset.Asset
	(*Assets)(nil),        // 5: asset.Assets
}
var file_asset_grpc_proto_depIdxs = []int32{
	3, // 0: asset.AssetQuery.Type:type_name -> asset.AssetType
	4, // 1: asset.AssetListService.UpsertAsset:input_type -> asset.Asset
	0, // 2: asset.AssetListService.GetAsset:input_type -> asset.AssetKey
	1, // 3: asset.AssetListService.GetAssets:input_type -> asset.AssetQuery
	1, // 4: asset.AssetListService.CountAssets:input_type -> asset.AssetQuery
	0, // 5: asset.AssetListService.UpsertAsset:output_type -> asset.AssetKey
	4, // 6: asset.AssetListService.GetAsset:output_type -> asset.Asset
	5, // 7: asset.AssetListService.GetAssets:output_type -> asset.Assets
	2, // 8: asset.AssetListService.CountAssets:output_type -> asset.CountResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_asset_grpc_proto_init() }
func file_asset_grpc_proto_init() {
	if File_asset_grpc_proto != nil {
		return
	}
	file_asset_proto_init()
	file_asset_grpc_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_asset_grpc_proto_rawDesc), len(file_asset_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_asset_grpc_proto_goTypes,
		DependencyIndexes: file_asset_grpc_proto_depIdxs,
		MessageInfos:      file_asset_grpc_proto_msgTypes,
	}.Build()
	File_asset_grpc_proto = out.File
	file_asset_grpc_proto_goTypes = nil
	file_asset_grpc_proto_depIdxs = nil
}
