// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: asset-grpc.proto

package asset

import (
	metadata "github.com/sologenic/com-fs-utils-lib/models/metadata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetKey) Reset() {
	*x = AssetKey{}
	mi := &file_asset_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetKey) ProtoMessage() {}

func (x *AssetKey) ProtoReflect() protoreflect.Message {
	mi := &file_asset_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetKey.ProtoReflect.Descriptor instead.
func (*AssetKey) Descriptor() ([]byte, []int) {
	return file_asset_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *AssetKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type AssetQuery struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Network metadata.Network       `protobuf:"varint,1,opt,name=Network,proto3,enum=metadata.Network" json:"Network,omitempty"`
	Offset  *int32                 `protobuf:"varint,2,opt,name=Offset,proto3,oneof" json:"Offset,omitempty"`
	// Compliance filter: list assets allowed in these jurisdictions
	JurisdictionIDs []string     `protobuf:"bytes,3,rep,name=JurisdictionIDs,proto3" json:"JurisdictionIDs,omitempty"`
	OrganizationID  *string      `protobuf:"bytes,4,opt,name=OrganizationID,proto3,oneof" json:"OrganizationID,omitempty"`
	Status          *AssetStatus `protobuf:"varint,5,opt,name=Status,proto3,enum=asset.AssetStatus,oneof" json:"Status,omitempty"`
	AssetType       *AssetType   `protobuf:"varint,6,opt,name=AssetType,proto3,enum=asset.AssetType,oneof" json:"AssetType,omitempty"`
	// On-chain issuer address (distinct from Denom.Issuer)
	SmartContractIssuerAddr *string `protobuf:"bytes,7,opt,name=SmartContractIssuerAddr,proto3,oneof" json:"SmartContractIssuerAddr,omitempty"`
	Limit                   *int32  `protobuf:"varint,8,opt,name=Limit,proto3,oneof" json:"Limit,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AssetQuery) Reset() {
	*x = AssetQuery{}
	mi := &file_asset_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetQuery) ProtoMessage() {}

func (x *AssetQuery) ProtoReflect() protoreflect.Message {
	mi := &file_asset_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetQuery.ProtoReflect.Descriptor instead.
func (*AssetQuery) Descriptor() ([]byte, []int) {
	return file_asset_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *AssetQuery) GetNetwork() metadata.Network {
	if x != nil {
		return x.Network
	}
	return metadata.Network(0)
}

func (x *AssetQuery) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *AssetQuery) GetJurisdictionIDs() []string {
	if x != nil {
		return x.JurisdictionIDs
	}
	return nil
}

func (x *AssetQuery) GetOrganizationID() string {
	if x != nil && x.OrganizationID != nil {
		return *x.OrganizationID
	}
	return ""
}

func (x *AssetQuery) GetStatus() AssetStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return AssetStatus_ASSET_STATUS_DO_NOT_USE
}

func (x *AssetQuery) GetAssetType() AssetType {
	if x != nil && x.AssetType != nil {
		return *x.AssetType
	}
	return AssetType_ASSET_TYPE_DO_NOT_USE
}

func (x *AssetQuery) GetSmartContractIssuerAddr() string {
	if x != nil && x.SmartContractIssuerAddr != nil {
		return *x.SmartContractIssuerAddr
	}
	return ""
}

func (x *AssetQuery) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type UserAssetListKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAssetListKey) Reset() {
	*x = UserAssetListKey{}
	mi := &file_asset_grpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAssetListKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAssetListKey) ProtoMessage() {}

func (x *UserAssetListKey) ProtoReflect() protoreflect.Message {
	mi := &file_asset_grpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAssetListKey.ProtoReflect.Descriptor instead.
func (*UserAssetListKey) Descriptor() ([]byte, []int) {
	return file_asset_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *UserAssetListKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type UserAssetListQuery struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Network        metadata.Network       `protobuf:"varint,1,opt,name=Network,proto3,enum=metadata.Network" json:"Network,omitempty"`
	Offset         *int32                 `protobuf:"varint,2,opt,name=Offset,proto3,oneof" json:"Offset,omitempty"`
	AccountID      *string                `protobuf:"bytes,3,opt,name=AccountID,proto3,oneof" json:"AccountID,omitempty"`
	Wallet         *string                `protobuf:"bytes,4,opt,name=Wallet,proto3,oneof" json:"Wallet,omitempty"`
	AssetKey       *string                `protobuf:"bytes,5,opt,name=AssetKey,proto3,oneof" json:"AssetKey,omitempty"`
	Status         *UserAssetStatus       `protobuf:"varint,6,opt,name=Status,proto3,enum=asset.UserAssetStatus,oneof" json:"Status,omitempty"`
	Visible        *bool                  `protobuf:"varint,7,opt,name=Visible,proto3,oneof" json:"Visible,omitempty"`
	OrganizationID *string                `protobuf:"bytes,8,opt,name=OrganizationID,proto3,oneof" json:"OrganizationID,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserAssetListQuery) Reset() {
	*x = UserAssetListQuery{}
	mi := &file_asset_grpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAssetListQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAssetListQuery) ProtoMessage() {}

func (x *UserAssetListQuery) ProtoReflect() protoreflect.Message {
	mi := &file_asset_grpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAssetListQuery.ProtoReflect.Descriptor instead.
func (*UserAssetListQuery) Descriptor() ([]byte, []int) {
	return file_asset_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *UserAssetListQuery) GetNetwork() metadata.Network {
	if x != nil {
		return x.Network
	}
	return metadata.Network(0)
}

func (x *UserAssetListQuery) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *UserAssetListQuery) GetAccountID() string {
	if x != nil && x.AccountID != nil {
		return *x.AccountID
	}
	return ""
}

func (x *UserAssetListQuery) GetWallet() string {
	if x != nil && x.Wallet != nil {
		return *x.Wallet
	}
	return ""
}

func (x *UserAssetListQuery) GetAssetKey() string {
	if x != nil && x.AssetKey != nil {
		return *x.AssetKey
	}
	return ""
}

func (x *UserAssetListQuery) GetStatus() UserAssetStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return UserAssetStatus_USER_ASSET_STATUS_DO_NOT_USE
}

func (x *UserAssetListQuery) GetVisible() bool {
	if x != nil && x.Visible != nil {
		return *x.Visible
	}
	return false
}

func (x *UserAssetListQuery) GetOrganizationID() string {
	if x != nil && x.OrganizationID != nil {
		return *x.OrganizationID
	}
	return ""
}

var File_asset_grpc_proto protoreflect.FileDescriptor

const file_asset_grpc_proto_rawDesc = "" +
	"\n" +
	"\x10asset-grpc.proto\x12\x05asset\x1a\vasset.proto\x1a9sologenic/com-fs-utils-lib/models/metadata/metadata.proto\"\x1c\n" +
	"\bAssetKey\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\"\xca\x03\n" +
	"\n" +
	"AssetQuery\x12+\n" +
	"\aNetwork\x18\x01 \x01(\x0e2\x11.metadata.NetworkR\aNetwork\x12\x1b\n" +
	"\x06Offset\x18\x02 \x01(\x05H\x00R\x06Offset\x88\x01\x01\x12(\n" +
	"\x0fJurisdictionIDs\x18\x03 \x03(\tR\x0fJurisdictionIDs\x12+\n" +
	"\x0eOrganizationID\x18\x04 \x01(\tH\x01R\x0eOrganizationID\x88\x01\x01\x12/\n" +
	"\x06Status\x18\x05 \x01(\x0e2\x12.asset.AssetStatusH\x02R\x06Status\x88\x01\x01\x123\n" +
	"\tAssetType\x18\x06 \x01(\x0e2\x10.asset.AssetTypeH\x03R\tAssetType\x88\x01\x01\x12=\n" +
	"\x17SmartContractIssuerAddr\x18\a \x01(\tH\x04R\x17SmartContractIssuerAddr\x88\x01\x01\x12\x19\n" +
	"\x05Limit\x18\b \x01(\x05H\x05R\x05Limit\x88\x01\x01B\t\n" +
	"\a_OffsetB\x11\n" +
	"\x0f_OrganizationIDB\t\n" +
	"\a_StatusB\f\n" +
	"\n" +
	"_AssetTypeB\x1a\n" +
	"\x18_SmartContractIssuerAddrB\b\n" +
	"\x06_Limit\"$\n" +
	"\x10UserAssetListKey\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\"\x9b\x03\n" +
	"\x12UserAssetListQuery\x12+\n" +
	"\aNetwork\x18\x01 \x01(\x0e2\x11.metadata.NetworkR\aNetwork\x12\x1b\n" +
	"\x06Offset\x18\x02 \x01(\x05H\x00R\x06Offset\x88\x01\x01\x12!\n" +
	"\tAccountID\x18\x03 \x01(\tH\x01R\tAccountID\x88\x01\x01\x12\x1b\n" +
	"\x06Wallet\x18\x04 \x01(\tH\x02R\x06Wallet\x88\x01\x01\x12\x1f\n" +
	"\bAssetKey\x18\x05 \x01(\tH\x03R\bAssetKey\x88\x01\x01\x123\n" +
	"\x06Status\x18\x06 \x01(\x0e2\x16.asset.UserAssetStatusH\x04R\x06Status\x88\x01\x01\x12\x1d\n" +
	"\aVisible\x18\a \x01(\bH\x05R\aVisible\x88\x01\x01\x12+\n" +
	"\x0eOrganizationID\x18\b \x01(\tH\x06R\x0eOrganizationID\x88\x01\x01B\t\n" +
	"\a_OffsetB\f\n" +
	"\n" +
	"_AccountIDB\t\n" +
	"\a_WalletB\v\n" +
	"\t_AssetKeyB\t\n" +
	"\a_StatusB\n" +
	"\n" +
	"\b_VisibleB\x11\n" +
	"\x0f_OrganizationID2\xea\x02\n" +
	"\x10AssetListService\x12,\n" +
	"\vUpsertAsset\x12\f.asset.Asset\x1a\x0f.asset.AssetKey\x12)\n" +
	"\bGetAsset\x12\x0f.asset.AssetKey\x1a\f.asset.Asset\x12-\n" +
	"\tGetAssets\x12\x11.asset.AssetQuery\x1a\r.asset.Assets\x12D\n" +
	"\x13UpsertUserAssetList\x12\x14.asset.UserAssetList\x1a\x17.asset.UserAssetListKey\x12A\n" +
	"\x10GetUserAssetList\x12\x17.asset.UserAssetListKey\x1a\x14.asset.UserAssetList\x12E\n" +
	"\x11GetUserAssetLists\x12\x19.asset.UserAssetListQuery\x1a\x15.asset.UserAssetListsB/Z-github.com/sologenic/com-fs-asset-model;assetb\x06proto3"

var (
	file_asset_grpc_proto_rawDescOnce sync.Once
	file_asset_grpc_proto_rawDescData []byte
)

func file_asset_grpc_proto_rawDescGZIP() []byte {
	file_asset_grpc_proto_rawDescOnce.Do(func() {
		file_asset_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_asset_grpc_proto_rawDesc), len(file_asset_grpc_proto_rawDesc)))
	})
	return file_asset_grpc_proto_rawDescData
}

var file_asset_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_asset_grpc_proto_goTypes = []any{
	(*AssetKey)(nil),           // 0: asset.AssetKey
	(*AssetQuery)(nil),         // 1: asset.AssetQuery
	(*UserAssetListKey)(nil),   // 2: asset.UserAssetListKey
	(*UserAssetListQuery)(nil), // 3: asset.UserAssetListQuery
	(metadata.Network)(0),      // 4: metadata.Network
	(AssetStatus)(0),           // 5: asset.AssetStatus
	(AssetType)(0),             // 6: asset.AssetType
	(UserAssetStatus)(0),       // 7: asset.UserAssetStatus
	(*Asset)(nil),              // 8: asset.Asset
	(*UserAssetList)(nil),      // 9: asset.UserAssetList
	(*Assets)(nil),             // 10: asset.Assets
	(*UserAssetLists)(nil),     // 11: asset.UserAssetLists
}
var file_asset_grpc_proto_depIdxs = []int32{
	4,  // 0: asset.AssetQuery.Network:type_name -> metadata.Network
	5,  // 1: asset.AssetQuery.Status:type_name -> asset.AssetStatus
	6,  // 2: asset.AssetQuery.AssetType:type_name -> asset.AssetType
	4,  // 3: asset.UserAssetListQuery.Network:type_name -> metadata.Network
	7,  // 4: asset.UserAssetListQuery.Status:type_name -> asset.UserAssetStatus
	8,  // 5: asset.AssetListService.UpsertAsset:input_type -> asset.Asset
	0,  // 6: asset.AssetListService.GetAsset:input_type -> asset.AssetKey
	1,  // 7: asset.AssetListService.GetAssets:input_type -> asset.AssetQuery
	9,  // 8: asset.AssetListService.UpsertUserAssetList:input_type -> asset.UserAssetList
	2,  // 9: asset.AssetListService.GetUserAssetList:input_type -> asset.UserAssetListKey
	3,  // 10: asset.AssetListService.GetUserAssetLists:input_type -> asset.UserAssetListQuery
	0,  // 11: asset.AssetListService.UpsertAsset:output_type -> asset.AssetKey
	8,  // 12: asset.AssetListService.GetAsset:output_type -> asset.Asset
	10, // 13: asset.AssetListService.GetAssets:output_type -> asset.Assets
	2,  // 14: asset.AssetListService.UpsertUserAssetList:output_type -> asset.UserAssetListKey
	9,  // 15: asset.AssetListService.GetUserAssetList:output_type -> asset.UserAssetList
	11, // 16: asset.AssetListService.GetUserAssetLists:output_type -> asset.UserAssetLists
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_asset_grpc_proto_init() }
func file_asset_grpc_proto_init() {
	if File_asset_grpc_proto != nil {
		return
	}
	file_asset_proto_init()
	file_asset_grpc_proto_msgTypes[1].OneofWrappers = []any{}
	file_asset_grpc_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_asset_grpc_proto_rawDesc), len(file_asset_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_asset_grpc_proto_goTypes,
		DependencyIndexes: file_asset_grpc_proto_depIdxs,
		MessageInfos:      file_asset_grpc_proto_msgTypes,
	}.Build()
	File_asset_grpc_proto = out.File
	file_asset_grpc_proto_goTypes = nil
	file_asset_grpc_proto_depIdxs = nil
}
