syntax = "proto3";

package asset;

import "asset.proto";

option go_package = "github.com/sologenic/com-fs-asset-model;asset";

service AssetListService { // TODO: Better name
    // Upsert on Asset
    rpc UpsertAsset(Asset) returns (AssetKey);
    // Get Asset by Key 
    rpc GetAsset(AssetKey) returns (Asset);
    // Get all Assets for a given filter
    rpc GetAssets(AssetQuery) returns (Assets);
    // Count all Assets for a given filter
    rpc CountAssets(AssetQuery) returns (CountResponse);
}   

message AssetKey {
    string Key = 1;
}

// TODO: Add more filters is IsIssued, IsVisible, IsSuperseded, ID
message AssetQuery {
    optional int32 Offset = 2;
    optional string OrganizationID = 4;
    optional AssetType AssetType = 6;
    optional int32 Limit = 8;
    optional bool IsPromoted = 12;
}

message CountResponse {
    int32 Count = 1;
}