syntax = "proto3";

package asset;

import "sologenic/com-fs-asset-model/domain/denom/denom.proto";
import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/struct.proto";

option go_package = "github.com/sologenic/com-fs-asset-model;asset";

message Asset {
    // Denom represented as a string
    // Immutable field
    string ID = 1 [
        (buf.validate.field).required = true,
        (buf.validate.field).string = {
            min_len: 43
            max_len: 256
            pattern: "^u[A-Za-z0-9.-]+_v[1-9][0-9]{0,2}-[a-zA-Z][a-zA-Z0-9]{37,126}$"
        }
    ];

    // Immutable field
    string OrganizationID = 2 [
        (buf.validate.field).string = {
            uuid: true
        }
    ];

    // Contains symbol, version, issuer address
    // Immutable field
    denom.Denom Denom = 3 [
        (buf.validate.field).required = true
    ];

    // Immutable field
    AssetType Type = 4 [
        (buf.validate.field).enum = {
            defined_only: true
            not_in: [0]
        }
    ];

    // @inject_tags: datastore:",noindex"
    string Name = 5 [
        (buf.validate.field).required = true
    ];

    // @inject_tags: datastore:",noindex"
    string Description = 6 [
        (buf.validate.field).string = {
            max_len: 256
        }
    ];

    // @inject_tags: datastore:",noindex"
    string HTML = 7 [
        (buf.validate.field).string = {
            max_len: 65536
        }
    ];

    // ISO 3166-1 alpha-3 code e.g. "USA", "CAD"
    string OriginCountryAlpha3 = 8 [
        (buf.validate.field).ignore = IGNORE_IF_ZERO_VALUE,
        (buf.validate.field).string = {
            len: 3,
            pattern: "^[A-Z]{3}$"
        }
    ];

    // If not nil means asset has been issued on chain
    // Immutable field
    optional google.protobuf.Timestamp IssuedAt = 9;

    // Controls whether the asset is visible in the marketplace
    bool IsVisible = 10;

    // Controls whether the asset is visible in the promoted assets panel
    bool IsPromoted = 11;

    optional google.protobuf.Timestamp SupersededAt = 12;

    string SupersededByID = 13 [
        (buf.validate.field).ignore = IGNORE_IF_ZERO_VALUE,
        (buf.validate.field).string = {
            min_len: 43
            max_len: 256
            pattern: "^u[A-Za-z0-9.-]+_v[1-9][0-9]{0,2}-[a-zA-Z][a-zA-Z0-9]{37,126}$"
        }
    ];

    repeated File Files = 14 [
        (buf.validate.field).repeated = {
            max_items: 128,
        }
    ];

    // Dynamic fields defined by front-end
    google.protobuf.Struct Details = 15;
}

message Assets {
    repeated Asset Records = 1;

    // If there is more data, this is the offset to pass to the next call
    optional int32 Offset = 2;
}

message File {
    string Name = 1 [
        (buf.validate.field).required = true,
        (buf.validate.field).string = {
            min_len: 2,
            max_len: 128
        }
    ];

    FileType Type = 2 [
        (buf.validate.field).enum = {
            defined_only: true
        }
    ];

    string Reference = 3 [
        (buf.validate.field).required = true,
        (buf.validate.field).string = {
            uri: true,
            prefix: "gs://",
            max_len: 256
        }
    ];
}

enum FileType {
    FILE_TYPE_NONE = 0;
    // TODO: Add generic file types like FILE_TYPE_LEGAL_DOCUMENT, FILE_TYPE_IMAGE, FILE_TYPE_BROCHURE etc
}

enum AssetType {
    ASSET_TYPE_NONE = 0;
    ASSET_TYPE_EQUITY = 1;
    ASSET_TYPE_RWA = 2;
    // TODO: Add more asset types
}