// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: asset-grpc.proto

package asset

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AssetListService_UpsertAsset_FullMethodName = "/asset.AssetListService/UpsertAsset"
	AssetListService_GetAsset_FullMethodName    = "/asset.AssetListService/GetAsset"
	AssetListService_GetAssets_FullMethodName   = "/asset.AssetListService/GetAssets"
	AssetListService_CountAssets_FullMethodName = "/asset.AssetListService/CountAssets"
)

// AssetListServiceClient is the client API for AssetListService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssetListServiceClient interface {
	// Upsert on Asset
	UpsertAsset(ctx context.Context, in *Asset, opts ...grpc.CallOption) (*AssetKey, error)
	// Get Asset by Key
	GetAsset(ctx context.Context, in *AssetKey, opts ...grpc.CallOption) (*Asset, error)
	// Get all Assets for a given filter
	GetAssets(ctx context.Context, in *AssetQuery, opts ...grpc.CallOption) (*Assets, error)
	// Count all Assets for a given filter
	CountAssets(ctx context.Context, in *AssetQuery, opts ...grpc.CallOption) (*CountResponse, error)
}

type assetListServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssetListServiceClient(cc grpc.ClientConnInterface) AssetListServiceClient {
	return &assetListServiceClient{cc}
}

func (c *assetListServiceClient) UpsertAsset(ctx context.Context, in *Asset, opts ...grpc.CallOption) (*AssetKey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssetKey)
	err := c.cc.Invoke(ctx, AssetListService_UpsertAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetListServiceClient) GetAsset(ctx context.Context, in *AssetKey, opts ...grpc.CallOption) (*Asset, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Asset)
	err := c.cc.Invoke(ctx, AssetListService_GetAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetListServiceClient) GetAssets(ctx context.Context, in *AssetQuery, opts ...grpc.CallOption) (*Assets, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Assets)
	err := c.cc.Invoke(ctx, AssetListService_GetAssets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetListServiceClient) CountAssets(ctx context.Context, in *AssetQuery, opts ...grpc.CallOption) (*CountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountResponse)
	err := c.cc.Invoke(ctx, AssetListService_CountAssets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssetListServiceServer is the server API for AssetListService service.
// All implementations should embed UnimplementedAssetListServiceServer
// for forward compatibility.
type AssetListServiceServer interface {
	// Upsert on Asset
	UpsertAsset(context.Context, *Asset) (*AssetKey, error)
	// Get Asset by Key
	GetAsset(context.Context, *AssetKey) (*Asset, error)
	// Get all Assets for a given filter
	GetAssets(context.Context, *AssetQuery) (*Assets, error)
	// Count all Assets for a given filter
	CountAssets(context.Context, *AssetQuery) (*CountResponse, error)
}

// UnimplementedAssetListServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAssetListServiceServer struct{}

func (UnimplementedAssetListServiceServer) UpsertAsset(context.Context, *Asset) (*AssetKey, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertAsset not implemented")
}
func (UnimplementedAssetListServiceServer) GetAsset(context.Context, *AssetKey) (*Asset, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAsset not implemented")
}
func (UnimplementedAssetListServiceServer) GetAssets(context.Context, *AssetQuery) (*Assets, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAssets not implemented")
}
func (UnimplementedAssetListServiceServer) CountAssets(context.Context, *AssetQuery) (*CountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CountAssets not implemented")
}
func (UnimplementedAssetListServiceServer) testEmbeddedByValue() {}

// UnsafeAssetListServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssetListServiceServer will
// result in compilation errors.
type UnsafeAssetListServiceServer interface {
	mustEmbedUnimplementedAssetListServiceServer()
}

func RegisterAssetListServiceServer(s grpc.ServiceRegistrar, srv AssetListServiceServer) {
	// If the following call panics, it indicates UnimplementedAssetListServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AssetListService_ServiceDesc, srv)
}

func _AssetListService_UpsertAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Asset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetListServiceServer).UpsertAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetListService_UpsertAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetListServiceServer).UpsertAsset(ctx, req.(*Asset))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetListService_GetAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetListServiceServer).GetAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetListService_GetAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetListServiceServer).GetAsset(ctx, req.(*AssetKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetListService_GetAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetListServiceServer).GetAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetListService_GetAssets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetListServiceServer).GetAssets(ctx, req.(*AssetQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetListService_CountAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetListServiceServer).CountAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetListService_CountAssets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetListServiceServer).CountAssets(ctx, req.(*AssetQuery))
	}
	return interceptor(ctx, in, info, handler)
}

// AssetListService_ServiceDesc is the grpc.ServiceDesc for AssetListService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssetListService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "asset.AssetListService",
	HandlerType: (*AssetListServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertAsset",
			Handler:    _AssetListService_UpsertAsset_Handler,
		},
		{
			MethodName: "GetAsset",
			Handler:    _AssetListService_GetAsset_Handler,
		},
		{
			MethodName: "GetAssets",
			Handler:    _AssetListService_GetAssets_Handler,
		},
		{
			MethodName: "CountAssets",
			Handler:    _AssetListService_CountAssets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "asset-grpc.proto",
}
