// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v5.26.1
// source: asset.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { Timestamp } from "./google/protobuf/timestamp";

export const protobufPackage = "asset";

export enum AssetStatus {
  ASSET_STATUS_DO_NOT_USE = 0,
  /** DO_NOT_LIST - BROKER_ASSET_ADMINISTRATOR only */
  DO_NOT_LIST = 1,
  /** REQUEST_LISTING - BROKER_ASSET_ADMINISTRATOR only */
  REQUEST_LISTING = 2,
  /** LISTED - ORGANIZATION_ASSET_ADMINISTRATOR only */
  LISTED = 3,
  /** ORGANIZATION_ADMIN_DO_NOT_LIST - ORGANIZATION_ASSET_ADMINISTRATOR only */
  ORGANIZATION_ADMIN_DO_NOT_LIST = 4,
  OUTDATED_ASSET_VERSION = 5,
  UNRECOGNIZED = -1,
}

export function assetStatusFromJSON(object: any): AssetStatus {
  switch (object) {
    case 0:
    case "ASSET_STATUS_DO_NOT_USE":
      return AssetStatus.ASSET_STATUS_DO_NOT_USE;
    case 1:
    case "DO_NOT_LIST":
      return AssetStatus.DO_NOT_LIST;
    case 2:
    case "REQUEST_LISTING":
      return AssetStatus.REQUEST_LISTING;
    case 3:
    case "LISTED":
      return AssetStatus.LISTED;
    case 4:
    case "ORGANIZATION_ADMIN_DO_NOT_LIST":
      return AssetStatus.ORGANIZATION_ADMIN_DO_NOT_LIST;
    case 5:
    case "OUTDATED_ASSET_VERSION":
      return AssetStatus.OUTDATED_ASSET_VERSION;
    case -1:
    case "UNRECOGNIZED":
    default:
      return AssetStatus.UNRECOGNIZED;
  }
}

export function assetStatusToJSON(object: AssetStatus): string {
  switch (object) {
    case AssetStatus.ASSET_STATUS_DO_NOT_USE:
      return "ASSET_STATUS_DO_NOT_USE";
    case AssetStatus.DO_NOT_LIST:
      return "DO_NOT_LIST";
    case AssetStatus.REQUEST_LISTING:
      return "REQUEST_LISTING";
    case AssetStatus.LISTED:
      return "LISTED";
    case AssetStatus.ORGANIZATION_ADMIN_DO_NOT_LIST:
      return "ORGANIZATION_ADMIN_DO_NOT_LIST";
    case AssetStatus.OUTDATED_ASSET_VERSION:
      return "OUTDATED_ASSET_VERSION";
    case AssetStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum Reason {
  REASON_DO_NOT_USE = 0,
  DUPLICATE = 1,
  UNWANTED_ASSET = 2,
  UNSTABLE_ASSET = 3,
  UNRECOGNIZED = -1,
}

export function reasonFromJSON(object: any): Reason {
  switch (object) {
    case 0:
    case "REASON_DO_NOT_USE":
      return Reason.REASON_DO_NOT_USE;
    case 1:
    case "DUPLICATE":
      return Reason.DUPLICATE;
    case 2:
    case "UNWANTED_ASSET":
      return Reason.UNWANTED_ASSET;
    case 3:
    case "UNSTABLE_ASSET":
      return Reason.UNSTABLE_ASSET;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Reason.UNRECOGNIZED;
  }
}

export function reasonToJSON(object: Reason): string {
  switch (object) {
    case Reason.REASON_DO_NOT_USE:
      return "REASON_DO_NOT_USE";
    case Reason.DUPLICATE:
      return "DUPLICATE";
    case Reason.UNWANTED_ASSET:
      return "UNWANTED_ASSET";
    case Reason.UNSTABLE_ASSET:
      return "UNSTABLE_ASSET";
    case Reason.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum AssetType {
  ASSET_TYPE_DO_NOT_USE = 0,
  STOCK = 1,
  UNRECOGNIZED = -1,
}

export function assetTypeFromJSON(object: any): AssetType {
  switch (object) {
    case 0:
    case "ASSET_TYPE_DO_NOT_USE":
      return AssetType.ASSET_TYPE_DO_NOT_USE;
    case 1:
    case "STOCK":
      return AssetType.STOCK;
    case -1:
    case "UNRECOGNIZED":
    default:
      return AssetType.UNRECOGNIZED;
  }
}

export function assetTypeToJSON(object: AssetType): string {
  switch (object) {
    case AssetType.ASSET_TYPE_DO_NOT_USE:
      return "ASSET_TYPE_DO_NOT_USE";
    case AssetType.STOCK:
      return "STOCK";
    case AssetType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum UserAssetStatus {
  USER_ASSET_STATUS_DO_NOT_USE = 0,
  NOT_WHITELISTED = 1,
  WHITELISTING_REQUESTED = 2,
  WHITELISTED = 3,
  OUTDATED_VERSION = 4,
  UNRECOGNIZED = -1,
}

export function userAssetStatusFromJSON(object: any): UserAssetStatus {
  switch (object) {
    case 0:
    case "USER_ASSET_STATUS_DO_NOT_USE":
      return UserAssetStatus.USER_ASSET_STATUS_DO_NOT_USE;
    case 1:
    case "NOT_WHITELISTED":
      return UserAssetStatus.NOT_WHITELISTED;
    case 2:
    case "WHITELISTING_REQUESTED":
      return UserAssetStatus.WHITELISTING_REQUESTED;
    case 3:
    case "WHITELISTED":
      return UserAssetStatus.WHITELISTED;
    case 4:
    case "OUTDATED_VERSION":
      return UserAssetStatus.OUTDATED_VERSION;
    case -1:
    case "UNRECOGNIZED":
    default:
      return UserAssetStatus.UNRECOGNIZED;
  }
}

export function userAssetStatusToJSON(object: UserAssetStatus): string {
  switch (object) {
    case UserAssetStatus.USER_ASSET_STATUS_DO_NOT_USE:
      return "USER_ASSET_STATUS_DO_NOT_USE";
    case UserAssetStatus.NOT_WHITELISTED:
      return "NOT_WHITELISTED";
    case UserAssetStatus.WHITELISTING_REQUESTED:
      return "WHITELISTING_REQUESTED";
    case UserAssetStatus.WHITELISTED:
      return "WHITELISTED";
    case UserAssetStatus.OUTDATED_VERSION:
      return "OUTDATED_VERSION";
    case UserAssetStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Asset {
  /** Key combination: Currency-OrganizationID-Version (Symbol-Version) */
  ID: string;
  /** External entity (broker) that owns this asset, e.g. issuer */
  OrganizationID: string;
  Status: AssetStatus;
  Reason?:
    | Reason
    | undefined;
  /** list of jurisdictionIDs where this asset is allowed to be traded */
  JurisdictionIDs: string[];
  Network: string;
  CreatedAt: Date | undefined;
  UpdatedAt: Date | undefined;
  Type: AssetType;
  /** Flattened StockProperties */
  Symbol: string;
  Currency: string;
  Version: string;
  Precision: number;
  Name: string;
  ExchangeTickerSymbol: string;
  Exchange: string;
  Description: string;
  /**
   * Denomination in the Smart Contract
   * {Symbol}_v{Version}-{SmartContract addr} where Symbol is the symbol in the smart contract, not Symbol in the Asset object
   * - is not allwed in symbol in the coreum smart contract: https://github.com/CoreumFoundation/coreum/blob/e5f74cfa51e3a83d101c0a307af18378c18d4748/x/asset/ft/types/token.go#L21
   * e.g. "btc_v1-testcore1et29cek95pl0zralsf43u4uply0g9nmxnj7fyt9yfy74spch7fpq3f8j0e"
   */
  DENOM: string;
  SmartContractAddress: string;
}

export interface Assets {
  Assets: Asset[];
}

export interface UserAssetList {
  /** Key combination: Currency-OrganizationID-Version-AccountID-Wallet (AssetKey-AccountID-Wallet) */
  AccountID: string;
  Wallet: string;
  /** Stable Key: "Currency-OrganizationID-Version" */
  AssetKey: string;
  Status: UserAssetStatus;
  Network: string;
  Visible: boolean;
  CreatedAt: Date | undefined;
  UpdatedAt: Date | undefined;
}

export interface UserAssetLists {
  UserAssetLists: UserAssetList[];
}

function createBaseAsset(): Asset {
  return {
    ID: "",
    OrganizationID: "",
    Status: 0,
    Reason: undefined,
    JurisdictionIDs: [],
    Network: "",
    CreatedAt: undefined,
    UpdatedAt: undefined,
    Type: 0,
    Symbol: "",
    Currency: "",
    Version: "",
    Precision: 0,
    Name: "",
    ExchangeTickerSymbol: "",
    Exchange: "",
    Description: "",
    DENOM: "",
    SmartContractAddress: "",
  };
}

export const Asset = {
  encode(message: Asset, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.ID !== "") {
      writer.uint32(10).string(message.ID);
    }
    if (message.OrganizationID !== "") {
      writer.uint32(18).string(message.OrganizationID);
    }
    if (message.Status !== 0) {
      writer.uint32(24).int32(message.Status);
    }
    if (message.Reason !== undefined) {
      writer.uint32(32).int32(message.Reason);
    }
    for (const v of message.JurisdictionIDs) {
      writer.uint32(42).string(v!);
    }
    if (message.Network !== "") {
      writer.uint32(50).string(message.Network);
    }
    if (message.CreatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.CreatedAt), writer.uint32(58).fork()).ldelim();
    }
    if (message.UpdatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.UpdatedAt), writer.uint32(66).fork()).ldelim();
    }
    if (message.Type !== 0) {
      writer.uint32(72).int32(message.Type);
    }
    if (message.Symbol !== "") {
      writer.uint32(82).string(message.Symbol);
    }
    if (message.Currency !== "") {
      writer.uint32(90).string(message.Currency);
    }
    if (message.Version !== "") {
      writer.uint32(98).string(message.Version);
    }
    if (message.Precision !== 0) {
      writer.uint32(104).int32(message.Precision);
    }
    if (message.Name !== "") {
      writer.uint32(114).string(message.Name);
    }
    if (message.ExchangeTickerSymbol !== "") {
      writer.uint32(122).string(message.ExchangeTickerSymbol);
    }
    if (message.Exchange !== "") {
      writer.uint32(130).string(message.Exchange);
    }
    if (message.Description !== "") {
      writer.uint32(138).string(message.Description);
    }
    if (message.DENOM !== "") {
      writer.uint32(146).string(message.DENOM);
    }
    if (message.SmartContractAddress !== "") {
      writer.uint32(154).string(message.SmartContractAddress);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Asset {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAsset();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.ID = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.OrganizationID = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.Status = reader.int32() as any;
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.Reason = reader.int32() as any;
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.JurisdictionIDs.push(reader.string());
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.Network = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.CreatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.UpdatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.Type = reader.int32() as any;
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.Symbol = reader.string();
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.Currency = reader.string();
          continue;
        case 12:
          if (tag !== 98) {
            break;
          }

          message.Version = reader.string();
          continue;
        case 13:
          if (tag !== 104) {
            break;
          }

          message.Precision = reader.int32();
          continue;
        case 14:
          if (tag !== 114) {
            break;
          }

          message.Name = reader.string();
          continue;
        case 15:
          if (tag !== 122) {
            break;
          }

          message.ExchangeTickerSymbol = reader.string();
          continue;
        case 16:
          if (tag !== 130) {
            break;
          }

          message.Exchange = reader.string();
          continue;
        case 17:
          if (tag !== 138) {
            break;
          }

          message.Description = reader.string();
          continue;
        case 18:
          if (tag !== 146) {
            break;
          }

          message.DENOM = reader.string();
          continue;
        case 19:
          if (tag !== 154) {
            break;
          }

          message.SmartContractAddress = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Asset {
    return {
      ID: isSet(object.ID) ? globalThis.String(object.ID) : "",
      OrganizationID: isSet(object.OrganizationID) ? globalThis.String(object.OrganizationID) : "",
      Status: isSet(object.Status) ? assetStatusFromJSON(object.Status) : 0,
      Reason: isSet(object.Reason) ? reasonFromJSON(object.Reason) : undefined,
      JurisdictionIDs: globalThis.Array.isArray(object?.JurisdictionIDs)
        ? object.JurisdictionIDs.map((e: any) => globalThis.String(e))
        : [],
      Network: isSet(object.Network) ? globalThis.String(object.Network) : "",
      CreatedAt: isSet(object.CreatedAt) ? fromJsonTimestamp(object.CreatedAt) : undefined,
      UpdatedAt: isSet(object.UpdatedAt) ? fromJsonTimestamp(object.UpdatedAt) : undefined,
      Type: isSet(object.Type) ? assetTypeFromJSON(object.Type) : 0,
      Symbol: isSet(object.Symbol) ? globalThis.String(object.Symbol) : "",
      Currency: isSet(object.Currency) ? globalThis.String(object.Currency) : "",
      Version: isSet(object.Version) ? globalThis.String(object.Version) : "",
      Precision: isSet(object.Precision) ? globalThis.Number(object.Precision) : 0,
      Name: isSet(object.Name) ? globalThis.String(object.Name) : "",
      ExchangeTickerSymbol: isSet(object.ExchangeTickerSymbol) ? globalThis.String(object.ExchangeTickerSymbol) : "",
      Exchange: isSet(object.Exchange) ? globalThis.String(object.Exchange) : "",
      Description: isSet(object.Description) ? globalThis.String(object.Description) : "",
      DENOM: isSet(object.DENOM) ? globalThis.String(object.DENOM) : "",
      SmartContractAddress: isSet(object.SmartContractAddress) ? globalThis.String(object.SmartContractAddress) : "",
    };
  },

  toJSON(message: Asset): unknown {
    const obj: any = {};
    if (message.ID !== "") {
      obj.ID = message.ID;
    }
    if (message.OrganizationID !== "") {
      obj.OrganizationID = message.OrganizationID;
    }
    if (message.Status !== 0) {
      obj.Status = assetStatusToJSON(message.Status);
    }
    if (message.Reason !== undefined) {
      obj.Reason = reasonToJSON(message.Reason);
    }
    if (message.JurisdictionIDs?.length) {
      obj.JurisdictionIDs = message.JurisdictionIDs;
    }
    if (message.Network !== "") {
      obj.Network = message.Network;
    }
    if (message.CreatedAt !== undefined) {
      obj.CreatedAt = message.CreatedAt.toISOString();
    }
    if (message.UpdatedAt !== undefined) {
      obj.UpdatedAt = message.UpdatedAt.toISOString();
    }
    if (message.Type !== 0) {
      obj.Type = assetTypeToJSON(message.Type);
    }
    if (message.Symbol !== "") {
      obj.Symbol = message.Symbol;
    }
    if (message.Currency !== "") {
      obj.Currency = message.Currency;
    }
    if (message.Version !== "") {
      obj.Version = message.Version;
    }
    if (message.Precision !== 0) {
      obj.Precision = Math.round(message.Precision);
    }
    if (message.Name !== "") {
      obj.Name = message.Name;
    }
    if (message.ExchangeTickerSymbol !== "") {
      obj.ExchangeTickerSymbol = message.ExchangeTickerSymbol;
    }
    if (message.Exchange !== "") {
      obj.Exchange = message.Exchange;
    }
    if (message.Description !== "") {
      obj.Description = message.Description;
    }
    if (message.DENOM !== "") {
      obj.DENOM = message.DENOM;
    }
    if (message.SmartContractAddress !== "") {
      obj.SmartContractAddress = message.SmartContractAddress;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Asset>, I>>(base?: I): Asset {
    return Asset.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Asset>, I>>(object: I): Asset {
    const message = createBaseAsset();
    message.ID = object.ID ?? "";
    message.OrganizationID = object.OrganizationID ?? "";
    message.Status = object.Status ?? 0;
    message.Reason = object.Reason ?? undefined;
    message.JurisdictionIDs = object.JurisdictionIDs?.map((e) => e) || [];
    message.Network = object.Network ?? "";
    message.CreatedAt = object.CreatedAt ?? undefined;
    message.UpdatedAt = object.UpdatedAt ?? undefined;
    message.Type = object.Type ?? 0;
    message.Symbol = object.Symbol ?? "";
    message.Currency = object.Currency ?? "";
    message.Version = object.Version ?? "";
    message.Precision = object.Precision ?? 0;
    message.Name = object.Name ?? "";
    message.ExchangeTickerSymbol = object.ExchangeTickerSymbol ?? "";
    message.Exchange = object.Exchange ?? "";
    message.Description = object.Description ?? "";
    message.DENOM = object.DENOM ?? "";
    message.SmartContractAddress = object.SmartContractAddress ?? "";
    return message;
  },
};

function createBaseAssets(): Assets {
  return { Assets: [] };
}

export const Assets = {
  encode(message: Assets, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.Assets) {
      Asset.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Assets {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAssets();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Assets.push(Asset.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Assets {
    return { Assets: globalThis.Array.isArray(object?.Assets) ? object.Assets.map((e: any) => Asset.fromJSON(e)) : [] };
  },

  toJSON(message: Assets): unknown {
    const obj: any = {};
    if (message.Assets?.length) {
      obj.Assets = message.Assets.map((e) => Asset.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Assets>, I>>(base?: I): Assets {
    return Assets.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Assets>, I>>(object: I): Assets {
    const message = createBaseAssets();
    message.Assets = object.Assets?.map((e) => Asset.fromPartial(e)) || [];
    return message;
  },
};

function createBaseUserAssetList(): UserAssetList {
  return {
    AccountID: "",
    Wallet: "",
    AssetKey: "",
    Status: 0,
    Network: "",
    Visible: false,
    CreatedAt: undefined,
    UpdatedAt: undefined,
  };
}

export const UserAssetList = {
  encode(message: UserAssetList, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.AccountID !== "") {
      writer.uint32(10).string(message.AccountID);
    }
    if (message.Wallet !== "") {
      writer.uint32(18).string(message.Wallet);
    }
    if (message.AssetKey !== "") {
      writer.uint32(26).string(message.AssetKey);
    }
    if (message.Status !== 0) {
      writer.uint32(32).int32(message.Status);
    }
    if (message.Network !== "") {
      writer.uint32(42).string(message.Network);
    }
    if (message.Visible !== false) {
      writer.uint32(48).bool(message.Visible);
    }
    if (message.CreatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.CreatedAt), writer.uint32(58).fork()).ldelim();
    }
    if (message.UpdatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.UpdatedAt), writer.uint32(66).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): UserAssetList {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserAssetList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.AccountID = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.Wallet = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.AssetKey = reader.string();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.Status = reader.int32() as any;
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.Network = reader.string();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.Visible = reader.bool();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.CreatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.UpdatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserAssetList {
    return {
      AccountID: isSet(object.AccountID) ? globalThis.String(object.AccountID) : "",
      Wallet: isSet(object.Wallet) ? globalThis.String(object.Wallet) : "",
      AssetKey: isSet(object.AssetKey) ? globalThis.String(object.AssetKey) : "",
      Status: isSet(object.Status) ? userAssetStatusFromJSON(object.Status) : 0,
      Network: isSet(object.Network) ? globalThis.String(object.Network) : "",
      Visible: isSet(object.Visible) ? globalThis.Boolean(object.Visible) : false,
      CreatedAt: isSet(object.CreatedAt) ? fromJsonTimestamp(object.CreatedAt) : undefined,
      UpdatedAt: isSet(object.UpdatedAt) ? fromJsonTimestamp(object.UpdatedAt) : undefined,
    };
  },

  toJSON(message: UserAssetList): unknown {
    const obj: any = {};
    if (message.AccountID !== "") {
      obj.AccountID = message.AccountID;
    }
    if (message.Wallet !== "") {
      obj.Wallet = message.Wallet;
    }
    if (message.AssetKey !== "") {
      obj.AssetKey = message.AssetKey;
    }
    if (message.Status !== 0) {
      obj.Status = userAssetStatusToJSON(message.Status);
    }
    if (message.Network !== "") {
      obj.Network = message.Network;
    }
    if (message.Visible !== false) {
      obj.Visible = message.Visible;
    }
    if (message.CreatedAt !== undefined) {
      obj.CreatedAt = message.CreatedAt.toISOString();
    }
    if (message.UpdatedAt !== undefined) {
      obj.UpdatedAt = message.UpdatedAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserAssetList>, I>>(base?: I): UserAssetList {
    return UserAssetList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserAssetList>, I>>(object: I): UserAssetList {
    const message = createBaseUserAssetList();
    message.AccountID = object.AccountID ?? "";
    message.Wallet = object.Wallet ?? "";
    message.AssetKey = object.AssetKey ?? "";
    message.Status = object.Status ?? 0;
    message.Network = object.Network ?? "";
    message.Visible = object.Visible ?? false;
    message.CreatedAt = object.CreatedAt ?? undefined;
    message.UpdatedAt = object.UpdatedAt ?? undefined;
    return message;
  },
};

function createBaseUserAssetLists(): UserAssetLists {
  return { UserAssetLists: [] };
}

export const UserAssetLists = {
  encode(message: UserAssetLists, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.UserAssetLists) {
      UserAssetList.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): UserAssetLists {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserAssetLists();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.UserAssetLists.push(UserAssetList.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserAssetLists {
    return {
      UserAssetLists: globalThis.Array.isArray(object?.UserAssetLists)
        ? object.UserAssetLists.map((e: any) => UserAssetList.fromJSON(e))
        : [],
    };
  },

  toJSON(message: UserAssetLists): unknown {
    const obj: any = {};
    if (message.UserAssetLists?.length) {
      obj.UserAssetLists = message.UserAssetLists.map((e) => UserAssetList.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserAssetLists>, I>>(base?: I): UserAssetLists {
    return UserAssetLists.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserAssetLists>, I>>(object: I): UserAssetLists {
    const message = createBaseUserAssetLists();
    message.UserAssetLists = object.UserAssetLists?.map((e) => UserAssetList.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
