// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package asset

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AssetListServiceClient is the client API for AssetListService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssetListServiceClient interface {
	// Upsert on Asset
	UpsertAsset(ctx context.Context, in *Asset, opts ...grpc.CallOption) (*AssetKey, error)
	// Get Asset by ID
	GetAsset(ctx context.Context, in *AssetKey, opts ...grpc.CallOption) (*Asset, error)
	// Get all Assets for a given filter
	GetAssets(ctx context.Context, in *AssetQuery, opts ...grpc.CallOption) (*Assets, error)
	// Upsert on UserAssetList
	UpsertUserAssetList(ctx context.Context, in *UserAssetList, opts ...grpc.CallOption) (*AssetKey, error)
	// Get UserAssetList by ID
	GetUserAssetList(ctx context.Context, in *UserAssetListKey, opts ...grpc.CallOption) (*UserAssetList, error)
	// Get all UserAssetList for a given filter
	GetUserAssetLists(ctx context.Context, in *UserAssetListQuery, opts ...grpc.CallOption) (*UserAssetLists, error)
	// Upsert on Jurisdiction
	UpsertJurisdiction(ctx context.Context, in *Jurisdiction, opts ...grpc.CallOption) (*JurisdictionID, error)
	// Get Jurisdiction by ID
	GetJurisdiction(ctx context.Context, in *JurisdictionID, opts ...grpc.CallOption) (*Jurisdiction, error)
	// Get all Jurisdictions for a given filter
	GetJurisdictions(ctx context.Context, in *JurisdictionQuery, opts ...grpc.CallOption) (*Jurisdictions, error)
	// Upsert on User Jurisdiction
	UpsertUserJurisdiction(ctx context.Context, in *UserJurisdiction, opts ...grpc.CallOption) (*UserJurisdictionKey, error)
	// Get User Jurisdiction by ID
	GetUserJurisdiction(ctx context.Context, in *UserJurisdictionKey, opts ...grpc.CallOption) (*UserJurisdiction, error)
	// Get all User Jurisdictions for a given filter
	GetUserJurisdictions(ctx context.Context, in *UserJurisdictionQuery, opts ...grpc.CallOption) (*UserJurisdictions, error)
}

type assetListServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssetListServiceClient(cc grpc.ClientConnInterface) AssetListServiceClient {
	return &assetListServiceClient{cc}
}

func (c *assetListServiceClient) UpsertAsset(ctx context.Context, in *Asset, opts ...grpc.CallOption) (*AssetKey, error) {
	out := new(AssetKey)
	err := c.cc.Invoke(ctx, "/asset.AssetListService/UpsertAsset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetListServiceClient) GetAsset(ctx context.Context, in *AssetKey, opts ...grpc.CallOption) (*Asset, error) {
	out := new(Asset)
	err := c.cc.Invoke(ctx, "/asset.AssetListService/GetAsset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetListServiceClient) GetAssets(ctx context.Context, in *AssetQuery, opts ...grpc.CallOption) (*Assets, error) {
	out := new(Assets)
	err := c.cc.Invoke(ctx, "/asset.AssetListService/GetAssets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetListServiceClient) UpsertUserAssetList(ctx context.Context, in *UserAssetList, opts ...grpc.CallOption) (*AssetKey, error) {
	out := new(AssetKey)
	err := c.cc.Invoke(ctx, "/asset.AssetListService/UpsertUserAssetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetListServiceClient) GetUserAssetList(ctx context.Context, in *UserAssetListKey, opts ...grpc.CallOption) (*UserAssetList, error) {
	out := new(UserAssetList)
	err := c.cc.Invoke(ctx, "/asset.AssetListService/GetUserAssetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetListServiceClient) GetUserAssetLists(ctx context.Context, in *UserAssetListQuery, opts ...grpc.CallOption) (*UserAssetLists, error) {
	out := new(UserAssetLists)
	err := c.cc.Invoke(ctx, "/asset.AssetListService/GetUserAssetLists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetListServiceClient) UpsertJurisdiction(ctx context.Context, in *Jurisdiction, opts ...grpc.CallOption) (*JurisdictionID, error) {
	out := new(JurisdictionID)
	err := c.cc.Invoke(ctx, "/asset.AssetListService/UpsertJurisdiction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetListServiceClient) GetJurisdiction(ctx context.Context, in *JurisdictionID, opts ...grpc.CallOption) (*Jurisdiction, error) {
	out := new(Jurisdiction)
	err := c.cc.Invoke(ctx, "/asset.AssetListService/GetJurisdiction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetListServiceClient) GetJurisdictions(ctx context.Context, in *JurisdictionQuery, opts ...grpc.CallOption) (*Jurisdictions, error) {
	out := new(Jurisdictions)
	err := c.cc.Invoke(ctx, "/asset.AssetListService/GetJurisdictions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetListServiceClient) UpsertUserJurisdiction(ctx context.Context, in *UserJurisdiction, opts ...grpc.CallOption) (*UserJurisdictionKey, error) {
	out := new(UserJurisdictionKey)
	err := c.cc.Invoke(ctx, "/asset.AssetListService/UpsertUserJurisdiction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetListServiceClient) GetUserJurisdiction(ctx context.Context, in *UserJurisdictionKey, opts ...grpc.CallOption) (*UserJurisdiction, error) {
	out := new(UserJurisdiction)
	err := c.cc.Invoke(ctx, "/asset.AssetListService/GetUserJurisdiction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetListServiceClient) GetUserJurisdictions(ctx context.Context, in *UserJurisdictionQuery, opts ...grpc.CallOption) (*UserJurisdictions, error) {
	out := new(UserJurisdictions)
	err := c.cc.Invoke(ctx, "/asset.AssetListService/GetUserJurisdictions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssetListServiceServer is the server API for AssetListService service.
// All implementations should embed UnimplementedAssetListServiceServer
// for forward compatibility
type AssetListServiceServer interface {
	// Upsert on Asset
	UpsertAsset(context.Context, *Asset) (*AssetKey, error)
	// Get Asset by ID
	GetAsset(context.Context, *AssetKey) (*Asset, error)
	// Get all Assets for a given filter
	GetAssets(context.Context, *AssetQuery) (*Assets, error)
	// Upsert on UserAssetList
	UpsertUserAssetList(context.Context, *UserAssetList) (*AssetKey, error)
	// Get UserAssetList by ID
	GetUserAssetList(context.Context, *UserAssetListKey) (*UserAssetList, error)
	// Get all UserAssetList for a given filter
	GetUserAssetLists(context.Context, *UserAssetListQuery) (*UserAssetLists, error)
	// Upsert on Jurisdiction
	UpsertJurisdiction(context.Context, *Jurisdiction) (*JurisdictionID, error)
	// Get Jurisdiction by ID
	GetJurisdiction(context.Context, *JurisdictionID) (*Jurisdiction, error)
	// Get all Jurisdictions for a given filter
	GetJurisdictions(context.Context, *JurisdictionQuery) (*Jurisdictions, error)
	// Upsert on User Jurisdiction
	UpsertUserJurisdiction(context.Context, *UserJurisdiction) (*UserJurisdictionKey, error)
	// Get User Jurisdiction by ID
	GetUserJurisdiction(context.Context, *UserJurisdictionKey) (*UserJurisdiction, error)
	// Get all User Jurisdictions for a given filter
	GetUserJurisdictions(context.Context, *UserJurisdictionQuery) (*UserJurisdictions, error)
}

// UnimplementedAssetListServiceServer should be embedded to have forward compatible implementations.
type UnimplementedAssetListServiceServer struct {
}

func (UnimplementedAssetListServiceServer) UpsertAsset(context.Context, *Asset) (*AssetKey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertAsset not implemented")
}
func (UnimplementedAssetListServiceServer) GetAsset(context.Context, *AssetKey) (*Asset, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAsset not implemented")
}
func (UnimplementedAssetListServiceServer) GetAssets(context.Context, *AssetQuery) (*Assets, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssets not implemented")
}
func (UnimplementedAssetListServiceServer) UpsertUserAssetList(context.Context, *UserAssetList) (*AssetKey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertUserAssetList not implemented")
}
func (UnimplementedAssetListServiceServer) GetUserAssetList(context.Context, *UserAssetListKey) (*UserAssetList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserAssetList not implemented")
}
func (UnimplementedAssetListServiceServer) GetUserAssetLists(context.Context, *UserAssetListQuery) (*UserAssetLists, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserAssetLists not implemented")
}
func (UnimplementedAssetListServiceServer) UpsertJurisdiction(context.Context, *Jurisdiction) (*JurisdictionID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertJurisdiction not implemented")
}
func (UnimplementedAssetListServiceServer) GetJurisdiction(context.Context, *JurisdictionID) (*Jurisdiction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJurisdiction not implemented")
}
func (UnimplementedAssetListServiceServer) GetJurisdictions(context.Context, *JurisdictionQuery) (*Jurisdictions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJurisdictions not implemented")
}
func (UnimplementedAssetListServiceServer) UpsertUserJurisdiction(context.Context, *UserJurisdiction) (*UserJurisdictionKey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertUserJurisdiction not implemented")
}
func (UnimplementedAssetListServiceServer) GetUserJurisdiction(context.Context, *UserJurisdictionKey) (*UserJurisdiction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserJurisdiction not implemented")
}
func (UnimplementedAssetListServiceServer) GetUserJurisdictions(context.Context, *UserJurisdictionQuery) (*UserJurisdictions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserJurisdictions not implemented")
}

// UnsafeAssetListServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssetListServiceServer will
// result in compilation errors.
type UnsafeAssetListServiceServer interface {
	mustEmbedUnimplementedAssetListServiceServer()
}

func RegisterAssetListServiceServer(s grpc.ServiceRegistrar, srv AssetListServiceServer) {
	s.RegisterService(&AssetListService_ServiceDesc, srv)
}

func _AssetListService_UpsertAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Asset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetListServiceServer).UpsertAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/asset.AssetListService/UpsertAsset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetListServiceServer).UpsertAsset(ctx, req.(*Asset))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetListService_GetAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetListServiceServer).GetAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/asset.AssetListService/GetAsset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetListServiceServer).GetAsset(ctx, req.(*AssetKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetListService_GetAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetListServiceServer).GetAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/asset.AssetListService/GetAssets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetListServiceServer).GetAssets(ctx, req.(*AssetQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetListService_UpsertUserAssetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAssetList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetListServiceServer).UpsertUserAssetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/asset.AssetListService/UpsertUserAssetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetListServiceServer).UpsertUserAssetList(ctx, req.(*UserAssetList))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetListService_GetUserAssetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAssetListKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetListServiceServer).GetUserAssetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/asset.AssetListService/GetUserAssetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetListServiceServer).GetUserAssetList(ctx, req.(*UserAssetListKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetListService_GetUserAssetLists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAssetListQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetListServiceServer).GetUserAssetLists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/asset.AssetListService/GetUserAssetLists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetListServiceServer).GetUserAssetLists(ctx, req.(*UserAssetListQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetListService_UpsertJurisdiction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Jurisdiction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetListServiceServer).UpsertJurisdiction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/asset.AssetListService/UpsertJurisdiction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetListServiceServer).UpsertJurisdiction(ctx, req.(*Jurisdiction))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetListService_GetJurisdiction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JurisdictionID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetListServiceServer).GetJurisdiction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/asset.AssetListService/GetJurisdiction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetListServiceServer).GetJurisdiction(ctx, req.(*JurisdictionID))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetListService_GetJurisdictions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JurisdictionQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetListServiceServer).GetJurisdictions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/asset.AssetListService/GetJurisdictions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetListServiceServer).GetJurisdictions(ctx, req.(*JurisdictionQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetListService_UpsertUserJurisdiction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserJurisdiction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetListServiceServer).UpsertUserJurisdiction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/asset.AssetListService/UpsertUserJurisdiction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetListServiceServer).UpsertUserJurisdiction(ctx, req.(*UserJurisdiction))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetListService_GetUserJurisdiction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserJurisdictionKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetListServiceServer).GetUserJurisdiction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/asset.AssetListService/GetUserJurisdiction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetListServiceServer).GetUserJurisdiction(ctx, req.(*UserJurisdictionKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetListService_GetUserJurisdictions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserJurisdictionQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetListServiceServer).GetUserJurisdictions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/asset.AssetListService/GetUserJurisdictions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetListServiceServer).GetUserJurisdictions(ctx, req.(*UserJurisdictionQuery))
	}
	return interceptor(ctx, in, info, handler)
}

// AssetListService_ServiceDesc is the grpc.ServiceDesc for AssetListService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssetListService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "asset.AssetListService",
	HandlerType: (*AssetListServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertAsset",
			Handler:    _AssetListService_UpsertAsset_Handler,
		},
		{
			MethodName: "GetAsset",
			Handler:    _AssetListService_GetAsset_Handler,
		},
		{
			MethodName: "GetAssets",
			Handler:    _AssetListService_GetAssets_Handler,
		},
		{
			MethodName: "UpsertUserAssetList",
			Handler:    _AssetListService_UpsertUserAssetList_Handler,
		},
		{
			MethodName: "GetUserAssetList",
			Handler:    _AssetListService_GetUserAssetList_Handler,
		},
		{
			MethodName: "GetUserAssetLists",
			Handler:    _AssetListService_GetUserAssetLists_Handler,
		},
		{
			MethodName: "UpsertJurisdiction",
			Handler:    _AssetListService_UpsertJurisdiction_Handler,
		},
		{
			MethodName: "GetJurisdiction",
			Handler:    _AssetListService_GetJurisdiction_Handler,
		},
		{
			MethodName: "GetJurisdictions",
			Handler:    _AssetListService_GetJurisdictions_Handler,
		},
		{
			MethodName: "UpsertUserJurisdiction",
			Handler:    _AssetListService_UpsertUserJurisdiction_Handler,
		},
		{
			MethodName: "GetUserJurisdiction",
			Handler:    _AssetListService_GetUserJurisdiction_Handler,
		},
		{
			MethodName: "GetUserJurisdictions",
			Handler:    _AssetListService_GetUserJurisdictions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "asset-grpc.proto",
}
