// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v7.35.1
// source: asset.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { Struct } from "./google/protobuf/struct";
import { Timestamp } from "./google/protobuf/timestamp";
import { Denom } from "./sologenic/com-fs-asset-model/domain/denom/denom";

export const protobufPackage = "asset";

export enum FileType {
  /** FILE_TYPE_NONE - TODO: Add generic file types like FILE_TYPE_LEGAL_DOCUMENT, FILE_TYPE_IMAGE, FILE_TYPE_BROCHURE etc */
  FILE_TYPE_NONE = 0,
  UNRECOGNIZED = -1,
}

export function fileTypeFromJSON(object: any): FileType {
  switch (object) {
    case 0:
    case "FILE_TYPE_NONE":
      return FileType.FILE_TYPE_NONE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return FileType.UNRECOGNIZED;
  }
}

export function fileTypeToJSON(object: FileType): string {
  switch (object) {
    case FileType.FILE_TYPE_NONE:
      return "FILE_TYPE_NONE";
    case FileType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum AssetType {
  ASSET_TYPE_NONE = 0,
  /** ASSET_TYPE_SECURITY - TODO: Add more asset types */
  ASSET_TYPE_SECURITY = 1,
  UNRECOGNIZED = -1,
}

export function assetTypeFromJSON(object: any): AssetType {
  switch (object) {
    case 0:
    case "ASSET_TYPE_NONE":
      return AssetType.ASSET_TYPE_NONE;
    case 1:
    case "ASSET_TYPE_SECURITY":
      return AssetType.ASSET_TYPE_SECURITY;
    case -1:
    case "UNRECOGNIZED":
    default:
      return AssetType.UNRECOGNIZED;
  }
}

export function assetTypeToJSON(object: AssetType): string {
  switch (object) {
    case AssetType.ASSET_TYPE_NONE:
      return "ASSET_TYPE_NONE";
    case AssetType.ASSET_TYPE_SECURITY:
      return "ASSET_TYPE_SECURITY";
    case AssetType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Asset {
  /**
   * Unique string representation of the asset's denom.
   * Immutable: Cannot be modified after creation.
   */
  ID: string;
  /**
   * Unique identifier of the organization that owns or issued the asset.
   * Immutable: Cannot be modified after creation.
   */
  OrganizationID: string;
  /**
   * Structured denomination data (symbol, version, issuer address).
   * Immutable: Cannot be modified after creation.
   */
  Denom:
    | Denom
    | undefined;
  /**
   * Categorization of the asset.
   * Immutable: Cannot be modified after creation.
   */
  Type: AssetType;
  /**
   * Display name of the asset.
   * @inject_tags: datastore:",noindex"
   */
  Name: string;
  /**
   * Short plain-text summary of the asset.
   * Suitable for UI previews, cards, and OG meta tags.
   * @inject_tags: datastore:",noindex"
   */
  Description: string;
  /**
   * Extended WYSIWYG content providing a detailed overview of the asset.
   * @inject_tags: datastore:",noindex"
   */
  Content: string;
  /** Country of origin represented as an ISO 3166-1 alpha-3 code (e.g., "USA", "CAD"). */
  OriginCountryAlpha3: string;
  /**
   * Timestamp indicating when the asset was issued on-chain.
   * System-managed: Set automatically via on-chain events. Becomes immutable once set.
   */
  IssuedAt?:
    | Date
    | undefined;
  /**
   * Indicates whether the asset is active/enabled on-chain.
   * System-managed: Updated automatically via on-chain events. Cannot be mutated manually.
   */
  IsEnabled: boolean;
  /**
   * Controls whether the asset is visible in the public marketplace.
   * Mutable by administrators.
   */
  IsVisible: boolean;
  /**
   * Controls whether the asset is highlighted in the promoted assets panel.
   * Mutable by administrators.
   */
  IsPromoted: boolean;
  /** Attached media and documents (e.g., legal agreements, brochures, images). */
  Files: File[];
  /** Flexible key-value store for arbitrary, frontend-defined dynamic attributes. */
  Details:
    | { [key: string]: any }
    | undefined;
  /** Set to now on create. Immutable afterwards. */
  CreatedAt:
    | Date
    | undefined;
  /** Set to now on create and on every upsert. */
  UpdatedAt:
    | Date
    | undefined;
  /**
   * Indicates whether the asset has been issued on-chain.
   * System-managed: Derived from IssuedAt on upsert. Becomes immutable once true.
   */
  IsIssued: boolean;
}

export interface Assets {
  Records: Asset[];
  /** Pagination offset for fetching the next page of results. */
  Offset?: number | undefined;
}

export interface File {
  /** Display name of the file. */
  Name: string;
  /** Categorization of the file's purpose. */
  Type: FileType;
  /** Google Cloud Storage URI pointing to the file blob (e.g., gs://bucket/path/file.pdf). */
  Reference: string;
}

function createBaseAsset(): Asset {
  return {
    ID: "",
    OrganizationID: "",
    Denom: undefined,
    Type: 0,
    Name: "",
    Description: "",
    Content: "",
    OriginCountryAlpha3: "",
    IssuedAt: undefined,
    IsEnabled: false,
    IsVisible: false,
    IsPromoted: false,
    Files: [],
    Details: undefined,
    CreatedAt: undefined,
    UpdatedAt: undefined,
    IsIssued: false,
  };
}

export const Asset = {
  encode(message: Asset, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.ID !== "") {
      writer.uint32(10).string(message.ID);
    }
    if (message.OrganizationID !== "") {
      writer.uint32(18).string(message.OrganizationID);
    }
    if (message.Denom !== undefined) {
      Denom.encode(message.Denom, writer.uint32(26).fork()).ldelim();
    }
    if (message.Type !== 0) {
      writer.uint32(32).int32(message.Type);
    }
    if (message.Name !== "") {
      writer.uint32(42).string(message.Name);
    }
    if (message.Description !== "") {
      writer.uint32(50).string(message.Description);
    }
    if (message.Content !== "") {
      writer.uint32(58).string(message.Content);
    }
    if (message.OriginCountryAlpha3 !== "") {
      writer.uint32(66).string(message.OriginCountryAlpha3);
    }
    if (message.IssuedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.IssuedAt), writer.uint32(74).fork()).ldelim();
    }
    if (message.IsEnabled !== false) {
      writer.uint32(80).bool(message.IsEnabled);
    }
    if (message.IsVisible !== false) {
      writer.uint32(88).bool(message.IsVisible);
    }
    if (message.IsPromoted !== false) {
      writer.uint32(96).bool(message.IsPromoted);
    }
    for (const v of message.Files) {
      File.encode(v!, writer.uint32(106).fork()).ldelim();
    }
    if (message.Details !== undefined) {
      Struct.encode(Struct.wrap(message.Details), writer.uint32(114).fork()).ldelim();
    }
    if (message.CreatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.CreatedAt), writer.uint32(122).fork()).ldelim();
    }
    if (message.UpdatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.UpdatedAt), writer.uint32(130).fork()).ldelim();
    }
    if (message.IsIssued !== false) {
      writer.uint32(136).bool(message.IsIssued);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Asset {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAsset();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.ID = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.OrganizationID = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.Denom = Denom.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.Type = reader.int32() as any;
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.Name = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.Description = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.Content = reader.string();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.OriginCountryAlpha3 = reader.string();
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.IssuedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 10:
          if (tag !== 80) {
            break;
          }

          message.IsEnabled = reader.bool();
          continue;
        case 11:
          if (tag !== 88) {
            break;
          }

          message.IsVisible = reader.bool();
          continue;
        case 12:
          if (tag !== 96) {
            break;
          }

          message.IsPromoted = reader.bool();
          continue;
        case 13:
          if (tag !== 106) {
            break;
          }

          message.Files.push(File.decode(reader, reader.uint32()));
          continue;
        case 14:
          if (tag !== 114) {
            break;
          }

          message.Details = Struct.unwrap(Struct.decode(reader, reader.uint32()));
          continue;
        case 15:
          if (tag !== 122) {
            break;
          }

          message.CreatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 16:
          if (tag !== 130) {
            break;
          }

          message.UpdatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 17:
          if (tag !== 136) {
            break;
          }

          message.IsIssued = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Asset {
    return {
      ID: isSet(object.ID) ? globalThis.String(object.ID) : "",
      OrganizationID: isSet(object.OrganizationID) ? globalThis.String(object.OrganizationID) : "",
      Denom: isSet(object.Denom) ? Denom.fromJSON(object.Denom) : undefined,
      Type: isSet(object.Type) ? assetTypeFromJSON(object.Type) : 0,
      Name: isSet(object.Name) ? globalThis.String(object.Name) : "",
      Description: isSet(object.Description) ? globalThis.String(object.Description) : "",
      Content: isSet(object.Content) ? globalThis.String(object.Content) : "",
      OriginCountryAlpha3: isSet(object.OriginCountryAlpha3) ? globalThis.String(object.OriginCountryAlpha3) : "",
      IssuedAt: isSet(object.IssuedAt) ? fromJsonTimestamp(object.IssuedAt) : undefined,
      IsEnabled: isSet(object.IsEnabled) ? globalThis.Boolean(object.IsEnabled) : false,
      IsVisible: isSet(object.IsVisible) ? globalThis.Boolean(object.IsVisible) : false,
      IsPromoted: isSet(object.IsPromoted) ? globalThis.Boolean(object.IsPromoted) : false,
      Files: globalThis.Array.isArray(object?.Files) ? object.Files.map((e: any) => File.fromJSON(e)) : [],
      Details: isObject(object.Details) ? object.Details : undefined,
      CreatedAt: isSet(object.CreatedAt) ? fromJsonTimestamp(object.CreatedAt) : undefined,
      UpdatedAt: isSet(object.UpdatedAt) ? fromJsonTimestamp(object.UpdatedAt) : undefined,
      IsIssued: isSet(object.IsIssued) ? globalThis.Boolean(object.IsIssued) : false,
    };
  },

  toJSON(message: Asset): unknown {
    const obj: any = {};
    if (message.ID !== "") {
      obj.ID = message.ID;
    }
    if (message.OrganizationID !== "") {
      obj.OrganizationID = message.OrganizationID;
    }
    if (message.Denom !== undefined) {
      obj.Denom = Denom.toJSON(message.Denom);
    }
    if (message.Type !== 0) {
      obj.Type = assetTypeToJSON(message.Type);
    }
    if (message.Name !== "") {
      obj.Name = message.Name;
    }
    if (message.Description !== "") {
      obj.Description = message.Description;
    }
    if (message.Content !== "") {
      obj.Content = message.Content;
    }
    if (message.OriginCountryAlpha3 !== "") {
      obj.OriginCountryAlpha3 = message.OriginCountryAlpha3;
    }
    if (message.IssuedAt !== undefined) {
      obj.IssuedAt = message.IssuedAt.toISOString();
    }
    if (message.IsEnabled !== false) {
      obj.IsEnabled = message.IsEnabled;
    }
    if (message.IsVisible !== false) {
      obj.IsVisible = message.IsVisible;
    }
    if (message.IsPromoted !== false) {
      obj.IsPromoted = message.IsPromoted;
    }
    if (message.Files?.length) {
      obj.Files = message.Files.map((e) => File.toJSON(e));
    }
    if (message.Details !== undefined) {
      obj.Details = message.Details;
    }
    if (message.CreatedAt !== undefined) {
      obj.CreatedAt = message.CreatedAt.toISOString();
    }
    if (message.UpdatedAt !== undefined) {
      obj.UpdatedAt = message.UpdatedAt.toISOString();
    }
    if (message.IsIssued !== false) {
      obj.IsIssued = message.IsIssued;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Asset>, I>>(base?: I): Asset {
    return Asset.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Asset>, I>>(object: I): Asset {
    const message = createBaseAsset();
    message.ID = object.ID ?? "";
    message.OrganizationID = object.OrganizationID ?? "";
    message.Denom = (object.Denom !== undefined && object.Denom !== null) ? Denom.fromPartial(object.Denom) : undefined;
    message.Type = object.Type ?? 0;
    message.Name = object.Name ?? "";
    message.Description = object.Description ?? "";
    message.Content = object.Content ?? "";
    message.OriginCountryAlpha3 = object.OriginCountryAlpha3 ?? "";
    message.IssuedAt = object.IssuedAt ?? undefined;
    message.IsEnabled = object.IsEnabled ?? false;
    message.IsVisible = object.IsVisible ?? false;
    message.IsPromoted = object.IsPromoted ?? false;
    message.Files = object.Files?.map((e) => File.fromPartial(e)) || [];
    message.Details = object.Details ?? undefined;
    message.CreatedAt = object.CreatedAt ?? undefined;
    message.UpdatedAt = object.UpdatedAt ?? undefined;
    message.IsIssued = object.IsIssued ?? false;
    return message;
  },
};

function createBaseAssets(): Assets {
  return { Records: [], Offset: undefined };
}

export const Assets = {
  encode(message: Assets, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.Records) {
      Asset.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    if (message.Offset !== undefined) {
      writer.uint32(16).int32(message.Offset);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Assets {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAssets();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Records.push(Asset.decode(reader, reader.uint32()));
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.Offset = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Assets {
    return {
      Records: globalThis.Array.isArray(object?.Records) ? object.Records.map((e: any) => Asset.fromJSON(e)) : [],
      Offset: isSet(object.Offset) ? globalThis.Number(object.Offset) : undefined,
    };
  },

  toJSON(message: Assets): unknown {
    const obj: any = {};
    if (message.Records?.length) {
      obj.Records = message.Records.map((e) => Asset.toJSON(e));
    }
    if (message.Offset !== undefined) {
      obj.Offset = Math.round(message.Offset);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Assets>, I>>(base?: I): Assets {
    return Assets.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Assets>, I>>(object: I): Assets {
    const message = createBaseAssets();
    message.Records = object.Records?.map((e) => Asset.fromPartial(e)) || [];
    message.Offset = object.Offset ?? undefined;
    return message;
  },
};

function createBaseFile(): File {
  return { Name: "", Type: 0, Reference: "" };
}

export const File = {
  encode(message: File, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Name !== "") {
      writer.uint32(10).string(message.Name);
    }
    if (message.Type !== 0) {
      writer.uint32(16).int32(message.Type);
    }
    if (message.Reference !== "") {
      writer.uint32(26).string(message.Reference);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): File {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Name = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.Type = reader.int32() as any;
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.Reference = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): File {
    return {
      Name: isSet(object.Name) ? globalThis.String(object.Name) : "",
      Type: isSet(object.Type) ? fileTypeFromJSON(object.Type) : 0,
      Reference: isSet(object.Reference) ? globalThis.String(object.Reference) : "",
    };
  },

  toJSON(message: File): unknown {
    const obj: any = {};
    if (message.Name !== "") {
      obj.Name = message.Name;
    }
    if (message.Type !== 0) {
      obj.Type = fileTypeToJSON(message.Type);
    }
    if (message.Reference !== "") {
      obj.Reference = message.Reference;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<File>, I>>(base?: I): File {
    return File.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<File>, I>>(object: I): File {
    const message = createBaseFile();
    message.Name = object.Name ?? "";
    message.Type = object.Type ?? 0;
    message.Reference = object.Reference ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
