// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: asset-grpc.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import _m0 from "protobufjs/minimal";
import {
  Asset,
  Assets,
  AssetStatus,
  assetStatusFromJSON,
  assetStatusToJSON,
  AssetType,
  assetTypeFromJSON,
  assetTypeToJSON,
  ExtensionType,
  extensionTypeFromJSON,
  extensionTypeToJSON,
  UserAssetList,
  UserAssetLists,
  UserAssetStatus,
  userAssetStatusFromJSON,
  userAssetStatusToJSON,
} from "./asset";
import { Network, networkFromJSON, networkToJSON } from "./sologenic/com-fs-utils-lib/models/metadata/metadata";

export const protobufPackage = "asset";

export interface AssetKey {
  Key: string;
}

export interface AssetQuery {
  Network: Network;
  Offset?:
    | number
    | undefined;
  /** Compliance filter: list assets allowed in these jurisdictions */
  JurisdictionIDs: string[];
  OrganizationID?: string | undefined;
  Status?: AssetStatus | undefined;
  AssetType?:
    | AssetType
    | undefined;
  /** On-chain issuer address (distinct from Denom.Issuer) */
  SmartContractIssuerAddr?: string | undefined;
  Limit?:
    | number
    | undefined;
  /** Asset Extension type filter */
  ExtensionType?:
    | ExtensionType
    | undefined;
  /** Asset Denom properties filter */
  DenomIssuer?: string | undefined;
  DenomSubunit?: string | undefined;
  IsPromoted?: boolean | undefined;
}

export interface UserAssetListKey {
  Key: string;
}

export interface UserAssetListQuery {
  Network: Network;
  Offset?: number | undefined;
  AccountID?: string | undefined;
  Wallet?: string | undefined;
  AssetKey?: string | undefined;
  Status?: UserAssetStatus | undefined;
  Visible?: boolean | undefined;
  OrganizationID?: string | undefined;
}

export interface CountResponse {
  Count: number;
}

function createBaseAssetKey(): AssetKey {
  return { Key: "" };
}

export const AssetKey = {
  encode(message: AssetKey, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Key !== "") {
      writer.uint32(10).string(message.Key);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): AssetKey {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAssetKey();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Key = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AssetKey {
    return { Key: isSet(object.Key) ? globalThis.String(object.Key) : "" };
  },

  toJSON(message: AssetKey): unknown {
    const obj: any = {};
    if (message.Key !== "") {
      obj.Key = message.Key;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AssetKey>, I>>(base?: I): AssetKey {
    return AssetKey.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AssetKey>, I>>(object: I): AssetKey {
    const message = createBaseAssetKey();
    message.Key = object.Key ?? "";
    return message;
  },
};

function createBaseAssetQuery(): AssetQuery {
  return {
    Network: 0,
    Offset: undefined,
    JurisdictionIDs: [],
    OrganizationID: undefined,
    Status: undefined,
    AssetType: undefined,
    SmartContractIssuerAddr: undefined,
    Limit: undefined,
    ExtensionType: undefined,
    DenomIssuer: undefined,
    DenomSubunit: undefined,
    IsPromoted: undefined,
  };
}

export const AssetQuery = {
  encode(message: AssetQuery, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Network !== 0) {
      writer.uint32(8).int32(message.Network);
    }
    if (message.Offset !== undefined) {
      writer.uint32(16).int32(message.Offset);
    }
    for (const v of message.JurisdictionIDs) {
      writer.uint32(26).string(v!);
    }
    if (message.OrganizationID !== undefined) {
      writer.uint32(34).string(message.OrganizationID);
    }
    if (message.Status !== undefined) {
      writer.uint32(40).int32(message.Status);
    }
    if (message.AssetType !== undefined) {
      writer.uint32(48).int32(message.AssetType);
    }
    if (message.SmartContractIssuerAddr !== undefined) {
      writer.uint32(58).string(message.SmartContractIssuerAddr);
    }
    if (message.Limit !== undefined) {
      writer.uint32(64).int32(message.Limit);
    }
    if (message.ExtensionType !== undefined) {
      writer.uint32(72).int32(message.ExtensionType);
    }
    if (message.DenomIssuer !== undefined) {
      writer.uint32(82).string(message.DenomIssuer);
    }
    if (message.DenomSubunit !== undefined) {
      writer.uint32(90).string(message.DenomSubunit);
    }
    if (message.IsPromoted !== undefined) {
      writer.uint32(96).bool(message.IsPromoted);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): AssetQuery {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAssetQuery();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.Network = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.Offset = reader.int32();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.JurisdictionIDs.push(reader.string());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.OrganizationID = reader.string();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.Status = reader.int32() as any;
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.AssetType = reader.int32() as any;
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.SmartContractIssuerAddr = reader.string();
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.Limit = reader.int32();
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.ExtensionType = reader.int32() as any;
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.DenomIssuer = reader.string();
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.DenomSubunit = reader.string();
          continue;
        case 12:
          if (tag !== 96) {
            break;
          }

          message.IsPromoted = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AssetQuery {
    return {
      Network: isSet(object.Network) ? networkFromJSON(object.Network) : 0,
      Offset: isSet(object.Offset) ? globalThis.Number(object.Offset) : undefined,
      JurisdictionIDs: globalThis.Array.isArray(object?.JurisdictionIDs)
        ? object.JurisdictionIDs.map((e: any) => globalThis.String(e))
        : [],
      OrganizationID: isSet(object.OrganizationID) ? globalThis.String(object.OrganizationID) : undefined,
      Status: isSet(object.Status) ? assetStatusFromJSON(object.Status) : undefined,
      AssetType: isSet(object.AssetType) ? assetTypeFromJSON(object.AssetType) : undefined,
      SmartContractIssuerAddr: isSet(object.SmartContractIssuerAddr)
        ? globalThis.String(object.SmartContractIssuerAddr)
        : undefined,
      Limit: isSet(object.Limit) ? globalThis.Number(object.Limit) : undefined,
      ExtensionType: isSet(object.ExtensionType) ? extensionTypeFromJSON(object.ExtensionType) : undefined,
      DenomIssuer: isSet(object.DenomIssuer) ? globalThis.String(object.DenomIssuer) : undefined,
      DenomSubunit: isSet(object.DenomSubunit) ? globalThis.String(object.DenomSubunit) : undefined,
      IsPromoted: isSet(object.IsPromoted) ? globalThis.Boolean(object.IsPromoted) : undefined,
    };
  },

  toJSON(message: AssetQuery): unknown {
    const obj: any = {};
    if (message.Network !== 0) {
      obj.Network = networkToJSON(message.Network);
    }
    if (message.Offset !== undefined) {
      obj.Offset = Math.round(message.Offset);
    }
    if (message.JurisdictionIDs?.length) {
      obj.JurisdictionIDs = message.JurisdictionIDs;
    }
    if (message.OrganizationID !== undefined) {
      obj.OrganizationID = message.OrganizationID;
    }
    if (message.Status !== undefined) {
      obj.Status = assetStatusToJSON(message.Status);
    }
    if (message.AssetType !== undefined) {
      obj.AssetType = assetTypeToJSON(message.AssetType);
    }
    if (message.SmartContractIssuerAddr !== undefined) {
      obj.SmartContractIssuerAddr = message.SmartContractIssuerAddr;
    }
    if (message.Limit !== undefined) {
      obj.Limit = Math.round(message.Limit);
    }
    if (message.ExtensionType !== undefined) {
      obj.ExtensionType = extensionTypeToJSON(message.ExtensionType);
    }
    if (message.DenomIssuer !== undefined) {
      obj.DenomIssuer = message.DenomIssuer;
    }
    if (message.DenomSubunit !== undefined) {
      obj.DenomSubunit = message.DenomSubunit;
    }
    if (message.IsPromoted !== undefined) {
      obj.IsPromoted = message.IsPromoted;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AssetQuery>, I>>(base?: I): AssetQuery {
    return AssetQuery.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AssetQuery>, I>>(object: I): AssetQuery {
    const message = createBaseAssetQuery();
    message.Network = object.Network ?? 0;
    message.Offset = object.Offset ?? undefined;
    message.JurisdictionIDs = object.JurisdictionIDs?.map((e) => e) || [];
    message.OrganizationID = object.OrganizationID ?? undefined;
    message.Status = object.Status ?? undefined;
    message.AssetType = object.AssetType ?? undefined;
    message.SmartContractIssuerAddr = object.SmartContractIssuerAddr ?? undefined;
    message.Limit = object.Limit ?? undefined;
    message.ExtensionType = object.ExtensionType ?? undefined;
    message.DenomIssuer = object.DenomIssuer ?? undefined;
    message.DenomSubunit = object.DenomSubunit ?? undefined;
    message.IsPromoted = object.IsPromoted ?? undefined;
    return message;
  },
};

function createBaseUserAssetListKey(): UserAssetListKey {
  return { Key: "" };
}

export const UserAssetListKey = {
  encode(message: UserAssetListKey, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Key !== "") {
      writer.uint32(10).string(message.Key);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): UserAssetListKey {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserAssetListKey();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Key = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserAssetListKey {
    return { Key: isSet(object.Key) ? globalThis.String(object.Key) : "" };
  },

  toJSON(message: UserAssetListKey): unknown {
    const obj: any = {};
    if (message.Key !== "") {
      obj.Key = message.Key;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserAssetListKey>, I>>(base?: I): UserAssetListKey {
    return UserAssetListKey.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserAssetListKey>, I>>(object: I): UserAssetListKey {
    const message = createBaseUserAssetListKey();
    message.Key = object.Key ?? "";
    return message;
  },
};

function createBaseUserAssetListQuery(): UserAssetListQuery {
  return {
    Network: 0,
    Offset: undefined,
    AccountID: undefined,
    Wallet: undefined,
    AssetKey: undefined,
    Status: undefined,
    Visible: undefined,
    OrganizationID: undefined,
  };
}

export const UserAssetListQuery = {
  encode(message: UserAssetListQuery, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Network !== 0) {
      writer.uint32(8).int32(message.Network);
    }
    if (message.Offset !== undefined) {
      writer.uint32(16).int32(message.Offset);
    }
    if (message.AccountID !== undefined) {
      writer.uint32(26).string(message.AccountID);
    }
    if (message.Wallet !== undefined) {
      writer.uint32(34).string(message.Wallet);
    }
    if (message.AssetKey !== undefined) {
      writer.uint32(42).string(message.AssetKey);
    }
    if (message.Status !== undefined) {
      writer.uint32(48).int32(message.Status);
    }
    if (message.Visible !== undefined) {
      writer.uint32(56).bool(message.Visible);
    }
    if (message.OrganizationID !== undefined) {
      writer.uint32(66).string(message.OrganizationID);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): UserAssetListQuery {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserAssetListQuery();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.Network = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.Offset = reader.int32();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.AccountID = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.Wallet = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.AssetKey = reader.string();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.Status = reader.int32() as any;
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.Visible = reader.bool();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.OrganizationID = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserAssetListQuery {
    return {
      Network: isSet(object.Network) ? networkFromJSON(object.Network) : 0,
      Offset: isSet(object.Offset) ? globalThis.Number(object.Offset) : undefined,
      AccountID: isSet(object.AccountID) ? globalThis.String(object.AccountID) : undefined,
      Wallet: isSet(object.Wallet) ? globalThis.String(object.Wallet) : undefined,
      AssetKey: isSet(object.AssetKey) ? globalThis.String(object.AssetKey) : undefined,
      Status: isSet(object.Status) ? userAssetStatusFromJSON(object.Status) : undefined,
      Visible: isSet(object.Visible) ? globalThis.Boolean(object.Visible) : undefined,
      OrganizationID: isSet(object.OrganizationID) ? globalThis.String(object.OrganizationID) : undefined,
    };
  },

  toJSON(message: UserAssetListQuery): unknown {
    const obj: any = {};
    if (message.Network !== 0) {
      obj.Network = networkToJSON(message.Network);
    }
    if (message.Offset !== undefined) {
      obj.Offset = Math.round(message.Offset);
    }
    if (message.AccountID !== undefined) {
      obj.AccountID = message.AccountID;
    }
    if (message.Wallet !== undefined) {
      obj.Wallet = message.Wallet;
    }
    if (message.AssetKey !== undefined) {
      obj.AssetKey = message.AssetKey;
    }
    if (message.Status !== undefined) {
      obj.Status = userAssetStatusToJSON(message.Status);
    }
    if (message.Visible !== undefined) {
      obj.Visible = message.Visible;
    }
    if (message.OrganizationID !== undefined) {
      obj.OrganizationID = message.OrganizationID;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserAssetListQuery>, I>>(base?: I): UserAssetListQuery {
    return UserAssetListQuery.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserAssetListQuery>, I>>(object: I): UserAssetListQuery {
    const message = createBaseUserAssetListQuery();
    message.Network = object.Network ?? 0;
    message.Offset = object.Offset ?? undefined;
    message.AccountID = object.AccountID ?? undefined;
    message.Wallet = object.Wallet ?? undefined;
    message.AssetKey = object.AssetKey ?? undefined;
    message.Status = object.Status ?? undefined;
    message.Visible = object.Visible ?? undefined;
    message.OrganizationID = object.OrganizationID ?? undefined;
    return message;
  },
};

function createBaseCountResponse(): CountResponse {
  return { Count: 0 };
}

export const CountResponse = {
  encode(message: CountResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Count !== 0) {
      writer.uint32(8).int32(message.Count);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CountResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCountResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.Count = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CountResponse {
    return { Count: isSet(object.Count) ? globalThis.Number(object.Count) : 0 };
  },

  toJSON(message: CountResponse): unknown {
    const obj: any = {};
    if (message.Count !== 0) {
      obj.Count = Math.round(message.Count);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CountResponse>, I>>(base?: I): CountResponse {
    return CountResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CountResponse>, I>>(object: I): CountResponse {
    const message = createBaseCountResponse();
    message.Count = object.Count ?? 0;
    return message;
  },
};

export type AssetListServiceService = typeof AssetListServiceService;
export const AssetListServiceService = {
  /** Upsert on Asset */
  upsertAsset: {
    path: "/asset.AssetListService/UpsertAsset",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: Asset) => Buffer.from(Asset.encode(value).finish()),
    requestDeserialize: (value: Buffer) => Asset.decode(value),
    responseSerialize: (value: AssetKey) => Buffer.from(AssetKey.encode(value).finish()),
    responseDeserialize: (value: Buffer) => AssetKey.decode(value),
  },
  /** Get Asset by Key */
  getAsset: {
    path: "/asset.AssetListService/GetAsset",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: AssetKey) => Buffer.from(AssetKey.encode(value).finish()),
    requestDeserialize: (value: Buffer) => AssetKey.decode(value),
    responseSerialize: (value: Asset) => Buffer.from(Asset.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Asset.decode(value),
  },
  /** Get all Assets for a given filter */
  getAssets: {
    path: "/asset.AssetListService/GetAssets",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: AssetQuery) => Buffer.from(AssetQuery.encode(value).finish()),
    requestDeserialize: (value: Buffer) => AssetQuery.decode(value),
    responseSerialize: (value: Assets) => Buffer.from(Assets.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Assets.decode(value),
  },
  /** Upsert on UserAssetList */
  upsertUserAssetList: {
    path: "/asset.AssetListService/UpsertUserAssetList",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UserAssetList) => Buffer.from(UserAssetList.encode(value).finish()),
    requestDeserialize: (value: Buffer) => UserAssetList.decode(value),
    responseSerialize: (value: UserAssetListKey) => Buffer.from(UserAssetListKey.encode(value).finish()),
    responseDeserialize: (value: Buffer) => UserAssetListKey.decode(value),
  },
  /** Get UserAssetList by Key */
  getUserAssetList: {
    path: "/asset.AssetListService/GetUserAssetList",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UserAssetListKey) => Buffer.from(UserAssetListKey.encode(value).finish()),
    requestDeserialize: (value: Buffer) => UserAssetListKey.decode(value),
    responseSerialize: (value: UserAssetList) => Buffer.from(UserAssetList.encode(value).finish()),
    responseDeserialize: (value: Buffer) => UserAssetList.decode(value),
  },
  /** Get all UserAssetList for a given filter */
  getUserAssetLists: {
    path: "/asset.AssetListService/GetUserAssetLists",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UserAssetListQuery) => Buffer.from(UserAssetListQuery.encode(value).finish()),
    requestDeserialize: (value: Buffer) => UserAssetListQuery.decode(value),
    responseSerialize: (value: UserAssetLists) => Buffer.from(UserAssetLists.encode(value).finish()),
    responseDeserialize: (value: Buffer) => UserAssetLists.decode(value),
  },
  /** Count all Assets for a given filter */
  countAssets: {
    path: "/asset.AssetListService/CountAssets",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: AssetQuery) => Buffer.from(AssetQuery.encode(value).finish()),
    requestDeserialize: (value: Buffer) => AssetQuery.decode(value),
    responseSerialize: (value: CountResponse) => Buffer.from(CountResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => CountResponse.decode(value),
  },
} as const;

export interface AssetListServiceServer extends UntypedServiceImplementation {
  /** Upsert on Asset */
  upsertAsset: handleUnaryCall<Asset, AssetKey>;
  /** Get Asset by Key */
  getAsset: handleUnaryCall<AssetKey, Asset>;
  /** Get all Assets for a given filter */
  getAssets: handleUnaryCall<AssetQuery, Assets>;
  /** Upsert on UserAssetList */
  upsertUserAssetList: handleUnaryCall<UserAssetList, UserAssetListKey>;
  /** Get UserAssetList by Key */
  getUserAssetList: handleUnaryCall<UserAssetListKey, UserAssetList>;
  /** Get all UserAssetList for a given filter */
  getUserAssetLists: handleUnaryCall<UserAssetListQuery, UserAssetLists>;
  /** Count all Assets for a given filter */
  countAssets: handleUnaryCall<AssetQuery, CountResponse>;
}

export interface AssetListServiceClient extends Client {
  /** Upsert on Asset */
  upsertAsset(request: Asset, callback: (error: ServiceError | null, response: AssetKey) => void): ClientUnaryCall;
  upsertAsset(
    request: Asset,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: AssetKey) => void,
  ): ClientUnaryCall;
  upsertAsset(
    request: Asset,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: AssetKey) => void,
  ): ClientUnaryCall;
  /** Get Asset by Key */
  getAsset(request: AssetKey, callback: (error: ServiceError | null, response: Asset) => void): ClientUnaryCall;
  getAsset(
    request: AssetKey,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Asset) => void,
  ): ClientUnaryCall;
  getAsset(
    request: AssetKey,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Asset) => void,
  ): ClientUnaryCall;
  /** Get all Assets for a given filter */
  getAssets(request: AssetQuery, callback: (error: ServiceError | null, response: Assets) => void): ClientUnaryCall;
  getAssets(
    request: AssetQuery,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Assets) => void,
  ): ClientUnaryCall;
  getAssets(
    request: AssetQuery,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Assets) => void,
  ): ClientUnaryCall;
  /** Upsert on UserAssetList */
  upsertUserAssetList(
    request: UserAssetList,
    callback: (error: ServiceError | null, response: UserAssetListKey) => void,
  ): ClientUnaryCall;
  upsertUserAssetList(
    request: UserAssetList,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UserAssetListKey) => void,
  ): ClientUnaryCall;
  upsertUserAssetList(
    request: UserAssetList,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UserAssetListKey) => void,
  ): ClientUnaryCall;
  /** Get UserAssetList by Key */
  getUserAssetList(
    request: UserAssetListKey,
    callback: (error: ServiceError | null, response: UserAssetList) => void,
  ): ClientUnaryCall;
  getUserAssetList(
    request: UserAssetListKey,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UserAssetList) => void,
  ): ClientUnaryCall;
  getUserAssetList(
    request: UserAssetListKey,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UserAssetList) => void,
  ): ClientUnaryCall;
  /** Get all UserAssetList for a given filter */
  getUserAssetLists(
    request: UserAssetListQuery,
    callback: (error: ServiceError | null, response: UserAssetLists) => void,
  ): ClientUnaryCall;
  getUserAssetLists(
    request: UserAssetListQuery,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UserAssetLists) => void,
  ): ClientUnaryCall;
  getUserAssetLists(
    request: UserAssetListQuery,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UserAssetLists) => void,
  ): ClientUnaryCall;
  /** Count all Assets for a given filter */
  countAssets(
    request: AssetQuery,
    callback: (error: ServiceError | null, response: CountResponse) => void,
  ): ClientUnaryCall;
  countAssets(
    request: AssetQuery,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CountResponse) => void,
  ): ClientUnaryCall;
  countAssets(
    request: AssetQuery,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CountResponse) => void,
  ): ClientUnaryCall;
}

export const AssetListServiceClient = makeGenericClientConstructor(
  AssetListServiceService,
  "asset.AssetListService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): AssetListServiceClient;
  service: typeof AssetListServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
