syntax = "proto3";

package asset;

import "asset.proto";

option go_package = "github.com/sologenic/com-fs-asset-model;asset";

service AssetListService { // TODO: Better name
    // Upsert on Asset
    rpc UpsertAsset(Asset) returns (AssetKey);
    // Get Asset by Key 
    rpc GetAsset(AssetKey) returns (Asset);
    // Get all Assets for a given filter
    rpc GetAssets(AssetQuery) returns (Assets);
    // Count all Assets for a given filter
    rpc CountAssets(AssetQuery) returns (CountResponse);
}

message AssetKey {
    string Key = 1;
}

message AssetQuery {
    optional int32 Offset = 1;
    optional string OrganizationID = 2;
    optional string ID = 3;
    optional AssetType Type = 4;
    optional int32 Limit = 5;
    optional bool IsIssued = 6; // IssuedAt != nil
    optional bool IsEnabled = 7;
    optional bool IsVisible = 8;
    optional bool IsPromoted = 9;
}

message CountResponse {
    int32 Count = 1;
}