// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: asset.proto

package asset

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetStatus int32

const (
	AssetStatus_ASSET_STATUS_DO_NOT_USE AssetStatus = 0
	AssetStatus_DO_NOT_LIST             AssetStatus = 1 // Owner only
	AssetStatus_REQUEST_LISTING         AssetStatus = 2 // Owner only
	AssetStatus_LISTED                  AssetStatus = 3 // Super admin only
	AssetStatus_SUPER_ADMIN_DO_NOT_LIST AssetStatus = 4 // Super admin only
)

// Enum value maps for AssetStatus.
var (
	AssetStatus_name = map[int32]string{
		0: "ASSET_STATUS_DO_NOT_USE",
		1: "DO_NOT_LIST",
		2: "REQUEST_LISTING",
		3: "LISTED",
		4: "SUPER_ADMIN_DO_NOT_LIST",
	}
	AssetStatus_value = map[string]int32{
		"ASSET_STATUS_DO_NOT_USE": 0,
		"DO_NOT_LIST":             1,
		"REQUEST_LISTING":         2,
		"LISTED":                  3,
		"SUPER_ADMIN_DO_NOT_LIST": 4,
	}
)

func (x AssetStatus) Enum() *AssetStatus {
	p := new(AssetStatus)
	*p = x
	return p
}

func (x AssetStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_asset_proto_enumTypes[0].Descriptor()
}

func (AssetStatus) Type() protoreflect.EnumType {
	return &file_asset_proto_enumTypes[0]
}

func (x AssetStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetStatus.Descriptor instead.
func (AssetStatus) EnumDescriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{0}
}

type Reason int32

const (
	Reason_REASON_DO_NOT_USE Reason = 0
	Reason_DUPLICATE         Reason = 1
	Reason_UNWANTED_ASSET    Reason = 2
	Reason_UNSTABLE_ASSET    Reason = 3
)

// Enum value maps for Reason.
var (
	Reason_name = map[int32]string{
		0: "REASON_DO_NOT_USE",
		1: "DUPLICATE",
		2: "UNWANTED_ASSET",
		3: "UNSTABLE_ASSET",
	}
	Reason_value = map[string]int32{
		"REASON_DO_NOT_USE": 0,
		"DUPLICATE":         1,
		"UNWANTED_ASSET":    2,
		"UNSTABLE_ASSET":    3,
	}
)

func (x Reason) Enum() *Reason {
	p := new(Reason)
	*p = x
	return p
}

func (x Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_asset_proto_enumTypes[1].Descriptor()
}

func (Reason) Type() protoreflect.EnumType {
	return &file_asset_proto_enumTypes[1]
}

func (x Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Reason.Descriptor instead.
func (Reason) EnumDescriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{1}
}

type AssetType int32

const (
	AssetType_ASSET_TYPE_DO_NOT_USE AssetType = 0
	AssetType_STOCK                 AssetType = 1
	AssetType_FUTURE                AssetType = 2 // Will be implemented in the future
	AssetType_OPTION                AssetType = 3 // Will be implemented in the future
)

// Enum value maps for AssetType.
var (
	AssetType_name = map[int32]string{
		0: "ASSET_TYPE_DO_NOT_USE",
		1: "STOCK",
		2: "FUTURE",
		3: "OPTION",
	}
	AssetType_value = map[string]int32{
		"ASSET_TYPE_DO_NOT_USE": 0,
		"STOCK":                 1,
		"FUTURE":                2,
		"OPTION":                3,
	}
)

func (x AssetType) Enum() *AssetType {
	p := new(AssetType)
	*p = x
	return p
}

func (x AssetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetType) Descriptor() protoreflect.EnumDescriptor {
	return file_asset_proto_enumTypes[2].Descriptor()
}

func (AssetType) Type() protoreflect.EnumType {
	return &file_asset_proto_enumTypes[2]
}

func (x AssetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetType.Descriptor instead.
func (AssetType) EnumDescriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{2}
}

type UserAssetStatus int32

const (
	UserAssetStatus_USER_ASSET_STATUS_DO_NOT_USE UserAssetStatus = 0
	UserAssetStatus_NOT_WHITELISTED              UserAssetStatus = 1
	UserAssetStatus_WHITELISTING_REQUESTED       UserAssetStatus = 2
	UserAssetStatus_WHITELISTED                  UserAssetStatus = 3
)

// Enum value maps for UserAssetStatus.
var (
	UserAssetStatus_name = map[int32]string{
		0: "USER_ASSET_STATUS_DO_NOT_USE",
		1: "NOT_WHITELISTED",
		2: "WHITELISTING_REQUESTED",
		3: "WHITELISTED",
	}
	UserAssetStatus_value = map[string]int32{
		"USER_ASSET_STATUS_DO_NOT_USE": 0,
		"NOT_WHITELISTED":              1,
		"WHITELISTING_REQUESTED":       2,
		"WHITELISTED":                  3,
	}
)

func (x UserAssetStatus) Enum() *UserAssetStatus {
	p := new(UserAssetStatus)
	*p = x
	return p
}

func (x UserAssetStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserAssetStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_asset_proto_enumTypes[3].Descriptor()
}

func (UserAssetStatus) Type() protoreflect.EnumType {
	return &file_asset_proto_enumTypes[3]
}

func (x UserAssetStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserAssetStatus.Descriptor instead.
func (UserAssetStatus) EnumDescriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{3}
}

type UserJurisdictionStatus int32

const (
	UserJurisdictionStatus_USER_JURISDICTION_STATUS_DO_NOT_USE UserJurisdictionStatus = 0
	UserJurisdictionStatus_ALLOWED                             UserJurisdictionStatus = 1
	UserJurisdictionStatus_NOT_ALLOWED                         UserJurisdictionStatus = 2
)

// Enum value maps for UserJurisdictionStatus.
var (
	UserJurisdictionStatus_name = map[int32]string{
		0: "USER_JURISDICTION_STATUS_DO_NOT_USE",
		1: "ALLOWED",
		2: "NOT_ALLOWED",
	}
	UserJurisdictionStatus_value = map[string]int32{
		"USER_JURISDICTION_STATUS_DO_NOT_USE": 0,
		"ALLOWED":                             1,
		"NOT_ALLOWED":                         2,
	}
)

func (x UserJurisdictionStatus) Enum() *UserJurisdictionStatus {
	p := new(UserJurisdictionStatus)
	*p = x
	return p
}

func (x UserJurisdictionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserJurisdictionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_asset_proto_enumTypes[4].Descriptor()
}

func (UserJurisdictionStatus) Type() protoreflect.EnumType {
	return &file_asset_proto_enumTypes[4]
}

func (x UserJurisdictionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserJurisdictionStatus.Descriptor instead.
func (UserJurisdictionStatus) EnumDescriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{4}
}

// Base structure for an asset
type Asset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=Owner,proto3" json:"Owner,omitempty"` // External entity (broket) that owns this asset, e.g. issuer
	Status        AssetStatus            `protobuf:"varint,3,opt,name=Status,proto3,enum=asset.AssetStatus" json:"Status,omitempty"`
	Reason        Reason                 `protobuf:"varint,4,opt,name=Reason,proto3,enum=asset.Reason" json:"Reason,omitempty"`
	Jurisdictions []string               `protobuf:"bytes,5,rep,name=Jurisdictions,proto3" json:"Jurisdictions,omitempty"` // list of jurisdictions where this asset is allowed to be traded
	Network       string                 `protobuf:"bytes,6,opt,name=Network,proto3" json:"Network,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	Type          AssetType              `protobuf:"varint,9,opt,name=Type,proto3,enum=asset.AssetType" json:"Type,omitempty"`
	// Asset can have only one of the following properties
	//
	// Types that are assignable to Properties:
	//
	//	*Asset_StockProperties
	Properties isAsset_Properties `protobuf_oneof:"Properties"`
}

func (x *Asset) Reset() {
	*x = Asset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asset_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{0}
}

func (x *Asset) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Asset) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Asset) GetStatus() AssetStatus {
	if x != nil {
		return x.Status
	}
	return AssetStatus_ASSET_STATUS_DO_NOT_USE
}

func (x *Asset) GetReason() Reason {
	if x != nil {
		return x.Reason
	}
	return Reason_REASON_DO_NOT_USE
}

func (x *Asset) GetJurisdictions() []string {
	if x != nil {
		return x.Jurisdictions
	}
	return nil
}

func (x *Asset) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Asset) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Asset) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Asset) GetType() AssetType {
	if x != nil {
		return x.Type
	}
	return AssetType_ASSET_TYPE_DO_NOT_USE
}

func (m *Asset) GetProperties() isAsset_Properties {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (x *Asset) GetStockProperties() *StockProperties {
	if x, ok := x.GetProperties().(*Asset_StockProperties); ok {
		return x.StockProperties
	}
	return nil
}

type isAsset_Properties interface {
	isAsset_Properties()
}

type Asset_StockProperties struct {
	StockProperties *StockProperties `protobuf:"bytes,10,opt,name=StockProperties,proto3,oneof"` // Add more properties here
}

func (*Asset_StockProperties) isAsset_Properties() {}

type AssetID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *AssetID) Reset() {
	*x = AssetID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asset_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssetID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetID) ProtoMessage() {}

func (x *AssetID) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetID.ProtoReflect.Descriptor instead.
func (*AssetID) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{1}
}

func (x *AssetID) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type Assets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Assets []*Asset `protobuf:"bytes,1,rep,name=Assets,proto3" json:"Assets,omitempty"`
}

func (x *Assets) Reset() {
	*x = Assets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asset_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Assets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assets) ProtoMessage() {}

func (x *Assets) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assets.ProtoReflect.Descriptor instead.
func (*Assets) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{2}
}

func (x *Assets) GetAssets() []*Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

type StockProperties struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol               string `protobuf:"bytes,1,opt,name=Symbol,proto3" json:"Symbol,omitempty"` // currency-issuer
	Currency             string `protobuf:"bytes,2,opt,name=Currency,proto3" json:"Currency,omitempty"`
	Version              string `protobuf:"bytes,3,opt,name=Version,proto3" json:"Version,omitempty"`
	Precision            int32  `protobuf:"varint,4,opt,name=Precision,proto3" json:"Precision,omitempty"`
	Name                 string `protobuf:"bytes,5,opt,name=Name,proto3" json:"Name,omitempty"`
	ExchangeTickerSymbol string `protobuf:"bytes,6,opt,name=ExchangeTickerSymbol,proto3" json:"ExchangeTickerSymbol,omitempty"`
	Exchange             string `protobuf:"bytes,7,opt,name=Exchange,proto3" json:"Exchange,omitempty"`
	Description          string `protobuf:"bytes,8,opt,name=Description,proto3" json:"Description,omitempty"`
	Listed               bool   `protobuf:"varint,9,opt,name=Listed,proto3" json:"Listed,omitempty"` // Only 1 version of the asset can be True at a time
}

func (x *StockProperties) Reset() {
	*x = StockProperties{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asset_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockProperties) ProtoMessage() {}

func (x *StockProperties) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockProperties.ProtoReflect.Descriptor instead.
func (*StockProperties) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{3}
}

func (x *StockProperties) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *StockProperties) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *StockProperties) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StockProperties) GetPrecision() int32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *StockProperties) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StockProperties) GetExchangeTickerSymbol() string {
	if x != nil {
		return x.ExchangeTickerSymbol
	}
	return ""
}

func (x *StockProperties) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *StockProperties) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StockProperties) GetListed() bool {
	if x != nil {
		return x.Listed
	}
	return false
}

type UserAssetList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"` // UUID
	UserID    string                 `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Wallet    string                 `protobuf:"bytes,3,opt,name=Wallet,proto3" json:"Wallet,omitempty"`
	AssetID   string                 `protobuf:"bytes,4,opt,name=AssetID,proto3" json:"AssetID,omitempty"` // UUID of the asset
	Status    UserAssetStatus        `protobuf:"varint,5,opt,name=Status,proto3,enum=asset.UserAssetStatus" json:"Status,omitempty"`
	Network   string                 `protobuf:"bytes,6,opt,name=Network,proto3" json:"Network,omitempty"`
	Visible   bool                   `protobuf:"varint,7,opt,name=Visible,proto3" json:"Visible,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
}

func (x *UserAssetList) Reset() {
	*x = UserAssetList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asset_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAssetList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAssetList) ProtoMessage() {}

func (x *UserAssetList) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAssetList.ProtoReflect.Descriptor instead.
func (*UserAssetList) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{4}
}

func (x *UserAssetList) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UserAssetList) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UserAssetList) GetWallet() string {
	if x != nil {
		return x.Wallet
	}
	return ""
}

func (x *UserAssetList) GetAssetID() string {
	if x != nil {
		return x.AssetID
	}
	return ""
}

func (x *UserAssetList) GetStatus() UserAssetStatus {
	if x != nil {
		return x.Status
	}
	return UserAssetStatus_USER_ASSET_STATUS_DO_NOT_USE
}

func (x *UserAssetList) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *UserAssetList) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

func (x *UserAssetList) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserAssetList) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UserAssetListID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *UserAssetListID) Reset() {
	*x = UserAssetListID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asset_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAssetListID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAssetListID) ProtoMessage() {}

func (x *UserAssetListID) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAssetListID.ProtoReflect.Descriptor instead.
func (*UserAssetListID) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{5}
}

func (x *UserAssetListID) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type UserAssetLists struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserAssetLists []*UserAssetList `protobuf:"bytes,1,rep,name=UserAssetLists,proto3" json:"UserAssetLists,omitempty"`
}

func (x *UserAssetLists) Reset() {
	*x = UserAssetLists{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asset_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAssetLists) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAssetLists) ProtoMessage() {}

func (x *UserAssetLists) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAssetLists.ProtoReflect.Descriptor instead.
func (*UserAssetLists) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{6}
}

func (x *UserAssetLists) GetUserAssetLists() []*UserAssetList {
	if x != nil {
		return x.UserAssetLists
	}
	return nil
}

type Jurisdiction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID          string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`       // UUID
	Owner       string                 `protobuf:"bytes,2,opt,name=Owner,proto3" json:"Owner,omitempty"` // Organization's owner
	Name        string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Description string                 `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	ExternalID  string                 `protobuf:"bytes,5,opt,name=ExternalID,proto3" json:"ExternalID,omitempty"`
	Network     string                 `protobuf:"bytes,6,opt,name=Network,proto3" json:"Network,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
}

func (x *Jurisdiction) Reset() {
	*x = Jurisdiction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asset_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Jurisdiction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jurisdiction) ProtoMessage() {}

func (x *Jurisdiction) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jurisdiction.ProtoReflect.Descriptor instead.
func (*Jurisdiction) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{7}
}

func (x *Jurisdiction) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Jurisdiction) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Jurisdiction) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Jurisdiction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Jurisdiction) GetExternalID() string {
	if x != nil {
		return x.ExternalID
	}
	return ""
}

func (x *Jurisdiction) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Jurisdiction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Jurisdiction) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type JurisdictionID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *JurisdictionID) Reset() {
	*x = JurisdictionID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asset_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JurisdictionID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JurisdictionID) ProtoMessage() {}

func (x *JurisdictionID) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JurisdictionID.ProtoReflect.Descriptor instead.
func (*JurisdictionID) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{8}
}

func (x *JurisdictionID) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type Jurisdictions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jurisdictions []*Jurisdiction `protobuf:"bytes,1,rep,name=Jurisdictions,proto3" json:"Jurisdictions,omitempty"`
}

func (x *Jurisdictions) Reset() {
	*x = Jurisdictions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asset_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Jurisdictions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jurisdictions) ProtoMessage() {}

func (x *Jurisdictions) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jurisdictions.ProtoReflect.Descriptor instead.
func (*Jurisdictions) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{9}
}

func (x *Jurisdictions) GetJurisdictions() []*Jurisdiction {
	if x != nil {
		return x.Jurisdictions
	}
	return nil
}

type UserJurisdiction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"` // UUID
	UserID         string                 `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Wallet         string                 `protobuf:"bytes,3,opt,name=Wallet,proto3" json:"Wallet,omitempty"`
	JurisdictionID string                 `protobuf:"bytes,4,opt,name=JurisdictionID,proto3" json:"JurisdictionID,omitempty"`                    // Jurisdiction UUID
	Status         UserJurisdictionStatus `protobuf:"varint,5,opt,name=Status,proto3,enum=asset.UserJurisdictionStatus" json:"Status,omitempty"` // Allowed or Not allowed
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	Network        string                 `protobuf:"bytes,8,opt,name=Network,proto3" json:"Network,omitempty"`
}

func (x *UserJurisdiction) Reset() {
	*x = UserJurisdiction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asset_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserJurisdiction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserJurisdiction) ProtoMessage() {}

func (x *UserJurisdiction) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserJurisdiction.ProtoReflect.Descriptor instead.
func (*UserJurisdiction) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{10}
}

func (x *UserJurisdiction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserJurisdiction) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UserJurisdiction) GetWallet() string {
	if x != nil {
		return x.Wallet
	}
	return ""
}

func (x *UserJurisdiction) GetJurisdictionID() string {
	if x != nil {
		return x.JurisdictionID
	}
	return ""
}

func (x *UserJurisdiction) GetStatus() UserJurisdictionStatus {
	if x != nil {
		return x.Status
	}
	return UserJurisdictionStatus_USER_JURISDICTION_STATUS_DO_NOT_USE
}

func (x *UserJurisdiction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserJurisdiction) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UserJurisdiction) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

type UserJurisdictionID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *UserJurisdictionID) Reset() {
	*x = UserJurisdictionID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asset_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserJurisdictionID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserJurisdictionID) ProtoMessage() {}

func (x *UserJurisdictionID) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserJurisdictionID.ProtoReflect.Descriptor instead.
func (*UserJurisdictionID) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{11}
}

func (x *UserJurisdictionID) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type UserJurisdictions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserJurisdictions []*UserJurisdiction `protobuf:"bytes,1,rep,name=UserJurisdictions,proto3" json:"UserJurisdictions,omitempty"`
}

func (x *UserJurisdictions) Reset() {
	*x = UserJurisdictions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asset_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserJurisdictions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserJurisdictions) ProtoMessage() {}

func (x *UserJurisdictions) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserJurisdictions.ProtoReflect.Descriptor instead.
func (*UserJurisdictions) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{12}
}

func (x *UserJurisdictions) GetUserJurisdictions() []*UserJurisdiction {
	if x != nil {
		return x.UserJurisdictions
	}
	return nil
}

var File_asset_proto protoreflect.FileDescriptor

var file_asset_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x61, 0x73, 0x73, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61,
	0x73, 0x73, 0x65, 0x74, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xac, 0x03, 0x0a, 0x05, 0x41, 0x73, 0x73, 0x65, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12,
	0x14, 0x0a, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x2e, 0x41, 0x73,
	0x73, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x25, 0x0a, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0d, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x2e, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x52, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x4a, 0x75, 0x72, 0x69,
	0x73, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0d, 0x4a, 0x75, 0x72, 0x69, 0x73, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x38, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x24, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x42, 0x0a, 0x0f, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x70, 0x65,
	0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x73,
	0x73, 0x65, 0x74, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x69, 0x65, 0x73, 0x48, 0x00, 0x52, 0x0f, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x70,
	0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x42, 0x0c, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x69, 0x65, 0x73, 0x22, 0x19, 0x0a, 0x07, 0x41, 0x73, 0x73, 0x65, 0x74, 0x49, 0x44, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22,
	0x2e, 0x0a, 0x06, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x12, 0x24, 0x0a, 0x06, 0x41, 0x73, 0x73,
	0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x06, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x22,
	0x9b, 0x02, 0x0a, 0x0f, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x69, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x43,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x50, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x32, 0x0a, 0x14, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x72, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x14, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x72, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x78, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x45, 0x78, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x64, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x64, 0x22, 0xc1, 0x02,
	0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x41, 0x73, 0x73, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12,
	0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x57, 0x61, 0x6c, 0x6c, 0x65,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x41, 0x73, 0x73, 0x65, 0x74, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x41, 0x73, 0x73, 0x65, 0x74, 0x49, 0x44, 0x12, 0x2e, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x41, 0x73, 0x73, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x56, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x12, 0x38, 0x0a,
	0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x22, 0x21, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x41, 0x73, 0x73, 0x65, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x44, 0x22, 0x4e, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x41, 0x73, 0x73, 0x65,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x73, 0x12, 0x3c, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x41, 0x73,
	0x73, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x41, 0x73, 0x73, 0x65, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x73, 0x22, 0x98, 0x02, 0x0a, 0x0c, 0x4a, 0x75, 0x72, 0x69, 0x73, 0x64, 0x69,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x44, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49,
	0x44, 0x12, 0x18, 0x0a, 0x07, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x38, 0x0a, 0x09, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22,
	0x20, 0x0a, 0x0e, 0x4a, 0x75, 0x72, 0x69, 0x73, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x44, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x44, 0x22, 0x4a, 0x0a, 0x0d, 0x4a, 0x75, 0x72, 0x69, 0x73, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x39, 0x0a, 0x0d, 0x4a, 0x75, 0x72, 0x69, 0x73, 0x64, 0x69, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x2e, 0x4a, 0x75, 0x72, 0x69, 0x73, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d,
	0x4a, 0x75, 0x72, 0x69, 0x73, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xbf, 0x02,
	0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x4a, 0x75, 0x72, 0x69, 0x73, 0x64, 0x69, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x57, 0x61,
	0x6c, 0x6c, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x57, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x4a, 0x75, 0x72, 0x69, 0x73, 0x64, 0x69, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x4a, 0x75, 0x72, 0x69,
	0x73, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x35, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4a, 0x75, 0x72, 0x69, 0x73, 0x64, 0x69, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x38, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x22,
	0x24, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x4a, 0x75, 0x72, 0x69, 0x73, 0x64, 0x69, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x5a, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x4a, 0x75, 0x72,
	0x69, 0x73, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x45, 0x0a, 0x11, 0x55, 0x73,
	0x65, 0x72, 0x4a, 0x75, 0x72, 0x69, 0x73, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x4a, 0x75, 0x72, 0x69, 0x73, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x11,
	0x55, 0x73, 0x65, 0x72, 0x4a, 0x75, 0x72, 0x69, 0x73, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2a, 0x79, 0x0a, 0x0b, 0x41, 0x73, 0x73, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1b, 0x0a, 0x17, 0x41, 0x53, 0x53, 0x45, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x44, 0x4f, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x55, 0x53, 0x45, 0x10, 0x00, 0x12, 0x0f, 0x0a,
	0x0b, 0x44, 0x4f, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x10, 0x01, 0x12, 0x13,
	0x0a, 0x0f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x49, 0x4e,
	0x47, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x49, 0x53, 0x54, 0x45, 0x44, 0x10, 0x03, 0x12,
	0x1b, 0x0a, 0x17, 0x53, 0x55, 0x50, 0x45, 0x52, 0x5f, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x5f, 0x44,
	0x4f, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x10, 0x04, 0x2a, 0x56, 0x0a, 0x06,
	0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e,
	0x5f, 0x44, 0x4f, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x55, 0x53, 0x45, 0x10, 0x00, 0x12, 0x0d, 0x0a,
	0x09, 0x44, 0x55, 0x50, 0x4c, 0x49, 0x43, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e,
	0x55, 0x4e, 0x57, 0x41, 0x4e, 0x54, 0x45, 0x44, 0x5f, 0x41, 0x53, 0x53, 0x45, 0x54, 0x10, 0x02,
	0x12, 0x12, 0x0a, 0x0e, 0x55, 0x4e, 0x53, 0x54, 0x41, 0x42, 0x4c, 0x45, 0x5f, 0x41, 0x53, 0x53,
	0x45, 0x54, 0x10, 0x03, 0x2a, 0x49, 0x0a, 0x09, 0x41, 0x73, 0x73, 0x65, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x19, 0x0a, 0x15, 0x41, 0x53, 0x53, 0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x44, 0x4f, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x55, 0x53, 0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05,
	0x53, 0x54, 0x4f, 0x43, 0x4b, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x55, 0x54, 0x55, 0x52,
	0x45, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x03, 0x2a,
	0x75, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x41, 0x73, 0x73, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x20, 0x0a, 0x1c, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x41, 0x53, 0x53, 0x45, 0x54,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x44, 0x4f, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x55,
	0x53, 0x45, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x4e, 0x4f, 0x54, 0x5f, 0x57, 0x48, 0x49, 0x54,
	0x45, 0x4c, 0x49, 0x53, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x1a, 0x0a, 0x16, 0x57, 0x48, 0x49,
	0x54, 0x45, 0x4c, 0x49, 0x53, 0x54, 0x49, 0x4e, 0x47, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53,
	0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x57, 0x48, 0x49, 0x54, 0x45, 0x4c, 0x49,
	0x53, 0x54, 0x45, 0x44, 0x10, 0x03, 0x2a, 0x5f, 0x0a, 0x16, 0x55, 0x73, 0x65, 0x72, 0x4a, 0x75,
	0x72, 0x69, 0x73, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x27, 0x0a, 0x23, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x4a, 0x55, 0x52, 0x49, 0x53, 0x44, 0x49,
	0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x44, 0x4f, 0x5f,
	0x4e, 0x4f, 0x54, 0x5f, 0x55, 0x53, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x4c, 0x4c,
	0x4f, 0x57, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x4e, 0x4f, 0x54, 0x5f, 0x41, 0x4c,
	0x4c, 0x4f, 0x57, 0x45, 0x44, 0x10, 0x02, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x6c, 0x6f, 0x67, 0x65, 0x6e, 0x69, 0x63, 0x2f,
	0x63, 0x6f, 0x6d, 0x2d, 0x66, 0x73, 0x2d, 0x61, 0x73, 0x73, 0x65, 0x74, 0x2d, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x3b, 0x61, 0x73, 0x73, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_asset_proto_rawDescOnce sync.Once
	file_asset_proto_rawDescData = file_asset_proto_rawDesc
)

func file_asset_proto_rawDescGZIP() []byte {
	file_asset_proto_rawDescOnce.Do(func() {
		file_asset_proto_rawDescData = protoimpl.X.CompressGZIP(file_asset_proto_rawDescData)
	})
	return file_asset_proto_rawDescData
}

var file_asset_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_asset_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_asset_proto_goTypes = []interface{}{
	(AssetStatus)(0),              // 0: asset.AssetStatus
	(Reason)(0),                   // 1: asset.Reason
	(AssetType)(0),                // 2: asset.AssetType
	(UserAssetStatus)(0),          // 3: asset.UserAssetStatus
	(UserJurisdictionStatus)(0),   // 4: asset.UserJurisdictionStatus
	(*Asset)(nil),                 // 5: asset.Asset
	(*AssetID)(nil),               // 6: asset.AssetID
	(*Assets)(nil),                // 7: asset.Assets
	(*StockProperties)(nil),       // 8: asset.StockProperties
	(*UserAssetList)(nil),         // 9: asset.UserAssetList
	(*UserAssetListID)(nil),       // 10: asset.UserAssetListID
	(*UserAssetLists)(nil),        // 11: asset.UserAssetLists
	(*Jurisdiction)(nil),          // 12: asset.Jurisdiction
	(*JurisdictionID)(nil),        // 13: asset.JurisdictionID
	(*Jurisdictions)(nil),         // 14: asset.Jurisdictions
	(*UserJurisdiction)(nil),      // 15: asset.UserJurisdiction
	(*UserJurisdictionID)(nil),    // 16: asset.UserJurisdictionID
	(*UserJurisdictions)(nil),     // 17: asset.UserJurisdictions
	(*timestamppb.Timestamp)(nil), // 18: google.protobuf.Timestamp
}
var file_asset_proto_depIdxs = []int32{
	0,  // 0: asset.Asset.Status:type_name -> asset.AssetStatus
	1,  // 1: asset.Asset.Reason:type_name -> asset.Reason
	18, // 2: asset.Asset.CreatedAt:type_name -> google.protobuf.Timestamp
	18, // 3: asset.Asset.UpdatedAt:type_name -> google.protobuf.Timestamp
	2,  // 4: asset.Asset.Type:type_name -> asset.AssetType
	8,  // 5: asset.Asset.StockProperties:type_name -> asset.StockProperties
	5,  // 6: asset.Assets.Assets:type_name -> asset.Asset
	3,  // 7: asset.UserAssetList.Status:type_name -> asset.UserAssetStatus
	18, // 8: asset.UserAssetList.CreatedAt:type_name -> google.protobuf.Timestamp
	18, // 9: asset.UserAssetList.UpdatedAt:type_name -> google.protobuf.Timestamp
	9,  // 10: asset.UserAssetLists.UserAssetLists:type_name -> asset.UserAssetList
	18, // 11: asset.Jurisdiction.CreatedAt:type_name -> google.protobuf.Timestamp
	18, // 12: asset.Jurisdiction.UpdatedAt:type_name -> google.protobuf.Timestamp
	12, // 13: asset.Jurisdictions.Jurisdictions:type_name -> asset.Jurisdiction
	4,  // 14: asset.UserJurisdiction.Status:type_name -> asset.UserJurisdictionStatus
	18, // 15: asset.UserJurisdiction.CreatedAt:type_name -> google.protobuf.Timestamp
	18, // 16: asset.UserJurisdiction.UpdatedAt:type_name -> google.protobuf.Timestamp
	15, // 17: asset.UserJurisdictions.UserJurisdictions:type_name -> asset.UserJurisdiction
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_asset_proto_init() }
func file_asset_proto_init() {
	if File_asset_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_asset_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Asset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asset_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssetID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asset_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Assets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asset_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockProperties); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asset_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAssetList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asset_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAssetListID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asset_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAssetLists); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asset_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Jurisdiction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asset_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JurisdictionID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asset_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Jurisdictions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asset_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserJurisdiction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asset_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserJurisdictionID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asset_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserJurisdictions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_asset_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Asset_StockProperties)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_asset_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_asset_proto_goTypes,
		DependencyIndexes: file_asset_proto_depIdxs,
		EnumInfos:         file_asset_proto_enumTypes,
		MessageInfos:      file_asset_proto_msgTypes,
	}.Build()
	File_asset_proto = out.File
	file_asset_proto_rawDesc = nil
	file_asset_proto_goTypes = nil
	file_asset_proto_depIdxs = nil
}
