// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.26.1
// source: asset-grpc.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import _m0 from "protobufjs/minimal";
import {
  Asset,
  Assets,
  AssetStatus,
  assetStatusFromJSON,
  assetStatusToJSON,
  AssetType,
  assetTypeFromJSON,
  assetTypeToJSON,
} from "./asset";
import { Network, networkFromJSON, networkToJSON } from "./sologenic/com-fs-utils-lib/models/metadata/metadata";

export const protobufPackage = "asset";

export interface AssetKey {
  Key: string;
}

export interface AssetQuery {
  Network: Network;
  Offset?: number | undefined;
  JurisdictionIDs: string[];
  OrganizationID?: string | undefined;
  Status?: AssetStatus | undefined;
  AssetType?: AssetType | undefined;
  ExchangeTickerSymbol?: string | undefined;
  Exchange?: string | undefined;
  Symbol?: string | undefined;
  Version?: string | undefined;
  Issuer?: string | undefined;
}

function createBaseAssetKey(): AssetKey {
  return { Key: "" };
}

export const AssetKey = {
  encode(message: AssetKey, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Key !== "") {
      writer.uint32(10).string(message.Key);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): AssetKey {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAssetKey();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Key = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AssetKey {
    return { Key: isSet(object.Key) ? globalThis.String(object.Key) : "" };
  },

  toJSON(message: AssetKey): unknown {
    const obj: any = {};
    if (message.Key !== "") {
      obj.Key = message.Key;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AssetKey>, I>>(base?: I): AssetKey {
    return AssetKey.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AssetKey>, I>>(object: I): AssetKey {
    const message = createBaseAssetKey();
    message.Key = object.Key ?? "";
    return message;
  },
};

function createBaseAssetQuery(): AssetQuery {
  return {
    Network: 0,
    Offset: undefined,
    JurisdictionIDs: [],
    OrganizationID: undefined,
    Status: undefined,
    AssetType: undefined,
    ExchangeTickerSymbol: undefined,
    Exchange: undefined,
    Symbol: undefined,
    Version: undefined,
    Issuer: undefined,
  };
}

export const AssetQuery = {
  encode(message: AssetQuery, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Network !== 0) {
      writer.uint32(8).int32(message.Network);
    }
    if (message.Offset !== undefined) {
      writer.uint32(16).int32(message.Offset);
    }
    for (const v of message.JurisdictionIDs) {
      writer.uint32(26).string(v!);
    }
    if (message.OrganizationID !== undefined) {
      writer.uint32(34).string(message.OrganizationID);
    }
    if (message.Status !== undefined) {
      writer.uint32(40).int32(message.Status);
    }
    if (message.AssetType !== undefined) {
      writer.uint32(48).int32(message.AssetType);
    }
    if (message.ExchangeTickerSymbol !== undefined) {
      writer.uint32(58).string(message.ExchangeTickerSymbol);
    }
    if (message.Exchange !== undefined) {
      writer.uint32(66).string(message.Exchange);
    }
    if (message.Symbol !== undefined) {
      writer.uint32(74).string(message.Symbol);
    }
    if (message.Version !== undefined) {
      writer.uint32(82).string(message.Version);
    }
    if (message.Issuer !== undefined) {
      writer.uint32(90).string(message.Issuer);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): AssetQuery {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAssetQuery();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.Network = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.Offset = reader.int32();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.JurisdictionIDs.push(reader.string());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.OrganizationID = reader.string();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.Status = reader.int32() as any;
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.AssetType = reader.int32() as any;
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.ExchangeTickerSymbol = reader.string();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.Exchange = reader.string();
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.Symbol = reader.string();
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.Version = reader.string();
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.Issuer = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AssetQuery {
    return {
      Network: isSet(object.Network) ? networkFromJSON(object.Network) : 0,
      Offset: isSet(object.Offset) ? globalThis.Number(object.Offset) : undefined,
      JurisdictionIDs: globalThis.Array.isArray(object?.JurisdictionIDs)
        ? object.JurisdictionIDs.map((e: any) => globalThis.String(e))
        : [],
      OrganizationID: isSet(object.OrganizationID) ? globalThis.String(object.OrganizationID) : undefined,
      Status: isSet(object.Status) ? assetStatusFromJSON(object.Status) : undefined,
      AssetType: isSet(object.AssetType) ? assetTypeFromJSON(object.AssetType) : undefined,
      ExchangeTickerSymbol: isSet(object.ExchangeTickerSymbol)
        ? globalThis.String(object.ExchangeTickerSymbol)
        : undefined,
      Exchange: isSet(object.Exchange) ? globalThis.String(object.Exchange) : undefined,
      Symbol: isSet(object.Symbol) ? globalThis.String(object.Symbol) : undefined,
      Version: isSet(object.Version) ? globalThis.String(object.Version) : undefined,
      Issuer: isSet(object.Issuer) ? globalThis.String(object.Issuer) : undefined,
    };
  },

  toJSON(message: AssetQuery): unknown {
    const obj: any = {};
    if (message.Network !== 0) {
      obj.Network = networkToJSON(message.Network);
    }
    if (message.Offset !== undefined) {
      obj.Offset = Math.round(message.Offset);
    }
    if (message.JurisdictionIDs?.length) {
      obj.JurisdictionIDs = message.JurisdictionIDs;
    }
    if (message.OrganizationID !== undefined) {
      obj.OrganizationID = message.OrganizationID;
    }
    if (message.Status !== undefined) {
      obj.Status = assetStatusToJSON(message.Status);
    }
    if (message.AssetType !== undefined) {
      obj.AssetType = assetTypeToJSON(message.AssetType);
    }
    if (message.ExchangeTickerSymbol !== undefined) {
      obj.ExchangeTickerSymbol = message.ExchangeTickerSymbol;
    }
    if (message.Exchange !== undefined) {
      obj.Exchange = message.Exchange;
    }
    if (message.Symbol !== undefined) {
      obj.Symbol = message.Symbol;
    }
    if (message.Version !== undefined) {
      obj.Version = message.Version;
    }
    if (message.Issuer !== undefined) {
      obj.Issuer = message.Issuer;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AssetQuery>, I>>(base?: I): AssetQuery {
    return AssetQuery.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AssetQuery>, I>>(object: I): AssetQuery {
    const message = createBaseAssetQuery();
    message.Network = object.Network ?? 0;
    message.Offset = object.Offset ?? undefined;
    message.JurisdictionIDs = object.JurisdictionIDs?.map((e) => e) || [];
    message.OrganizationID = object.OrganizationID ?? undefined;
    message.Status = object.Status ?? undefined;
    message.AssetType = object.AssetType ?? undefined;
    message.ExchangeTickerSymbol = object.ExchangeTickerSymbol ?? undefined;
    message.Exchange = object.Exchange ?? undefined;
    message.Symbol = object.Symbol ?? undefined;
    message.Version = object.Version ?? undefined;
    message.Issuer = object.Issuer ?? undefined;
    return message;
  },
};

export type AssetServiceService = typeof AssetServiceService;
export const AssetServiceService = {
  get: {
    path: "/asset.AssetService/Get",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: AssetKey) => Buffer.from(AssetKey.encode(value).finish()),
    requestDeserialize: (value: Buffer) => AssetKey.decode(value),
    responseSerialize: (value: Asset) => Buffer.from(Asset.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Asset.decode(value),
  },
  list: {
    path: "/asset.AssetService/List",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: AssetQuery) => Buffer.from(AssetQuery.encode(value).finish()),
    requestDeserialize: (value: Buffer) => AssetQuery.decode(value),
    responseSerialize: (value: Assets) => Buffer.from(Assets.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Assets.decode(value),
  },
  upsert: {
    path: "/asset.AssetService/Upsert",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: Asset) => Buffer.from(Asset.encode(value).finish()),
    requestDeserialize: (value: Buffer) => Asset.decode(value),
    responseSerialize: (value: AssetKey) => Buffer.from(AssetKey.encode(value).finish()),
    responseDeserialize: (value: Buffer) => AssetKey.decode(value),
  },
} as const;

export interface AssetServiceServer extends UntypedServiceImplementation {
  get: handleUnaryCall<AssetKey, Asset>;
  list: handleUnaryCall<AssetQuery, Assets>;
  upsert: handleUnaryCall<Asset, AssetKey>;
}

export interface AssetServiceClient extends Client {
  get(request: AssetKey, callback: (error: ServiceError | null, response: Asset) => void): ClientUnaryCall;
  get(
    request: AssetKey,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Asset) => void,
  ): ClientUnaryCall;
  get(
    request: AssetKey,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Asset) => void,
  ): ClientUnaryCall;
  list(request: AssetQuery, callback: (error: ServiceError | null, response: Assets) => void): ClientUnaryCall;
  list(
    request: AssetQuery,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Assets) => void,
  ): ClientUnaryCall;
  list(
    request: AssetQuery,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Assets) => void,
  ): ClientUnaryCall;
  upsert(request: Asset, callback: (error: ServiceError | null, response: AssetKey) => void): ClientUnaryCall;
  upsert(
    request: Asset,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: AssetKey) => void,
  ): ClientUnaryCall;
  upsert(
    request: Asset,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: AssetKey) => void,
  ): ClientUnaryCall;
}

export const AssetServiceClient = makeGenericClientConstructor(
  AssetServiceService,
  "asset.AssetService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): AssetServiceClient;
  service: typeof AssetServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
