// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.26.1
// source: user-asset-list-grpc.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import _m0 from "protobufjs/minimal";
import { Network, networkFromJSON, networkToJSON } from "./sologenic/com-fs-utils-lib/models/metadata/metadata";
import {
  UserAssetList,
  UserAssetLists,
  UserAssetStatus,
  userAssetStatusFromJSON,
  userAssetStatusToJSON,
} from "./user-asset-list";

export const protobufPackage = "asset";

export interface UserAssetListKey {
  Key: string;
}

export interface UserAssetListQuery {
  Network: Network;
  Offset?: number | undefined;
  AccountID?: string | undefined;
  Wallet?: string | undefined;
  AssetKey?: string | undefined;
  Status?: UserAssetStatus | undefined;
  Visible?: boolean | undefined;
}

function createBaseUserAssetListKey(): UserAssetListKey {
  return { Key: "" };
}

export const UserAssetListKey = {
  encode(message: UserAssetListKey, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Key !== "") {
      writer.uint32(10).string(message.Key);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): UserAssetListKey {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserAssetListKey();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Key = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserAssetListKey {
    return { Key: isSet(object.Key) ? globalThis.String(object.Key) : "" };
  },

  toJSON(message: UserAssetListKey): unknown {
    const obj: any = {};
    if (message.Key !== "") {
      obj.Key = message.Key;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserAssetListKey>, I>>(base?: I): UserAssetListKey {
    return UserAssetListKey.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserAssetListKey>, I>>(object: I): UserAssetListKey {
    const message = createBaseUserAssetListKey();
    message.Key = object.Key ?? "";
    return message;
  },
};

function createBaseUserAssetListQuery(): UserAssetListQuery {
  return {
    Network: 0,
    Offset: undefined,
    AccountID: undefined,
    Wallet: undefined,
    AssetKey: undefined,
    Status: undefined,
    Visible: undefined,
  };
}

export const UserAssetListQuery = {
  encode(message: UserAssetListQuery, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Network !== 0) {
      writer.uint32(8).int32(message.Network);
    }
    if (message.Offset !== undefined) {
      writer.uint32(16).int32(message.Offset);
    }
    if (message.AccountID !== undefined) {
      writer.uint32(26).string(message.AccountID);
    }
    if (message.Wallet !== undefined) {
      writer.uint32(34).string(message.Wallet);
    }
    if (message.AssetKey !== undefined) {
      writer.uint32(42).string(message.AssetKey);
    }
    if (message.Status !== undefined) {
      writer.uint32(48).int32(message.Status);
    }
    if (message.Visible !== undefined) {
      writer.uint32(56).bool(message.Visible);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): UserAssetListQuery {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserAssetListQuery();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.Network = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.Offset = reader.int32();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.AccountID = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.Wallet = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.AssetKey = reader.string();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.Status = reader.int32() as any;
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.Visible = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserAssetListQuery {
    return {
      Network: isSet(object.Network) ? networkFromJSON(object.Network) : 0,
      Offset: isSet(object.Offset) ? globalThis.Number(object.Offset) : undefined,
      AccountID: isSet(object.AccountID) ? globalThis.String(object.AccountID) : undefined,
      Wallet: isSet(object.Wallet) ? globalThis.String(object.Wallet) : undefined,
      AssetKey: isSet(object.AssetKey) ? globalThis.String(object.AssetKey) : undefined,
      Status: isSet(object.Status) ? userAssetStatusFromJSON(object.Status) : undefined,
      Visible: isSet(object.Visible) ? globalThis.Boolean(object.Visible) : undefined,
    };
  },

  toJSON(message: UserAssetListQuery): unknown {
    const obj: any = {};
    if (message.Network !== 0) {
      obj.Network = networkToJSON(message.Network);
    }
    if (message.Offset !== undefined) {
      obj.Offset = Math.round(message.Offset);
    }
    if (message.AccountID !== undefined) {
      obj.AccountID = message.AccountID;
    }
    if (message.Wallet !== undefined) {
      obj.Wallet = message.Wallet;
    }
    if (message.AssetKey !== undefined) {
      obj.AssetKey = message.AssetKey;
    }
    if (message.Status !== undefined) {
      obj.Status = userAssetStatusToJSON(message.Status);
    }
    if (message.Visible !== undefined) {
      obj.Visible = message.Visible;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserAssetListQuery>, I>>(base?: I): UserAssetListQuery {
    return UserAssetListQuery.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserAssetListQuery>, I>>(object: I): UserAssetListQuery {
    const message = createBaseUserAssetListQuery();
    message.Network = object.Network ?? 0;
    message.Offset = object.Offset ?? undefined;
    message.AccountID = object.AccountID ?? undefined;
    message.Wallet = object.Wallet ?? undefined;
    message.AssetKey = object.AssetKey ?? undefined;
    message.Status = object.Status ?? undefined;
    message.Visible = object.Visible ?? undefined;
    return message;
  },
};

export type UserAssetListServiceService = typeof UserAssetListServiceService;
export const UserAssetListServiceService = {
  get: {
    path: "/asset.UserAssetListService/Get",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UserAssetListKey) => Buffer.from(UserAssetListKey.encode(value).finish()),
    requestDeserialize: (value: Buffer) => UserAssetListKey.decode(value),
    responseSerialize: (value: UserAssetList) => Buffer.from(UserAssetList.encode(value).finish()),
    responseDeserialize: (value: Buffer) => UserAssetList.decode(value),
  },
  list: {
    path: "/asset.UserAssetListService/List",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UserAssetListQuery) => Buffer.from(UserAssetListQuery.encode(value).finish()),
    requestDeserialize: (value: Buffer) => UserAssetListQuery.decode(value),
    responseSerialize: (value: UserAssetLists) => Buffer.from(UserAssetLists.encode(value).finish()),
    responseDeserialize: (value: Buffer) => UserAssetLists.decode(value),
  },
  upsert: {
    path: "/asset.UserAssetListService/Upsert",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UserAssetList) => Buffer.from(UserAssetList.encode(value).finish()),
    requestDeserialize: (value: Buffer) => UserAssetList.decode(value),
    responseSerialize: (value: UserAssetListKey) => Buffer.from(UserAssetListKey.encode(value).finish()),
    responseDeserialize: (value: Buffer) => UserAssetListKey.decode(value),
  },
} as const;

export interface UserAssetListServiceServer extends UntypedServiceImplementation {
  get: handleUnaryCall<UserAssetListKey, UserAssetList>;
  list: handleUnaryCall<UserAssetListQuery, UserAssetLists>;
  upsert: handleUnaryCall<UserAssetList, UserAssetListKey>;
}

export interface UserAssetListServiceClient extends Client {
  get(
    request: UserAssetListKey,
    callback: (error: ServiceError | null, response: UserAssetList) => void,
  ): ClientUnaryCall;
  get(
    request: UserAssetListKey,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UserAssetList) => void,
  ): ClientUnaryCall;
  get(
    request: UserAssetListKey,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UserAssetList) => void,
  ): ClientUnaryCall;
  list(
    request: UserAssetListQuery,
    callback: (error: ServiceError | null, response: UserAssetLists) => void,
  ): ClientUnaryCall;
  list(
    request: UserAssetListQuery,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UserAssetLists) => void,
  ): ClientUnaryCall;
  list(
    request: UserAssetListQuery,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UserAssetLists) => void,
  ): ClientUnaryCall;
  upsert(
    request: UserAssetList,
    callback: (error: ServiceError | null, response: UserAssetListKey) => void,
  ): ClientUnaryCall;
  upsert(
    request: UserAssetList,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UserAssetListKey) => void,
  ): ClientUnaryCall;
  upsert(
    request: UserAssetList,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UserAssetListKey) => void,
  ): ClientUnaryCall;
}

export const UserAssetListServiceClient = makeGenericClientConstructor(
  UserAssetListServiceService,
  "asset.UserAssetListService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): UserAssetListServiceClient;
  service: typeof UserAssetListServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
