// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.26.1
// source: user-asset-list.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { MetaData } from "./sologenic/com-fs-utils-lib/models/metadata/metadata";

export const protobufPackage = "asset";

export enum UserAssetStatus {
  USER_ASSET_STATUS_DO_NOT_USE = 0,
  NOT_WHITELISTED = 1,
  WHITELISTING_REQUESTED = 2,
  WHITELISTED = 3,
  OUTDATED_VERSION = 4,
  UNRECOGNIZED = -1,
}

export function userAssetStatusFromJSON(object: any): UserAssetStatus {
  switch (object) {
    case 0:
    case "USER_ASSET_STATUS_DO_NOT_USE":
      return UserAssetStatus.USER_ASSET_STATUS_DO_NOT_USE;
    case 1:
    case "NOT_WHITELISTED":
      return UserAssetStatus.NOT_WHITELISTED;
    case 2:
    case "WHITELISTING_REQUESTED":
      return UserAssetStatus.WHITELISTING_REQUESTED;
    case 3:
    case "WHITELISTED":
      return UserAssetStatus.WHITELISTED;
    case 4:
    case "OUTDATED_VERSION":
      return UserAssetStatus.OUTDATED_VERSION;
    case -1:
    case "UNRECOGNIZED":
    default:
      return UserAssetStatus.UNRECOGNIZED;
  }
}

export function userAssetStatusToJSON(object: UserAssetStatus): string {
  switch (object) {
    case UserAssetStatus.USER_ASSET_STATUS_DO_NOT_USE:
      return "USER_ASSET_STATUS_DO_NOT_USE";
    case UserAssetStatus.NOT_WHITELISTED:
      return "NOT_WHITELISTED";
    case UserAssetStatus.WHITELISTING_REQUESTED:
      return "WHITELISTING_REQUESTED";
    case UserAssetStatus.WHITELISTED:
      return "WHITELISTED";
    case UserAssetStatus.OUTDATED_VERSION:
      return "OUTDATED_VERSION";
    case UserAssetStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Key: Currency-OrganizationID-AccountID-Wallet (AssetKey-AccountID-Wallet) */
export interface UserAssetList {
  AccountID: string;
  Wallet: string;
  /** Currency-OrganizationID */
  AssetKey: string;
  Status: UserAssetStatus;
  MetaData: MetaData | undefined;
  Visible: boolean;
}

export interface UserAssetLists {
  UserAssetLists: UserAssetList[];
}

function createBaseUserAssetList(): UserAssetList {
  return { AccountID: "", Wallet: "", AssetKey: "", Status: 0, MetaData: undefined, Visible: false };
}

export const UserAssetList = {
  encode(message: UserAssetList, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.AccountID !== "") {
      writer.uint32(10).string(message.AccountID);
    }
    if (message.Wallet !== "") {
      writer.uint32(18).string(message.Wallet);
    }
    if (message.AssetKey !== "") {
      writer.uint32(26).string(message.AssetKey);
    }
    if (message.Status !== 0) {
      writer.uint32(32).int32(message.Status);
    }
    if (message.MetaData !== undefined) {
      MetaData.encode(message.MetaData, writer.uint32(42).fork()).ldelim();
    }
    if (message.Visible !== false) {
      writer.uint32(48).bool(message.Visible);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): UserAssetList {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserAssetList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.AccountID = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.Wallet = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.AssetKey = reader.string();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.Status = reader.int32() as any;
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.MetaData = MetaData.decode(reader, reader.uint32());
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.Visible = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserAssetList {
    return {
      AccountID: isSet(object.AccountID) ? globalThis.String(object.AccountID) : "",
      Wallet: isSet(object.Wallet) ? globalThis.String(object.Wallet) : "",
      AssetKey: isSet(object.AssetKey) ? globalThis.String(object.AssetKey) : "",
      Status: isSet(object.Status) ? userAssetStatusFromJSON(object.Status) : 0,
      MetaData: isSet(object.MetaData) ? MetaData.fromJSON(object.MetaData) : undefined,
      Visible: isSet(object.Visible) ? globalThis.Boolean(object.Visible) : false,
    };
  },

  toJSON(message: UserAssetList): unknown {
    const obj: any = {};
    if (message.AccountID !== "") {
      obj.AccountID = message.AccountID;
    }
    if (message.Wallet !== "") {
      obj.Wallet = message.Wallet;
    }
    if (message.AssetKey !== "") {
      obj.AssetKey = message.AssetKey;
    }
    if (message.Status !== 0) {
      obj.Status = userAssetStatusToJSON(message.Status);
    }
    if (message.MetaData !== undefined) {
      obj.MetaData = MetaData.toJSON(message.MetaData);
    }
    if (message.Visible !== false) {
      obj.Visible = message.Visible;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserAssetList>, I>>(base?: I): UserAssetList {
    return UserAssetList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserAssetList>, I>>(object: I): UserAssetList {
    const message = createBaseUserAssetList();
    message.AccountID = object.AccountID ?? "";
    message.Wallet = object.Wallet ?? "";
    message.AssetKey = object.AssetKey ?? "";
    message.Status = object.Status ?? 0;
    message.MetaData = (object.MetaData !== undefined && object.MetaData !== null)
      ? MetaData.fromPartial(object.MetaData)
      : undefined;
    message.Visible = object.Visible ?? false;
    return message;
  },
};

function createBaseUserAssetLists(): UserAssetLists {
  return { UserAssetLists: [] };
}

export const UserAssetLists = {
  encode(message: UserAssetLists, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.UserAssetLists) {
      UserAssetList.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): UserAssetLists {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserAssetLists();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.UserAssetLists.push(UserAssetList.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserAssetLists {
    return {
      UserAssetLists: globalThis.Array.isArray(object?.UserAssetLists)
        ? object.UserAssetLists.map((e: any) => UserAssetList.fromJSON(e))
        : [],
    };
  },

  toJSON(message: UserAssetLists): unknown {
    const obj: any = {};
    if (message.UserAssetLists?.length) {
      obj.UserAssetLists = message.UserAssetLists.map((e) => UserAssetList.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserAssetLists>, I>>(base?: I): UserAssetLists {
    return UserAssetLists.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserAssetLists>, I>>(object: I): UserAssetLists {
    const message = createBaseUserAssetLists();
    message.UserAssetLists = object.UserAssetLists?.map((e) => UserAssetList.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
