// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: user-asset-list.proto

package asset

import (
	metadata "github.com/sologenic/com-fs-utils-lib/models/metadata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserAssetStatus int32

const (
	UserAssetStatus_USER_ASSET_STATUS_DO_NOT_USE UserAssetStatus = 0
	UserAssetStatus_NOT_WHITELISTED              UserAssetStatus = 1
	UserAssetStatus_WHITELISTING_REQUESTED       UserAssetStatus = 2
	UserAssetStatus_WHITELISTED                  UserAssetStatus = 3
	UserAssetStatus_OUTDATED_VERSION             UserAssetStatus = 4
)

// Enum value maps for UserAssetStatus.
var (
	UserAssetStatus_name = map[int32]string{
		0: "USER_ASSET_STATUS_DO_NOT_USE",
		1: "NOT_WHITELISTED",
		2: "WHITELISTING_REQUESTED",
		3: "WHITELISTED",
		4: "OUTDATED_VERSION",
	}
	UserAssetStatus_value = map[string]int32{
		"USER_ASSET_STATUS_DO_NOT_USE": 0,
		"NOT_WHITELISTED":              1,
		"WHITELISTING_REQUESTED":       2,
		"WHITELISTED":                  3,
		"OUTDATED_VERSION":             4,
	}
)

func (x UserAssetStatus) Enum() *UserAssetStatus {
	p := new(UserAssetStatus)
	*p = x
	return p
}

func (x UserAssetStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserAssetStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_user_asset_list_proto_enumTypes[0].Descriptor()
}

func (UserAssetStatus) Type() protoreflect.EnumType {
	return &file_user_asset_list_proto_enumTypes[0]
}

func (x UserAssetStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserAssetStatus.Descriptor instead.
func (UserAssetStatus) EnumDescriptor() ([]byte, []int) {
	return file_user_asset_list_proto_rawDescGZIP(), []int{0}
}

// Key: Currency-OrganizationID-AccountID-Wallet (AssetKey-AccountID-Wallet)
type UserAssetList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountID string             `protobuf:"bytes,1,opt,name=AccountID,proto3" json:"AccountID,omitempty"`
	Wallet    string             `protobuf:"bytes,2,opt,name=Wallet,proto3" json:"Wallet,omitempty"`
	AssetKey  string             `protobuf:"bytes,3,opt,name=AssetKey,proto3" json:"AssetKey,omitempty"` // Currency-OrganizationID
	Status    UserAssetStatus    `protobuf:"varint,4,opt,name=Status,proto3,enum=asset.UserAssetStatus" json:"Status,omitempty"`
	MetaData  *metadata.MetaData `protobuf:"bytes,5,opt,name=MetaData,proto3" json:"MetaData,omitempty"`
	Visible   bool               `protobuf:"varint,6,opt,name=Visible,proto3" json:"Visible,omitempty"`
}

func (x *UserAssetList) Reset() {
	*x = UserAssetList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_asset_list_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAssetList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAssetList) ProtoMessage() {}

func (x *UserAssetList) ProtoReflect() protoreflect.Message {
	mi := &file_user_asset_list_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAssetList.ProtoReflect.Descriptor instead.
func (*UserAssetList) Descriptor() ([]byte, []int) {
	return file_user_asset_list_proto_rawDescGZIP(), []int{0}
}

func (x *UserAssetList) GetAccountID() string {
	if x != nil {
		return x.AccountID
	}
	return ""
}

func (x *UserAssetList) GetWallet() string {
	if x != nil {
		return x.Wallet
	}
	return ""
}

func (x *UserAssetList) GetAssetKey() string {
	if x != nil {
		return x.AssetKey
	}
	return ""
}

func (x *UserAssetList) GetStatus() UserAssetStatus {
	if x != nil {
		return x.Status
	}
	return UserAssetStatus_USER_ASSET_STATUS_DO_NOT_USE
}

func (x *UserAssetList) GetMetaData() *metadata.MetaData {
	if x != nil {
		return x.MetaData
	}
	return nil
}

func (x *UserAssetList) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

type UserAssetLists struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserAssetLists []*UserAssetList `protobuf:"bytes,1,rep,name=UserAssetLists,proto3" json:"UserAssetLists,omitempty"`
}

func (x *UserAssetLists) Reset() {
	*x = UserAssetLists{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_asset_list_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAssetLists) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAssetLists) ProtoMessage() {}

func (x *UserAssetLists) ProtoReflect() protoreflect.Message {
	mi := &file_user_asset_list_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAssetLists.ProtoReflect.Descriptor instead.
func (*UserAssetLists) Descriptor() ([]byte, []int) {
	return file_user_asset_list_proto_rawDescGZIP(), []int{1}
}

func (x *UserAssetLists) GetUserAssetLists() []*UserAssetList {
	if x != nil {
		return x.UserAssetLists
	}
	return nil
}

var File_user_asset_list_proto protoreflect.FileDescriptor

var file_user_asset_list_proto_rawDesc = []byte{
	0x0a, 0x15, 0x75, 0x73, 0x65, 0x72, 0x2d, 0x61, 0x73, 0x73, 0x65, 0x74, 0x2d, 0x6c, 0x69, 0x73,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61, 0x73, 0x73, 0x65, 0x74, 0x1a, 0x39,
	0x73, 0x6f, 0x6c, 0x6f, 0x67, 0x65, 0x6e, 0x69, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x2d, 0x66, 0x73,
	0x2d, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2d, 0x6c, 0x69, 0x62, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdb, 0x01, 0x0a, 0x0d, 0x55, 0x73,
	0x65, 0x72, 0x41, 0x73, 0x73, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x57, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x57, 0x61, 0x6c, 0x6c, 0x65,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x73, 0x73, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x41, 0x73, 0x73, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x2e, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e,
	0x61, 0x73, 0x73, 0x65, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x41, 0x73, 0x73, 0x65, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2e, 0x0a,
	0x08, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a,
	0x07, 0x56, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x56, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x22, 0x4e, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x41,
	0x73, 0x73, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x73, 0x12, 0x3c, 0x0a, 0x0e, 0x55, 0x73, 0x65,
	0x72, 0x41, 0x73, 0x73, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x41, 0x73,
	0x73, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x41, 0x73, 0x73,
	0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x73, 0x2a, 0x8b, 0x01, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72,
	0x41, 0x73, 0x73, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20, 0x0a, 0x1c, 0x55,
	0x53, 0x45, 0x52, 0x5f, 0x41, 0x53, 0x53, 0x45, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x44, 0x4f, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x55, 0x53, 0x45, 0x10, 0x00, 0x12, 0x13, 0x0a,
	0x0f, 0x4e, 0x4f, 0x54, 0x5f, 0x57, 0x48, 0x49, 0x54, 0x45, 0x4c, 0x49, 0x53, 0x54, 0x45, 0x44,
	0x10, 0x01, 0x12, 0x1a, 0x0a, 0x16, 0x57, 0x48, 0x49, 0x54, 0x45, 0x4c, 0x49, 0x53, 0x54, 0x49,
	0x4e, 0x47, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0f,
	0x0a, 0x0b, 0x57, 0x48, 0x49, 0x54, 0x45, 0x4c, 0x49, 0x53, 0x54, 0x45, 0x44, 0x10, 0x03, 0x12,
	0x14, 0x0a, 0x10, 0x4f, 0x55, 0x54, 0x44, 0x41, 0x54, 0x45, 0x44, 0x5f, 0x56, 0x45, 0x52, 0x53,
	0x49, 0x4f, 0x4e, 0x10, 0x04, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x6c, 0x6f, 0x67, 0x65, 0x6e, 0x69, 0x63, 0x2f, 0x63, 0x6f,
	0x6d, 0x2d, 0x66, 0x73, 0x2d, 0x61, 0x73, 0x73, 0x65, 0x74, 0x2d, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x3b, 0x61, 0x73, 0x73, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_asset_list_proto_rawDescOnce sync.Once
	file_user_asset_list_proto_rawDescData = file_user_asset_list_proto_rawDesc
)

func file_user_asset_list_proto_rawDescGZIP() []byte {
	file_user_asset_list_proto_rawDescOnce.Do(func() {
		file_user_asset_list_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_asset_list_proto_rawDescData)
	})
	return file_user_asset_list_proto_rawDescData
}

var file_user_asset_list_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_asset_list_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_asset_list_proto_goTypes = []interface{}{
	(UserAssetStatus)(0),      // 0: asset.UserAssetStatus
	(*UserAssetList)(nil),     // 1: asset.UserAssetList
	(*UserAssetLists)(nil),    // 2: asset.UserAssetLists
	(*metadata.MetaData)(nil), // 3: metadata.MetaData
}
var file_user_asset_list_proto_depIdxs = []int32{
	0, // 0: asset.UserAssetList.Status:type_name -> asset.UserAssetStatus
	3, // 1: asset.UserAssetList.MetaData:type_name -> metadata.MetaData
	1, // 2: asset.UserAssetLists.UserAssetLists:type_name -> asset.UserAssetList
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_user_asset_list_proto_init() }
func file_user_asset_list_proto_init() {
	if File_user_asset_list_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_asset_list_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAssetList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_asset_list_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAssetLists); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_asset_list_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_asset_list_proto_goTypes,
		DependencyIndexes: file_user_asset_list_proto_depIdxs,
		EnumInfos:         file_user_asset_list_proto_enumTypes,
		MessageInfos:      file_user_asset_list_proto_msgTypes,
	}.Build()
	File_user_asset_list_proto = out.File
	file_user_asset_list_proto_rawDesc = nil
	file_user_asset_list_proto_goTypes = nil
	file_user_asset_list_proto_depIdxs = nil
}
