// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: domain/symbol/symbol.proto

package symbol

import (
	denom "github.com/sologenic/com-fs-asset-model/domain/denom"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Symbol struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *denom.Denom           `protobuf:"bytes,1,opt,name=Base,proto3" json:"Base,omitempty"`
	Quote         *denom.Denom           `protobuf:"bytes,2,opt,name=Quote,proto3" json:"Quote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Symbol) Reset() {
	*x = Symbol{}
	mi := &file_domain_symbol_symbol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Symbol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Symbol) ProtoMessage() {}

func (x *Symbol) ProtoReflect() protoreflect.Message {
	mi := &file_domain_symbol_symbol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Symbol.ProtoReflect.Descriptor instead.
func (*Symbol) Descriptor() ([]byte, []int) {
	return file_domain_symbol_symbol_proto_rawDescGZIP(), []int{0}
}

func (x *Symbol) GetBase() *denom.Denom {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *Symbol) GetQuote() *denom.Denom {
	if x != nil {
		return x.Quote
	}
	return nil
}

var File_domain_symbol_symbol_proto protoreflect.FileDescriptor

const file_domain_symbol_symbol_proto_rawDesc = "" +
	"\n" +
	"\x1adomain/symbol/symbol.proto\x12\x06symbol\x1a5sologenic/com-fs-asset-model/domain/denom/denom.proto\"N\n" +
	"\x06Symbol\x12 \n" +
	"\x04Base\x18\x01 \x01(\v2\f.denom.DenomR\x04Base\x12\"\n" +
	"\x05Quote\x18\x02 \x01(\v2\f.denom.DenomR\x05QuoteB>Z<github.com/sologenic/com-fs-asset-model/domain/symbol;symbolb\x06proto3"

var (
	file_domain_symbol_symbol_proto_rawDescOnce sync.Once
	file_domain_symbol_symbol_proto_rawDescData []byte
)

func file_domain_symbol_symbol_proto_rawDescGZIP() []byte {
	file_domain_symbol_symbol_proto_rawDescOnce.Do(func() {
		file_domain_symbol_symbol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_symbol_symbol_proto_rawDesc), len(file_domain_symbol_symbol_proto_rawDesc)))
	})
	return file_domain_symbol_symbol_proto_rawDescData
}

var file_domain_symbol_symbol_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_domain_symbol_symbol_proto_goTypes = []any{
	(*Symbol)(nil),      // 0: symbol.Symbol
	(*denom.Denom)(nil), // 1: denom.Denom
}
var file_domain_symbol_symbol_proto_depIdxs = []int32{
	1, // 0: symbol.Symbol.Base:type_name -> denom.Denom
	1, // 1: symbol.Symbol.Quote:type_name -> denom.Denom
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_domain_symbol_symbol_proto_init() }
func file_domain_symbol_symbol_proto_init() {
	if File_domain_symbol_symbol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_symbol_symbol_proto_rawDesc), len(file_domain_symbol_symbol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_symbol_symbol_proto_goTypes,
		DependencyIndexes: file_domain_symbol_symbol_proto_depIdxs,
		MessageInfos:      file_domain_symbol_symbol_proto_msgTypes,
	}.Build()
	File_domain_symbol_symbol_proto = out.File
	file_domain_symbol_symbol_proto_goTypes = nil
	file_domain_symbol_symbol_proto_depIdxs = nil
}
