syntax = "proto3";

package denom;

import "sologenic/com-fs-asset-model/domain/currency/currency.proto";

option go_package = "github.com/sologenic/com-fs-asset-model/domain/denom;denom";

// Denom defines the on-chain denomination of a token and include on-chain data such as the issuer, precision, and description.
// It is constructed according to the following conventions:
//  1. Currency:  {lowercase(symbol)}_v{version}
//     - Example: "aapl_v1", "btc-usd_v2"
//  2. Subunit:   u{currency}
//     - Example: "uaapl_v1", "ubtc-usd_v2"
//  3. Denom:     {subunit}-{issuer}
//     - Example: "uaapl_v1-testcore1et29cek95pl0zralsf43u4uply0g9nmxnj7fyt9yfy74spch7fpq3f8j0e"
//     - Example: "ubab.a_v1-testcore1cd0ezxp06xauqhrrpm4xe3h7yx9xmmeqr23vffppngld54sh9hnqmmep6g"
message Denom {
    currency.Currency Currency = 1;  // Format: {symbol}_{version}
    string Subunit = 2; // Format: u{currency}
    string Issuer = 3;
    int64 Precision = 4; // Decimal precision for the share count. e.g, if set to 6, the smallest unit represents 0.000001 shares.
    string Description = 5; // On-chain description
}
