// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.26.1
// source: domain/denom/denom.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { Currency } from "../currency/currency";

export const protobufPackage = "denom";

/**
 * Denom defines the on-chain denomination of a token.
 * It is constructed according to the following conventions:
 *   1. Currency:  {lowercase(symbol)}_{version}
 *      - Example: "aapl_1", "btc-usd_2"
 *   2. Subunit:   u{currency}
 *      - Example: "uaapl_1"
 *   3. Denom:     {subunit}-{issuer}
 *      - Where issuer is the smart contract address.
 *      - Example: "uaapl_1-testcore1et29cek95pl0zralsf43u4uply0g9nmxnj7fyt9yfy74spch7fpq3f8j0e"
 */
export interface Denom {
  /** Format: {symbol}_{version} */
  Currency:
    | Currency
    | undefined;
  /** Format: u{currency} */
  Subunit: string;
  /** Smart contract address that issues the token(issuer) */
  SmartContractAddress: string;
}

function createBaseDenom(): Denom {
  return { Currency: undefined, Subunit: "", SmartContractAddress: "" };
}

export const Denom = {
  encode(message: Denom, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Currency !== undefined) {
      Currency.encode(message.Currency, writer.uint32(10).fork()).ldelim();
    }
    if (message.Subunit !== "") {
      writer.uint32(18).string(message.Subunit);
    }
    if (message.SmartContractAddress !== "") {
      writer.uint32(26).string(message.SmartContractAddress);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Denom {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDenom();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Currency = Currency.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.Subunit = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.SmartContractAddress = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Denom {
    return {
      Currency: isSet(object.Currency) ? Currency.fromJSON(object.Currency) : undefined,
      Subunit: isSet(object.Subunit) ? globalThis.String(object.Subunit) : "",
      SmartContractAddress: isSet(object.SmartContractAddress) ? globalThis.String(object.SmartContractAddress) : "",
    };
  },

  toJSON(message: Denom): unknown {
    const obj: any = {};
    if (message.Currency !== undefined) {
      obj.Currency = Currency.toJSON(message.Currency);
    }
    if (message.Subunit !== "") {
      obj.Subunit = message.Subunit;
    }
    if (message.SmartContractAddress !== "") {
      obj.SmartContractAddress = message.SmartContractAddress;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Denom>, I>>(base?: I): Denom {
    return Denom.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Denom>, I>>(object: I): Denom {
    const message = createBaseDenom();
    message.Currency = (object.Currency !== undefined && object.Currency !== null)
      ? Currency.fromPartial(object.Currency)
      : undefined;
    message.Subunit = object.Subunit ?? "";
    message.SmartContractAddress = object.SmartContractAddress ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
