// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v7.35.1
// source: domain/denom/denom.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { Currency } from "../../sologenic/com-fs-asset-model/domain/currency/currency";

export const protobufPackage = "denom";

/**
 * Denom defines the on-chain denomination of a token and include on-chain data such as the issuer, precision, and description.
 * It is constructed according to the following conventions:
 *  1. Currency:  {lowercase(symbol)}_v{version}
 *     - Example: "aapl_v1", "btc-usd_v2"
 *  2. Subunit:   u{currency}
 *     - Example: "uaapl_v1", "ubtc-usd_v2"
 *  3. Denom:     {subunit}-{issuer}
 *     - Example: "uaapl_v1-testcore1et29cek95pl0zralsf43u4uply0g9nmxnj7fyt9yfy74spch7fpq3f8j0e"
 *     - Example: "ubab.a_v1-testcore1cd0ezxp06xauqhrrpm4xe3h7yx9xmmeqr23vffppngld54sh9hnqmmep6g"
 */
export interface Denom {
  Currency: Currency | undefined;
  Subunit: string;
  Issuer: string;
}

function createBaseDenom(): Denom {
  return { Currency: undefined, Subunit: "", Issuer: "" };
}

export const Denom = {
  encode(message: Denom, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Currency !== undefined) {
      Currency.encode(message.Currency, writer.uint32(10).fork()).ldelim();
    }
    if (message.Subunit !== "") {
      writer.uint32(18).string(message.Subunit);
    }
    if (message.Issuer !== "") {
      writer.uint32(26).string(message.Issuer);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Denom {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDenom();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Currency = Currency.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.Subunit = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.Issuer = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Denom {
    return {
      Currency: isSet(object.Currency) ? Currency.fromJSON(object.Currency) : undefined,
      Subunit: isSet(object.Subunit) ? globalThis.String(object.Subunit) : "",
      Issuer: isSet(object.Issuer) ? globalThis.String(object.Issuer) : "",
    };
  },

  toJSON(message: Denom): unknown {
    const obj: any = {};
    if (message.Currency !== undefined) {
      obj.Currency = Currency.toJSON(message.Currency);
    }
    if (message.Subunit !== "") {
      obj.Subunit = message.Subunit;
    }
    if (message.Issuer !== "") {
      obj.Issuer = message.Issuer;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Denom>, I>>(base?: I): Denom {
    return Denom.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Denom>, I>>(object: I): Denom {
    const message = createBaseDenom();
    message.Currency = (object.Currency !== undefined && object.Currency !== null)
      ? Currency.fromPartial(object.Currency)
      : undefined;
    message.Subunit = object.Subunit ?? "";
    message.Issuer = object.Issuer ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
