// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: domain/denom/denom.proto

package denom

import (
	currency "github.com/sologenic/com-fs-asset-model/domain/currency"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Denom defines the on-chain denomination of a token and include on-chain data such as the issuer, precision, and description.
// It is constructed according to the following conventions:
//  1. Currency:  {lowercase(symbol)}_{version}
//     - Example: "aapl_1", "btc-usd_2"
//  2. Subunit:   su{currency}
//     - Example: "suaapl_1"
//  3. Denom:     {subunit}-{issuer}
//     - Example: "suaapl_1-testcore1et29cek95pl0zralsf43u4uply0g9nmxnj7fyt9yfy74spch7fpq3f8j0e"
type Denom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Currency    *currency.Currency `protobuf:"bytes,1,opt,name=Currency,proto3" json:"Currency,omitempty"` // Format: {symbol}_{version}
	Subunit     string             `protobuf:"bytes,2,opt,name=Subunit,proto3" json:"Subunit,omitempty"`   // Format: su{currency}
	Issuer      string             `protobuf:"bytes,3,opt,name=Issuer,proto3" json:"Issuer,omitempty"`
	Precision   uint32             `protobuf:"varint,4,opt,name=Precision,proto3" json:"Precision,omitempty"`    // Decimal precision for the share count. e.g, if set to 6, the smallest unit represents 0.000001 shares.
	Description string             `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"` // On-chain description
}

func (x *Denom) Reset() {
	*x = Denom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_denom_denom_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Denom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Denom) ProtoMessage() {}

func (x *Denom) ProtoReflect() protoreflect.Message {
	mi := &file_domain_denom_denom_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Denom.ProtoReflect.Descriptor instead.
func (*Denom) Descriptor() ([]byte, []int) {
	return file_domain_denom_denom_proto_rawDescGZIP(), []int{0}
}

func (x *Denom) GetCurrency() *currency.Currency {
	if x != nil {
		return x.Currency
	}
	return nil
}

func (x *Denom) GetSubunit() string {
	if x != nil {
		return x.Subunit
	}
	return ""
}

func (x *Denom) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *Denom) GetPrecision() uint32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *Denom) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_domain_denom_denom_proto protoreflect.FileDescriptor

var file_domain_denom_denom_proto_rawDesc = []byte{
	0x0a, 0x18, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x2f, 0x64,
	0x65, 0x6e, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x64, 0x65, 0x6e, 0x6f,
	0x6d, 0x1a, 0x1e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x63, 0x79, 0x2f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xa9, 0x01, 0x0a, 0x05, 0x44, 0x65, 0x6e, 0x6f, 0x6d, 0x12, 0x2e, 0x0a, 0x08, 0x43,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63,
	0x79, 0x52, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x53,
	0x75, 0x62, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x53, 0x75,
	0x62, 0x75, 0x6e, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x73, 0x73, 0x75, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x49, 0x73, 0x73, 0x75, 0x65, 0x72, 0x12, 0x1c, 0x0a,
	0x09, 0x50, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x50, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x3c, 0x5a,
	0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x6c, 0x6f,
	0x67, 0x65, 0x6e, 0x69, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x2d, 0x66, 0x73, 0x2d, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x2d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f,
	0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x3b, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_domain_denom_denom_proto_rawDescOnce sync.Once
	file_domain_denom_denom_proto_rawDescData = file_domain_denom_denom_proto_rawDesc
)

func file_domain_denom_denom_proto_rawDescGZIP() []byte {
	file_domain_denom_denom_proto_rawDescOnce.Do(func() {
		file_domain_denom_denom_proto_rawDescData = protoimpl.X.CompressGZIP(file_domain_denom_denom_proto_rawDescData)
	})
	return file_domain_denom_denom_proto_rawDescData
}

var file_domain_denom_denom_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_domain_denom_denom_proto_goTypes = []interface{}{
	(*Denom)(nil),             // 0: denom.Denom
	(*currency.Currency)(nil), // 1: currency.Currency
}
var file_domain_denom_denom_proto_depIdxs = []int32{
	1, // 0: denom.Denom.Currency:type_name -> currency.Currency
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_domain_denom_denom_proto_init() }
func file_domain_denom_denom_proto_init() {
	if File_domain_denom_denom_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_domain_denom_denom_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Denom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_domain_denom_denom_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_denom_denom_proto_goTypes,
		DependencyIndexes: file_domain_denom_denom_proto_depIdxs,
		MessageInfos:      file_domain_denom_denom_proto_msgTypes,
	}.Build()
	File_domain_denom_denom_proto = out.File
	file_domain_denom_denom_proto_rawDesc = nil
	file_domain_denom_denom_proto_goTypes = nil
	file_domain_denom_denom_proto_depIdxs = nil
}
