// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: domain/denom/denom.proto

package denom

import (
	currency "github.com/sologenic/com-fs-asset-model/domain/currency"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Denom defines the on-chain denomination of a token and include on-chain data such as the issuer, precision, and description.
// It is constructed according to the following conventions:
//  1. Currency:  {lowercase(symbol)}_{version}
//     - Example: "aapl_v1", "btc-usd_v2"
//  2. Subunit:   u{currency}
//     - Example: "uaapl_v1"
//  3. Denom:     {subunit}-{issuer}
//     - Example: "uaapl_v1-testcore1et29cek95pl0zralsf43u4uply0g9nmxnj7fyt9yfy74spch7fpq3f8j0e"
type Denom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      *currency.Currency     `protobuf:"bytes,1,opt,name=Currency,proto3" json:"Currency,omitempty"` // Format: {symbol}_{version}
	Subunit       string                 `protobuf:"bytes,2,opt,name=Subunit,proto3" json:"Subunit,omitempty"`   // Format: u{currency}
	Issuer        string                 `protobuf:"bytes,3,opt,name=Issuer,proto3" json:"Issuer,omitempty"`
	Precision     int64                  `protobuf:"varint,4,opt,name=Precision,proto3" json:"Precision,omitempty"`    // Decimal precision for the share count. e.g, if set to 6, the smallest unit represents 0.000001 shares.
	Description   string                 `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"` // On-chain description
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Denom) Reset() {
	*x = Denom{}
	mi := &file_domain_denom_denom_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Denom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Denom) ProtoMessage() {}

func (x *Denom) ProtoReflect() protoreflect.Message {
	mi := &file_domain_denom_denom_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Denom.ProtoReflect.Descriptor instead.
func (*Denom) Descriptor() ([]byte, []int) {
	return file_domain_denom_denom_proto_rawDescGZIP(), []int{0}
}

func (x *Denom) GetCurrency() *currency.Currency {
	if x != nil {
		return x.Currency
	}
	return nil
}

func (x *Denom) GetSubunit() string {
	if x != nil {
		return x.Subunit
	}
	return ""
}

func (x *Denom) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *Denom) GetPrecision() int64 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *Denom) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_domain_denom_denom_proto protoreflect.FileDescriptor

const file_domain_denom_denom_proto_rawDesc = "" +
	"\n" +
	"\x18domain/denom/denom.proto\x12\x05denom\x1a;sologenic/com-fs-asset-model/domain/currency/currency.proto\"\xa9\x01\n" +
	"\x05Denom\x12.\n" +
	"\bCurrency\x18\x01 \x01(\v2\x12.currency.CurrencyR\bCurrency\x12\x18\n" +
	"\aSubunit\x18\x02 \x01(\tR\aSubunit\x12\x16\n" +
	"\x06Issuer\x18\x03 \x01(\tR\x06Issuer\x12\x1c\n" +
	"\tPrecision\x18\x04 \x01(\x03R\tPrecision\x12 \n" +
	"\vDescription\x18\x05 \x01(\tR\vDescriptionB<Z:github.com/sologenic/com-fs-asset-model/domain/denom;denomb\x06proto3"

var (
	file_domain_denom_denom_proto_rawDescOnce sync.Once
	file_domain_denom_denom_proto_rawDescData []byte
)

func file_domain_denom_denom_proto_rawDescGZIP() []byte {
	file_domain_denom_denom_proto_rawDescOnce.Do(func() {
		file_domain_denom_denom_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_denom_denom_proto_rawDesc), len(file_domain_denom_denom_proto_rawDesc)))
	})
	return file_domain_denom_denom_proto_rawDescData
}

var file_domain_denom_denom_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_domain_denom_denom_proto_goTypes = []any{
	(*Denom)(nil),             // 0: denom.Denom
	(*currency.Currency)(nil), // 1: currency.Currency
}
var file_domain_denom_denom_proto_depIdxs = []int32{
	1, // 0: denom.Denom.Currency:type_name -> currency.Currency
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_domain_denom_denom_proto_init() }
func file_domain_denom_denom_proto_init() {
	if File_domain_denom_denom_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_denom_denom_proto_rawDesc), len(file_domain_denom_denom_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_denom_denom_proto_goTypes,
		DependencyIndexes: file_domain_denom_denom_proto_depIdxs,
		MessageInfos:      file_domain_denom_denom_proto_msgTypes,
	}.Build()
	File_domain_denom_denom_proto = out.File
	file_domain_denom_denom_proto_goTypes = nil
	file_domain_denom_denom_proto_depIdxs = nil
}
