// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v7.35.1
// source: domain/pair/pair.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { Denom } from "../../sologenic/com-fs-asset-model/domain/denom/denom";

export const protobufPackage = "pair";

export interface Pair {
  Base: Denom | undefined;
  Quote: Denom | undefined;
}

function createBasePair(): Pair {
  return { Base: undefined, Quote: undefined };
}

export const Pair = {
  encode(message: Pair, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Base !== undefined) {
      Denom.encode(message.Base, writer.uint32(10).fork()).ldelim();
    }
    if (message.Quote !== undefined) {
      Denom.encode(message.Quote, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Pair {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePair();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Base = Denom.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.Quote = Denom.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Pair {
    return {
      Base: isSet(object.Base) ? Denom.fromJSON(object.Base) : undefined,
      Quote: isSet(object.Quote) ? Denom.fromJSON(object.Quote) : undefined,
    };
  },

  toJSON(message: Pair): unknown {
    const obj: any = {};
    if (message.Base !== undefined) {
      obj.Base = Denom.toJSON(message.Base);
    }
    if (message.Quote !== undefined) {
      obj.Quote = Denom.toJSON(message.Quote);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Pair>, I>>(base?: I): Pair {
    return Pair.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Pair>, I>>(object: I): Pair {
    const message = createBasePair();
    message.Base = (object.Base !== undefined && object.Base !== null) ? Denom.fromPartial(object.Base) : undefined;
    message.Quote = (object.Quote !== undefined && object.Quote !== null) ? Denom.fromPartial(object.Quote) : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
