// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: domain/currency/currency.proto

package currency

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Currency struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User-entered ticker with format:[a-zA-Z0-9.\-]{1,45}. e.g., APPL, PLTR, MSFT, BAB.A, BTC-USD
	Symbol string `protobuf:"bytes,1,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	// Auto-incremented version (no leading zeros) with max length 3 characters (values 1 to 999)
	Version       string `protobuf:"bytes,2,opt,name=Version,proto3" json:"Version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Currency) Reset() {
	*x = Currency{}
	mi := &file_domain_currency_currency_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Currency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Currency) ProtoMessage() {}

func (x *Currency) ProtoReflect() protoreflect.Message {
	mi := &file_domain_currency_currency_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Currency.ProtoReflect.Descriptor instead.
func (*Currency) Descriptor() ([]byte, []int) {
	return file_domain_currency_currency_proto_rawDescGZIP(), []int{0}
}

func (x *Currency) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Currency) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_domain_currency_currency_proto protoreflect.FileDescriptor

const file_domain_currency_currency_proto_rawDesc = "" +
	"\n" +
	"\x1edomain/currency/currency.proto\x12\bcurrency\x1a\x1bbuf/validate/validate.proto\"z\n" +
	"\bCurrency\x127\n" +
	"\x06Symbol\x18\x01 \x01(\tB\x1f\xbaH\x1c\xc8\x01\x01r\x172\x15^[a-zA-Z0-9.-]{1,45}$R\x06Symbol\x125\n" +
	"\aVersion\x18\x02 \x01(\tB\x1b\xbaH\x18\xc8\x01\x01r\x132\x11^[1-9][0-9]{0,2}$R\aVersionBBZ@github.com/sologenic/com-fs-asset-model/domain/currency;currencyb\x06proto3"

var (
	file_domain_currency_currency_proto_rawDescOnce sync.Once
	file_domain_currency_currency_proto_rawDescData []byte
)

func file_domain_currency_currency_proto_rawDescGZIP() []byte {
	file_domain_currency_currency_proto_rawDescOnce.Do(func() {
		file_domain_currency_currency_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_currency_currency_proto_rawDesc), len(file_domain_currency_currency_proto_rawDesc)))
	})
	return file_domain_currency_currency_proto_rawDescData
}

var file_domain_currency_currency_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_domain_currency_currency_proto_goTypes = []any{
	(*Currency)(nil), // 0: currency.Currency
}
var file_domain_currency_currency_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_domain_currency_currency_proto_init() }
func file_domain_currency_currency_proto_init() {
	if File_domain_currency_currency_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_currency_currency_proto_rawDesc), len(file_domain_currency_currency_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_currency_currency_proto_goTypes,
		DependencyIndexes: file_domain_currency_currency_proto_depIdxs,
		MessageInfos:      file_domain_currency_currency_proto_msgTypes,
	}.Build()
	File_domain_currency_currency_proto = out.File
	file_domain_currency_currency_proto_goTypes = nil
	file_domain_currency_currency_proto_depIdxs = nil
}
